#!/usr/bin/env python3
"""Additional bounty hunter entries merged at generation time."""

from __future__ import annotations

from pathlib import Path

_catalog_path = Path(__file__).resolve().parent / "generate_bounty_hunter_catalog.py"
_code = _catalog_path.read_text()
_ns: dict = {"__file__": str(_catalog_path), "__name__": "_catalog_helpers"}
exec(compile(_code.split("def main()")[0], str(_catalog_path), "exec"), _ns)
bp = _ns["bp"]
_ev = _ns["_ev"]
_aff = _ns["_aff"]
_tl = _ns["_tl"]


def qb(
    name: str,
    specialty: str,
    homeworld: str,
    description: str,
    color: str,
    sources: str,
    silhouette: str,
    origin: str,
    conflict: str,
    methods: str,
    *,
    ancient: str = "",
    modern: str = "",
    reputation: str = "",
    impact: str = "",
    events: list[str] | None = None,
    affiliations: list[str] | None = None,
    timeline: list[tuple[str, str]] | None = None,
) -> dict:
    return bp(
        name,
        specialty,
        homeworld,
        description,
        color,
        sources,
        silhouette,
        {
            "origin_detail": origin,
            "ancient_detail": ancient or (
                f"{homeworld} supplied mercenary hunters to Old Republic charter markets and "
                f"Sith Empire shadow rolls long before {name} posted the contracts that made them infamous."
            ),
            "modern_detail": modern or (
                f"{name} remained active through Imperial guild consolidation, Rebellion-era "
                f"shadow postings, and New Republic amnesty debates—pucks archived on Nar Shaddaa, "
                f"Ord Mantell, and Nevarro alike."
            ),
            "conflict_detail": conflict,
            "methods_detail": methods,
            "reputation_detail": reputation or (
                f"Guild brokers classify {name} as a {specialty.lower()} whose name alone "
                f"changes negotiation posture—feared on the Rim, cited in ISB redacted annexes."
            ),
            "impact_detail": impact or (
                f"{name}'s captures and eliminations shifted local power wherever {homeworld} "
                f"expatriates compete for Hutt, Imperial, and syndicate contracts."
            ),
            "events": _ev(*(events or (f"Rises as {specialty.lower()} from {homeworld}", f"Accepts major Rim contract linked to {name}", "Survives guild restructuring after Endor"))),
            "affiliations": _aff(*(
                affiliations
                or ("Bounty Hunters' Guild", f"{homeworld} expatriate networks", "Hutt Cartel (contracted)", "Crime syndicates of the Outer Rim")
            )),
            "timeline": _tl(*(
                timeline
                or ((homeworld, f"Origins and early {specialty.lower()} training"), ("Active Era", "Major guild contracts"), ("Legacy", "Cited in hunter training archives"))
            )),
        },
    )


ADDITIONAL_BOUNTY_HUNTERS: list[dict] = [
    qb(
        "Kul Teska", "Cyborg Bounty Hunter", "Unknown",
        "Cybernetic hunter who wielded gravity-manipulation technology against the Republic during the Clone Wars.",
        "#64748b", "Clone Wars · The Clone Wars: Republic Heroes", "cyborg",
        "Kul Teska rebuilt himself after catastrophic injuries, selling gravity-weapon expertise to Separatist paymasters who wanted Jedi and clones crushed without fleet bombardment.",
        "Teska assaulted Republic staging worlds with localized gravity bombs, forcing clone battalions into kill zones before Jedi could evacuate civilians.",
        "Gravity gauntlets, cybernetic frame reinforcement, orbital drop strikes, and Separatist research labs—Teska weaponized physics where blasters failed.",
        ancient="Separatist R&D archives on Geonosis and Mustafar document earlier gravity-mercenary prototypes Teska perfected into personal hunter kit.",
        events=_ev("Rebuilt body after catastrophic battlefield loss", "Deploys gravity tech against Republic forces", "Fights Clone Wars heroes in Rim campaigns", "Separatist contractor on high-value Jedi targets"),
        affiliations=_aff("Confederacy of Independent Systems", "Separatist R&D contractors", "Bounty Hunters' Guild", "Geonosian weapons brokers"),
        timeline=_tl(("Injury", "Cybernetic reconstruction"), ("Clone Wars", "Gravity-weapon campaigns"), ("Republic Heroes", "Major Rim confrontation"), ("Legacy", "Tech-hunter cautionary archive")),
    ),
    qb(
        "Boushh", "Ubese Bounty Hunter", "Uba IV",
        "Ubese warrior whose armor and identity were famously borrowed to infiltrate Jabba's palace during the rescue of Han Solo.",
        "#991b1b", "Return of the Jedi · Comics", "helmet",
        "Boushh built a lethal reputation on Uba IV before Imperial isolation policies drove Ubese hunters into Hutt space, where Boushh's armor became synonymous with silent extraction.",
        "Boushk hunted Black Sun intermediaries on Nar Shaddaa and accepted Jabba-posted pucks before Leia Organa used the armor to breach the Hutt palace with a thermal detonator bluff.",
        "Ubese battle armor, vibroblades, thermal detonators, and isolationist clan training—Boushh preferred close-quarters intimidation over prolonged pursuit.",
        modern="After the armor's use at Jabba's palace, Ubese hunter gear became among the most counterfeited identities in the guild—every impostor measured against Boushh's original lethality.",
        events=_ev("Earns Ubese clan hunter prestige on Uba IV", "Posts bounties in Hutt space", "Armor used in Jabba palace infiltration", "Identity becomes guild legend and forgery target"),
        affiliations=_aff("Ubese hunter clans", "Black Sun (targets)", "Jabba the Hutt's court (contracted)", "Bounty Hunters' Guild"),
        timeline=_tl(("Uba IV", "Clan hunter training"), ("Hutt Space", "Independent contracts"), ("Jabba Era", "Palace court presence"), ("Legacy", "Armor iconography")),
    ),
    qb(
        "Skorr", "Trandoshan Bounty Hunter", "Trandosha",
        "Trandoshan hunter who tracked Ahsoka Tano during the Clone Wars, embodying scorekeeper zeal against Jedi targets.",
        "#65a30d", "Clone Wars", "trandoshan",
        "Skorr rose through Trandosha's scorekeeper lodges by capturing prey alive for trophy rites, then sold those skills to Separatist brokers hunting Jedi Padawans.",
        "Skorr pursued Ahsoka Tano across Rim waystations, using Trandoshan tracking instincts and guild backup to corner Jedi separated from clone support.",
        "Scorekeeper manacles, thermal nets, Trandoshan strength, and pack-hunter coordination—Skorr favored capture trophies over quick kills.",
        reputation="Ahsoka's survival against Skorr became a Padawan cautionary tale about Trandoshan persistence when Jedi operate alone.",
        events=_ev("Rises in Trandoshan scorekeeper lodges", "Accepts Separatist Jedi-hunting contracts", "Tracks Ahsoka Tano during Clone Wars", "Embodies Trandoshan trophy-hunter tradition"),
        affiliations=_aff("Trandoshan scorekeepers", "Confederacy of Independent Systems (contracted)", "Bounty Hunters' Guild", "Trandosha lodge networks"),
        timeline=_tl(("Trandosha", "Scorekeeper initiation"), ("Clone Wars", "Jedi-hunting contracts"), ("Ahsoka Pursuit", "Padawan hunt"), ("Legacy", "Trandoshan trophy legend")),
    ),
    qb(
        "Bric", "Trandoshan Guild Instructor", "Trandosha",
        "Trandoshan bounty hunter who trained gladiator recruits and tested assassin candidates for the guild on Serenno.",
        "#65a30d", "Clone Wars", "trandoshan",
        "Bric served as guild drillmaster on Serenno, breaking hunters in Moralo Eval's pipeline before they reached the box tournament—Trandoshan discipline as industry gatekeeper.",
        "Bric evaluated Cad Bane, Derrown, and dozens of box entrants, deciding which hunters were lethal enough for Separatist assassination contracts.",
        "Arena drill instruction, capture-kill metrics, Trandoshan intimidation, and guild authority—Bric shaped hunter quality before pucks were ever posted.",
        impact="Without instructors like Bric, Eval's box would have been spectacle without skill—guild historians credit him with raising Clone Wars hunter lethality.",
        events=_ev("Appointed guild instructor on Serenno", "Trains Moralo Eval box candidates", "Evaluates Cad Bane-era hunter roster", "Gatekeeps assassin recruitment pipeline"),
        affiliations=_aff("Bounty Hunters' Guild", "Moralo Eval's training cadre", "Trandoshan lodge authority", "Serenno gladiator circuits"),
        timeline=_tl(("Trandosha", "Hunter mastery"), ("Serenno", "Guild instructor posting"), ("Box Era", "Eval pipeline training"), ("Legacy", "Guild drillmaster archetype")),
    ),
    qb(
        "Todo 360", "Assassin Droid Bounty Hunter", "Holowan Labs",
        "Cad Bane's personal assassin droid partner who combined hunter precision with loyalty circuits tuned to the Duros gunslinger.",
        "#64748b", "Clone Wars", "droid",
        "Todo 360 was commissioned as Cad Bane's paired assassin droid, programmed for guild work where biological hunters needed mechanical backup inside secure facilities.",
        "Todo accompanied Bane on Senate hostage operations, holocron heists, and Coruscant infiltrations—droid hunter integration at the highest Clone Wars threat level.",
        "Integrated blaster arms, grappling appendages, compact chassis for ventilation infiltration, and Bane-synced tactical subroutines.",
        modern="Todo 360's partnership model influenced later IG-series hunter droids and Q9-0-style assassin postings in the New Republic era.",
        events=_ev("Commissioned as Cad Bane's partner droid", "Participates in Senate hostage crisis", "Supports Jedi Temple holocron heist", "Destroyed in Clone Wars operations"),
        affiliations=_aff("Cad Bane gang", "Holowan Labs (origin)", "Bounty Hunters' Guild", "Separatist contractor rolls"),
        timeline=_tl(("Activation", "Paired with Cad Bane"), ("Senate Crisis", "Hostage operation"), ("Temple Heist", "Holocron theft"), ("End", "Droid destroyed in field")),
    ),
    qb(
        "Ranzar Malk", "Mandalorian Bounty Broker", "Unknown",
        "Mandalorian fixer who assembled hunter crews for high-risk prison breaks and assassination contracts during the New Republic era.",
        "#0284c7", "Mandalorian", "mando",
        "Ranzar Malk operated a Bothan-5 space station crew, brokering hunter teams for Imperial remnant targets and Grogu abduction contracts.",
        "Ranzar hired Din Djarin, Q9-0, Xi'an, and Burg for a New Republic prisoner extraction that collapsed into double-cross and droid destruction.",
        "Crew assembly, orbital station logistics, Mandalorian credential verification, and cold-profit contract math—Ranzar rarely pulled triggers personally.",
        events=_ev("Runs Bothan-5 hunter broker station", "Assembles crew including Din Djarin", "Posts contract on Grogu", "Double-crosses Mandalorian allies"),
        affiliations=_aff("Ranzar Malk's crew", "Bothan-5 station", "Bounty Hunters' Guild", "Imperial remnant clients"),
        timeline=_tl(("Broker Era", "Bothan-5 operations"), ("Prison Break", "Assembles hunter crew"), ("Grogu Contract", "Assassination posting"), ("Betrayal", "Mandalorian double-cross")),
    ),
    qb(
        "Burg", "Devaronian Bounty Hunter", "Devaron",
        "Devaronian enforcer on Ranzar Malk's crew who combined horned intimidation with heavy blaster work on prison-ship raids.",
        "#991b1b", "Mandalorian", "alien",
        "Burg left Devaron's temple cities for guild muscle work, selling horned intimidation and starship boarding skills to Ranzar Malk's broker operation.",
        "Burg joined Xi'an and Q9-0 on Bothan-5's prisoner extraction, clashing with Din Djarin when Ranzar's betrayal turned the crew against itself.",
        "Devaronian horns as close-combat weapons, boarding harpoons, heavy blaster rifles, and zero-g raid tactics.",
        events=_ev("Leaves Devaron for hunter muscle contracts", "Joins Ranzar Malk's Bothan-5 crew", "Prison ship boarding operation", "Confrontation with Din Djarin"),
        affiliations=_aff("Ranzar Malk's crew", "Devaronian expatriates", "Bounty Hunters' Guild", "Bothan-5 station"),
        timeline=_tl(("Devaron", "Temple city origins"), ("Guild", "Muscle contracts"), ("Bothan-5", "Ranzar crew"), ("Prison Raid", "Djarin confrontation")),
    ),
    qb(
        "Bendix Fust", "Rodian Bounty Hunter", "Rodia",
        "Rodian hunter active on Manaan during the Jedi Civil War, when KOTOR-era guild boards still answered to Hutt and Sith paymasters.",
        "#65a30d", "Knights of the Old Republic", "rodian",
        "Bendix Fust ran Rodian clan contracts on Manaan's kolto lanes, hunting debtors and Sith deserters when the Old Republic's authority thinned around underwater cities.",
        "Fust clashed with Republic travelers and Sith patrols alike on Manaan, treating kolto convoys as hunting grounds for posted pucks and clan honor.",
        "Rodian tracking snares, underwater ambush tactics, clan-marked armor, and Manaan dockside informant webs.",
        ancient="Manaan's neutral kolto trade produced hunter-enforcers for centuries—Bendix Fust is the best-documented Rodian operator of the Jedi Civil War period.",
        events=_ev("Clan hunter training on Rodia", "Posts contracts on Manaan's kolto lanes", "Hunts Sith deserters and debtors", "KOTOR-era Nar Shaddaa board listings"),
        affiliations=_aff("Rodia hunter clans", "Manaan dock syndicates", "Old Republic guild charters", "Hutt Cartel (contracted)"),
        timeline=_tl(("Rodia", "Clan initiation"), ("Manaan", "Kolto lane contracts"), ("Jedi Civil War", "Sith deserter hunts"), ("Legacy", "KOTOR hunter archive")),
    ),
    qb(
        "Komad Fortuna", "Twi'lek Bounty Hunter", "Ryloth",
        "Twi'lek hunter whose KOTOR-era contracts on Tatooine and Nar Shaddaa made him a benchmark for Rim independence before the Mandalorian wars.",
        "#0891b2", "Knights of the Old Republic", "twilek",
        "Komad Fortuna escaped Ryloth's exploitation markets by selling lekku-wrapped anonymity and precise blaster work to Exchange brokers on Nar Shaddaa.",
        "Fortuna hunted deserters, smugglers, and Sith agents across Tatooine's Dune Sea and Nar Shaddaa's vertical slums during the Jedi Civil War.",
        "Dual blaster proficiency, Twi'lek agility, Exchange safe-house networks, and Tatooine sandstorm pursuit tactics.",
        events=_ev("Escapes Ryloth exploitation via hunter trade", "Exchange contracts on Nar Shaddaa", "Tatooine Dune Sea postings", "KOTOR-era guild benchmark"),
        affiliations=_aff("Nar Shaddaa Exchange", "Ryloth expatriates", "Bounty Hunters' Guild", "Tatooine moisture-farmer debt networks"),
        timeline=_tl(("Ryloth", "Exploitation and escape"), ("Nar Shaddaa", "Exchange contracts"), ("Tatooine", "Dune Sea hunts"), ("Legacy", "KOTOR Rim hunter icon")),
    ),
    qb(
        "Jicoln Cadera", "Mandalorian Bounty Hunter", "Mandalore",
        "Mandalorian exile and Great Hunt competitor whose clan feud with Tarro Blood defined SWTOR-era hunter politics on Dromund Kaas.",
        "#0284c7", "Star Wars: The Old Republic", "mando",
        "Jicoln Cadera was cast out of Mandalorian orthodoxy for challenging clan leadership, then rebuilt status through the Great Hunt's lethal tournament brackets.",
        "Cadera's feud with Tarro Blood spilled across Dromund Kaas hunting grounds, turning SWTOR's Great Hunt into a proxy war for Mandalorian honor codes.",
        "Mandalorian vambrace weaponry, ambush tactics, clan feud choreography, and Great Hunt tournament survival strategies.",
        events=_ev("Exiled from Mandalorian clan hierarchy", "Enters the Great Hunt tournament", "Feud with Tarro Blood escalates", "SWTOR-era Dromund Kaas contracts"),
        affiliations=_aff("Mandalorian exile networks", "Great Hunt tournament", "Dromund Kaas hunter lodges", "Bounty Hunters' Guild"),
        timeline=_tl(("Mandalore", "Clan exile"), ("Great Hunt", "Tournament entry"), ("Blood Feud", "Tarro Blood rivalry"), ("SWTOR Era", "Dromund Kaas legend")),
    ),
    qb(
        "Hedarr", "Trandoshan Great Hunt Hunter", "Trandosha",
        "Trandoshan competitor in the SWTOR Great Hunt who brought scorekeeper trophy rituals to the galaxy's most public hunter tournament.",
        "#65a30d", "Star Wars: The Old Republic", "trandoshan",
        "Hedarr entered the Great Hunt to prove Trandoshan scorekeeper traditions could dominate Dromund Kaas tournament brackets against Mandalorian and cyborg rivals.",
        "Hedarr eliminated multiple Hunt competitors using trophy-capture methods that horrified Republic spectators but impressed guild elders.",
        "Scorekeeper nets, trophy manacles, Trandoshan pack psychology, and Great Hunt arena adaptation.",
        events=_ev("Scorekeeper lodge champion on Trandosha", "Great Hunt tournament entry", "Eliminates multiple Hunt rivals", "Public Trandoshan hunter representation"),
        affiliations=_aff("Trandoshan scorekeepers", "Great Hunt tournament", "Bounty Hunters' Guild", "Dromund Kaas lodges"),
        timeline=_tl(("Trandosha", "Lodge champion"), ("Great Hunt", "Tournament entry"), ("Arena", "Rival eliminations"), ("Legacy", "SWTOR Trandoshan icon")),
    ),
    qb(
        "Veeboo Lunak", "Rodian Great Hunt Hunter", "Rodia",
        "Rodian tournament hunter whose Great Hunt career showcased Rodian marksmanship in SWTOR's deadliest public competition.",
        "#65a30d", "Star Wars: The Old Republic", "rodian",
        "Veeboo Lunak translated Rodian clan sniper training into Great Hunt bracket survival, posting kills that Republic media could not censor fast enough.",
        "Lunak hunted competitors and sanctioned targets across Dromund Kaas under Great Hunt rules, where capture and kill both advanced tournament standing.",
        "Rodian sniper rifles, clan targeting rituals, tournament point optimization, and Dromund Kaas urban overwatch.",
        events=_ev("Rodian clan sniper training", "Great Hunt bracket entry", "High-profile tournament eliminations", "SWTOR media-notorious hunter"),
        affiliations=_aff("Rodia hunter clans", "Great Hunt tournament", "Bounty Hunters' Guild", "Dromund Kaas broker boards"),
        timeline=_tl(("Rodia", "Sniper training"), ("Great Hunt", "Bracket entry"), ("Tournament", "Public eliminations"), ("Legacy", "Rodian SWTOR legend")),
    ),
    qb(
        "Gold Fury", "Zabrak Great Hunt Hunter", "Iridonia",
        "Zabrak brawler-hunter who fought through SWTOR Great Hunt arenas with horned close-combat dominance.",
        "#d97706", "Star Wars: The Old Republic", "zabrak",
        "Gold Fury earned the name in underground Iridonia fight pits before translating horned brawling into Great Hunt tournament carnage on Dromund Kaas.",
        "Gold Fury closed distance on sniper-specialist rivals, turning Hunt brackets into melee slaughter that guild bookmakers exploited.",
        "Zabrak horn rushes, arena grappling, pain tolerance training, and tournament crowd manipulation.",
        events=_ev("Underground champion on Iridonia", "Great Hunt tournament entry", "Melee dominance in Hunt arenas", "Bookmaker-famous brawler-hunter"),
        affiliations=_aff("Iridonia fight pits", "Great Hunt tournament", "Bounty Hunters' Guild", "Dromund Kaas arena circuits"),
        timeline=_tl(("Iridonia", "Fight pit champion"), ("Great Hunt", "Tournament entry"), ("Arena", "Melee slaughter"), ("Legacy", "Zabrak brawler-hunter")),
    ),
    qb(
        "Murmur", "Anomid Great Hunt Hunter", "Yablari",
        "Vocal-modulator Anomid hunter who communicated through encrypted frequency bursts during SWTOR Great Hunt operations.",
        "#64748b", "Star Wars: The Old Republic", "alien",
        "Murmur's Anomid biology required vocal modulators for galactic trade, which Murmur weaponized as encrypted hunter coordination during Great Hunt team eliminations.",
        "Murmur coordinated Hunt ambushes using frequency-coded commands competitors could not intercept, elevating Anomid hunters in tournament archives.",
        "Vocal-modulator encryption, ambush synchronization, Anomid tech integration, and Great Hunt team tactics.",
        events=_ev("Anomid vocal-modulator adaptation", "Great Hunt tournament entry", "Frequency-coded ambush victories", "Anomid hunter representation in SWTOR"),
        affiliations=_aff("Anomid expatriates", "Great Hunt tournament", "Bounty Hunters' Guild", "Yablari tech brokers"),
        timeline=_tl(("Yablari", "Modulator adaptation"), ("Great Hunt", "Tournament entry"), ("Ambush Era", "Frequency-coded wins"), ("Legacy", "Anomid hunter archive")),
    ),
    qb(
        "Thelonia Redrish", "Human Great Hunt Hunter", "Core Worlds",
        "Core Worlds aristocrat turned hunter who used SWTOR's Great Hunt to launder family scandal into public lethal celebrity.",
        "#0284c7", "Star Wars: The Old Republic", "human",
        "Thelonia Redrish abandoned Core privilege for Hunt brackets, treating Dromund Kaas eliminations as performance art broadcast to Republic social channels.",
        "Redrish hunted sanctioned targets and rival competitors with equal flair, turning Great Hunt standings into tabloid currency.",
        "Precision blaster work, public persona management, Core Worlds funding, and tournament media manipulation.",
        events=_ev("Core Worlds aristocratic scandal", "Great Hunt tournament entry", "Tabloid-famous eliminations", "Republic social channel notoriety"),
        affiliations=_aff("Core Worlds aristocracy (renounced)", "Great Hunt tournament", "Bounty Hunters' Guild", "Republic media circuits"),
        timeline=_tl(("Core Worlds", "Aristocratic origins"), ("Scandal", "Public disgrace"), ("Great Hunt", "Tournament celebrity"), ("Legacy", "Socialite-hunter archetype")),
    ),
    qb(
        "Gorm the Dissolver", "Assassin Droid Bounty Hunter", "Unknown",
        "Acid-equipped hunter-killer whose dissolution methods made guild capture-alive standards irrelevant across multiple eras.",
        "#64748b", "Comics · Legends-adjacent", "droid",
        "Gorm the Dissolver operated as a droid assassin whose acid dispensers reduced targets and evidence simultaneously—guild brokers priced Gorm for jobs requiring total erasure.",
        "Gorm hunted Imperial defectors, Hutt rivals, and Jedi sympathizers across Nar Shaddaa and Coruscant underworld layers across decades of contract work.",
        "Acid jet appendages, droid chassis reinforcement, evidence dissolution protocols, and silent facility infiltration.",
        events=_ev("Activated as hunter-killer droid", "Acid-dissolution contracts on Nar Shaddaa", "Imperial defector elimination campaigns", "Multi-era guild notoriety"),
        affiliations=_aff("Assassin droid black markets", "Bounty Hunters' Guild", "Hutt Cartel (contracted)", "Imperial Security Bureau (denied)"),
        timeline=_tl(("Activation", "Hunter-killer deployment"), ("Nar Shaddaa", "Dissolution contracts"), ("Imperial Era", "Defector hunts"), ("Legacy", "Acid-hunter legend")),
    ),
    qb(
        "Noval Garaint", "Mandalorian Bounty Hunter", "Mandalore",
        "Mandalorian hunter and author of pre-Imperial guild tactical manuals still cited in hunter training academies.",
        "#0284c7", "Legends · Guild lore", "mando",
        "Noval Garaint codified Mandalorian pursuit doctrine into hunter manuals that survived the Clone Wars, influencing Boba Fett-era guild academies on Nevarro.",
        "Garaint hunted Separatist agents and Rim pirates before publishing trap-setting guides that Imperial ISB later confiscated as insurgent literature.",
        "Mandalorian jetpack interception, manual-authored ambush geometry, beskar durability tactics, and guild curriculum design.",
        impact="Garaint's manuals appear in redacted form in Nevarro guild training—hunter historians treat them as foundational Rim enforcement theory.",
        events=_ev("Active Mandalorian hunter during late Republic", "Publishes guild tactical manuals", "Hunts Separatist agents on the Rim", "Manuals survive into Imperial era"),
        affiliations=_aff("Mandalorian warrior culture", "Bounty Hunters' Guild", "Nevarro training academies (legacy)", "Old Republic contractor rolls"),
        timeline=_tl(("Late Republic", "Active hunting career"), ("Manuals", "Tactical doctrine published"), ("Imperial Era", "Confiscated literature"), ("Legacy", "Guild academy citations")),
    ),
    qb(
        "D'harhan", "Cyborg Bounty Hunter", "Unknown",
        "Near-mythical cyborg hunter with a face-mounted laser cannon whose Imperial Era contracts were priced above entire clone squads.",
        "#64748b", "Tales of the Bounty Hunters · Expanded lore", "cyborg",
        "D'harhan survived catastrophic wounds by accepting full facial cybernetic replacement, turning the hunter into a walking cannon platform feared from Ord Mantell to the Outer Rim.",
        "D'harhan served on high-value Imperial extractions where Vader's roster needed overwhelming firepower rather than capture finesse.",
        "Facial laser cannon, cybernetic targeting array, heavy armor plating, and no-negotiation elimination policy.",
        events=_ev("Catastrophic injury leads to full cyborg rebuild", "Imperial high-value elimination contracts", "Priced above clone squad deployments", "Ord Mantell hunter cantina legend"),
        affiliations=_aff("Bounty Hunters' Guild", "Galactic Empire (contracted)", "Ord Mantell broker networks", "Cyborg modification clinics"),
        timeline=_tl(("Injury", "Cyborg reconstruction"), ("Imperial Era", "Elite contracts"), ("Executor Era", "High-value eliminations"), ("Legacy", "Cyborg hunter myth")),
    ),
    qb(
        "T'ongor", "Twi'lek Bounty Hunter", "Ryloth",
        "Twi'lek hunter and father of T'onga whose death on a Hutt contract reshaped the family into one of the galaxy's most feared hunter lineages.",
        "#0891b2", "War of the Bounty Hunters · Comics", "twilek",
        "T'ongor ran Twi'lek clan contracts on Ryloth before Hutt postings took him to syndicate wars where betrayal killed him and launched T'onga's vengeance career.",
        "T'ongor's final Hutt contract ended in ambush, leaving T'onga and T'lar to inherit his ship, debts, and reputation across the War of the Bounty Hunters.",
        "Twi'lek agility, Hutt contract negotiation, family crew operations, and Ryloth clan honor codes.",
        events=_ev("Builds Twi'lek hunter reputation on Ryloth", "Accepts lucrative Hutt syndicate contract", "Killed in contract ambush", "Legacy drives T'onga and T'lar careers"),
        affiliations=_aff("T'onga family hunter lineage", "Hutt Cartel (contracted)", "Ryloth clan networks", "Bounty Hunters' Guild"),
        timeline=_tl(("Ryloth", "Clan hunter origins"), ("Hutt Contracts", "Syndicate postings"), ("Ambush", "Death on final contract"), ("Legacy", "T'onga vengeance arc")),
    ),
    qb(
        "T'lar", "Twi'lek Bounty Hunter", "Ryloth",
        "Sister of T'onga who continued the family hunter business after T'ongor's death during the War of the Bounty Hunters.",
        "#0891b2", "War of the Bounty Hunters · Comics", "twilek",
        "T'lar inherited T'ongor's debts and ship alongside T'onga, keeping the family hunter brand alive when Crimson Dawn and Pyke syndicates rewrote guild law.",
        "T'lar fought alongside T'onga during the Han Solo carbonite puck crisis, targeting syndicate brokers who exploited T'ongor's death.",
        "Sibling crew coordination, Twi'lek pursuit tactics, family debt honor, and syndicate war navigation.",
        events=_ev("Inherits T'ongor hunter legacy", "Partners with T'onga on family contracts", "War of the Bounty Hunters syndicate fights", "Maintains family hunter brand"),
        affiliations=_aff("T'onga family hunter lineage", "Bounty Hunters' Guild", "Crimson Dawn (opposed)", "Ryloth expatriates"),
        timeline=_tl(("Ryloth", "Family origins"), ("T'ongor Death", "Legacy inheritance"), ("Syndicate War", "T'onga partnership"), ("Legacy", "Sister-hunter lineage")),
    ),
    qb(
        "Riley", "Human Bounty Hunter", "Unknown",
        "Beilert Valance's partner whose death on a Core job pushed the cyborg hunter toward vengeance against Imperial-backed clients.",
        "#64748b", "Target Vader · Comics", "human",
        "Riley partnered with Beilert Valance on Core Worlds extractions until an Imperial-backed ambush killed Riley and hardened Valance into cyborg vengeance.",
        "Riley and Valance hunted Rebel sympathizers and deserters until Riley's death proved even elite partners could not survive ISB trap architecture.",
        "Dual-hunter coordination, Core Worlds infiltration, fast extraction pods, and Valance partnership tactics.",
        events=_ev("Partners with Beilert Valance", "Core Worlds extraction contracts", "Killed in Imperial-backed ambush", "Death catalyzes Valance cyborg path"),
        affiliations=_aff("Beilert Valance partnership", "Bounty Hunters' Guild", "Core Worlds broker networks", "Galactic Empire (targets)"),
        timeline=_tl(("Partnership", "Valance crew formation"), ("Core Jobs", "Extraction contracts"), ("Ambush", "Riley killed"), ("Legacy", "Valance vengeance catalyst")),
    ),
    qb(
        "Vukorah", "Devaronian Bounty Hunter", "Devaron",
        "Crimson Dawn enforcer who hunted rival syndicate brokers during the War of the Bounty Hunters.",
        "#991b1b", "War of the Bounty Hunters · Comics", "alien",
        "Vukorah sold horned intimidation to Crimson Dawn during Qi'ra's syndicate war, hunting guild brokers who challenged Dawn's puck monopoly.",
        "Vukorah targeted Doctor Aphra associates and independent hunters holding Han Solo carbonite stakes during the syndicate-wide bounty crisis.",
        "Devaronian horn combat, Crimson Dawn strike teams, syndicate assassination, and broker intimidation.",
        events=_ev("Recruited as Crimson Dawn enforcer", "War of the Bounty Hunters operations", "Targets rival syndicate brokers", "Hunts carbonite puck holders"),
        affiliations=_aff("Crimson Dawn", "Devaronian enforcer networks", "Bounty Hunters' Guild (opposed)", "Qi'ra syndicate command"),
        timeline=_tl(("Devaron", "Enforcer origins"), ("Crimson Dawn", "Recruitment"), ("Syndicate War", "Broker hunts"), ("Legacy", "Dawn enforcer icon")),
    ),
    qb(
        "Beebox", "Trandoshan Bounty Hunter", "Trandosha",
        "Trandoshan hunter who competed for Han Solo's carbonite puck during the War of the Bounty Hunters.",
        "#65a30d", "War of the Bounty Hunters · Comics", "trandoshan",
        "Beebox joined the galaxy-wide scramble for Han Solo's carbonite body when Crimson Dawn posted the ultimate puck, bringing Trandoshan scorekeeper brutality to Core broker battles.",
        "Beebox fought guild rivals and syndicate enforcers on Nar Shaddaa and Coruscant underworld stations for carbonite custody rights.",
        "Trandoshan strength, carbonite transport interception, scorekeeper trophy ambition, and syndicate war raids.",
        events=_ev("Trandoshan lodge hunter certification", "Joins Han Solo carbonite puck scramble", "Fights syndicate rivals for custody", "War of the Bounty Hunters combatant"),
        affiliations=_aff("Trandoshan scorekeepers", "Bounty Hunters' Guild", "Crimson Dawn (opposed)", "Carbonite puck hunters"),
        timeline=_tl(("Trandosha", "Lodge certification"), ("Carbonite Puck", "Han Solo scramble"), ("Syndicate War", "Rival fights"), ("Legacy", "Trandoshan puck hunter")),
    ),
    qb(
        "Snoova", "Shistavanen Bounty Hunter", "Uvena Prime",
        "Wolf-like Shistavanen tracker hired for Imperial-era extractions where scent tracking beat sensor arrays.",
        "#64748b", "Comics · Expanded lore", "alien",
        "Snoova leveraged Shistavanen olfactory tracking on frontier worlds where Imperial sensors failed and guild clients needed prey found across wasteland continents.",
        "Snoova hunted Rebel cells and deserter convoys for Imperial paymasters who valued tracking over public capture displays.",
        "Scent-trail pursuit, wilderness endurance, Shistavanen pack instincts, and silent takedown tactics.",
        events=_ev("Shistavanen tracking mastery on Uvena Prime", "Imperial wilderness extraction contracts", "Rebel cell pursuit campaigns", "Frontier tracker legend"),
        affiliations=_aff("Shistavanen tracker clans", "Galactic Empire (contracted)", "Bounty Hunters' Guild", "Frontier broker networks"),
        timeline=_tl(("Uvena Prime", "Tracker training"), ("Imperial Era", "Wilderness contracts"), ("Rebel Hunts", "Cell pursuit"), ("Legacy", "Scent-tracker icon")),
    ),
    qb(
        "Chanath Cha", "Human Bounty Hunter", "Unknown",
        "Elite hunter associated with Solo-era underworld operations and Emperor Palpatine's secret vault pursuits.",
        "#0284c7", "Solo · Crimson Reign · Comics", "human",
        "Chanath Cha operated in the Emperor's hidden vault chase, combining aristocratic hunter bearing with classified Imperial extraction skills.",
        "Cha pursued vault artifacts and underworld brokers when Crimson Dawn and Imperial remnant factions collided after Endor.",
        "Precision sniper work, vault infiltration, underworld identity networks, and classified Imperial training.",
        events=_ev("Imperial-classified hunter training", "Emperor vault artifact pursuits", "Crimson Reign underworld operations", "Solo-era syndicate extractions"),
        affiliations=_aff("Imperial remnant clients", "Crimson Dawn (complex)", "Bounty Hunters' Guild", "Vault artifact brokers"),
        timeline=_tl(("Training", "Imperial hunter classification"), ("Vault Era", "Artifact pursuits"), ("Crimson Reign", "Underworld wars"), ("Legacy", "Vault-hunter specialist")),
    ),
    qb(
        "IG-72", "Assassin Droid Bounty Hunter", "Holowan Labs",
        "Independent IG-series assassin droid that competed with IG-88 for guild prestige during the Imperial Era.",
        "#64748b", "Empire Strikes Back era · Expanded lore", "droid",
        "IG-72 escaped Holowan batch programming to run independent hunter contracts, refusing IG-88's collective architecture while sharing the same lethal chassis design.",
        "IG-72 posted pucks on smuggler convoys and Rebel couriers along the Perlemian Trade Route when Imperial brokers needed droid discretion.",
        "IG-series blaster integration, independent tactical AI, starship interception, and Holowan chassis durability.",
        events=_ev("Escapes Holowan batch control", "Independent Imperial Era contracts", "Rivalry with IG-88 collective", "Perlemian Trade Route postings"),
        affiliations=_aff("Holowan Labs (origin)", "Bounty Hunters' Guild", "Galactic Empire (contracted)", "IG-series droid black market"),
        timeline=_tl(("Holowan", "Batch activation"), ("Independence", "Leaves collective model"), ("Imperial Era", "Solo contracts"), ("Legacy", "IG-series rival")),
    ),
    qb(
        "Deathstick", "Twi'lek Assassin", "Ryloth",
        "Twi'lek assassin-hunter who operated on Nar Shaddaa during the Clone Wars, selling lethal precision to Exchange brokers.",
        "#991b1b", "Clone Wars · Comics", "twilek",
        "Deathstick earned her name on Nar Shaddaa by completing Exchange assassinations that guild hunters considered too politically exposed for open pucks.",
        "Deathstick eliminated Separatist financiers and corrupt Republic officials when standard bounty postings would trigger diplomatic incidents.",
        "Vibro-blade mastery, Twi'lek stealth, Exchange safe routes, and politically deniable assassination.",
        events=_ev("Nar Shaddaa Exchange assassin training", "Clone Wars politically deniable kills", "Separatist financier eliminations", "Republic corruption target removals"),
        affiliations=_aff("Nar Shaddaa Exchange", "Ryloth assassin circles", "Bounty Hunters' Guild (adjacent)", "Shadow broker networks"),
        timeline=_tl(("Ryloth", "Assassin training"), ("Nar Shaddaa", "Exchange work"), ("Clone Wars", "Deniable kills"), ("Legacy", "Assassin-hunter archetype")),
    ),
    qb(
        "Danzigorro Potts", "Human Bounty Hunter", "Corellia",
        "Corellian hunter whose flamboyant weapon collection and Rim contracts made him a guild showman during the Imperial Era.",
        "#0284c7", "Empire Strikes Back era · Expanded lore", "human",
        "Danzigorro Potts built a Corellian reputation on customized blaster arsenals and theatrical captures that impressed Hutt clients and humiliated targets.",
        "Potts hunted smuggler rivals and Rebel couriers along Corellian trade spurs, posting trophies in hunter cantinas as marketing.",
        "Custom blaster collection, theatrical capture displays, Corellian piloting, and cantina reputation engineering.",
        events=_ev("Corellian hunter showmanship rises", "Custom weapon arsenal fame", "Smuggler and Rebel courier hunts", "Cantina trophy marketing"),
        affiliations=_aff("Corellian hunter circuits", "Bounty Hunters' Guild", "Hutt Cartel (contracted)", "Smuggler rival networks"),
        timeline=_tl(("Corellia", "Showman origins"), ("Imperial Era", "Rim contracts"), ("Cantina Fame", "Trophy marketing"), ("Legacy", "Flamboyant hunter archetype")),
    ),
    qb(
        "Crockagor", "Gamorrean Bounty Hunter", "Gamorr",
        "Gamorrean enforcer-hunter who sold brute capture services to Hutt courts that valued intimidation over finesse.",
        "#65a30d", "Expanded lore · Hutt contracts", "alien",
        "Crockagor left Gamorr's clan wars for Hutt court muscle work, translating Gamorrean brutality into live-capture contracts for debtors and rival capos.",
        "Crockagor guarded Hutt palaces by day and hunted escapees by night, making Gamorrean hunters visible in kajidic enforcement.",
        "Gamorrean vibro-axe work, palace intimidation, debtor capture, and Hutt court standby enforcement.",
        events=_ev("Gamorr clan war veteran", "Hutt court enforcer recruitment", "Debtor capture contracts", "Palace and pursuit dual role"),
        affiliations=_aff("Gamorr clans", "Hutt Cartel courts", "Bounty Hunters' Guild", "Tatooine kajidic enforcement"),
        timeline=_tl(("Gamorr", "Clan wars"), ("Hutt Courts", "Enforcer recruitment"), ("Capture Work", "Debtor hunts"), ("Legacy", "Gamorrean hunter icon")),
    ),
    qb(
        "Breacher", "Human Bounty Hunter", "Unknown",
        "Ranzar Malk crew specialist in breaching sealed prison transports during New Republic-era extractions.",
        "#64748b", "Mandalorian", "helmet",
        "Breacher joined Ranzar's Bothan-5 operation as hull-cutting specialist for New Republic prisoner ships where stealth failed and speed mattered.",
        "Breacher cut into prison transport cells during the mission that hired Din Djarin, Q9-0, and Xi'an before Ranzar's betrayal.",
        "Thermal hull charges, zero-g breaching, prison transport layout expertise, and crew raid coordination.",
        events=_ev("Prison transport breaching specialist", "Joins Ranzar Malk crew", "Bothan-5 extraction operation", "New Republic prisoner ship raid"),
        affiliations=_aff("Ranzar Malk's crew", "Bothan-5 station", "Bounty Hunters' Guild", "Prison break specialists"),
        timeline=_tl(("Specialist", "Breaching expertise"), ("Ranzar Crew", "Bothan-5 join"), ("Prison Raid", "Transport breach"), ("Legacy", "Breacher archetype")),
    ),
    qb(
        "Traxus", "Human Bounty Hunter", "Corellia",
        "Corellian hunter whose Imperial Era contracts on the Perlemian Trade Route made him a benchmark for smuggler-capture pricing.",
        "#0284c7", "Legends · Expanded lore", "human",
        "Traxus built Corellian hunter credentials capturing smuggler convoys along the Perlemian when Imperial patrols were stretched thin across Mid Rim sectors.",
        "Traxus hunted Rebel couriers and Hutt defectors with equal efficiency, posting prices guild brokers used as market indexes for capture-alive clauses.",
        "Corellian pursuit piloting, convoy interception, capture-alive restraint systems, and Perlemian route intelligence.",
        events=_ev("Corellian hunter market rise", "Perlemian smuggler convoy captures", "Rebel courier contract specialization", "Guild pricing benchmark status"),
        affiliations=_aff("Corellian hunter circuits", "Bounty Hunters' Guild", "Galactic Empire (contracted)", "Perlemian broker networks"),
        timeline=_tl(("Corellia", "Hunter origins"), ("Perlemian", "Convoy captures"), ("Imperial Era", "Market benchmark"), ("Legacy", "Pricing index hunter")),
    ),
    qb(
        "Nix Card", "Bounty Hunter Broker", "Unknown",
        "Information broker who arranged high-value hunter contracts during the Clone Wars for clients requiring total operational secrecy.",
        "#64748b", "Clone Wars · Comics", "human",
        "Nix Card operated as broker between anonymous Separatist and Republic clients, posting hunter contracts without guild paperwork that would trigger ISB review.",
        "Card arranged Cad Bane-adjacent operations and independent hunter teams for holocron-class targets when public pucks were politically impossible.",
        "Anonymous contract routing, encrypted puck delivery, hunter team assembly, and Clone Wars deniable operations.",
        events=_ev("Rise as anonymous hunter broker", "Clone Wars deniable contract routing", "High-value target team assembly", "Encrypted puck network expansion"),
        affiliations=_aff("Shadow broker networks", "Bounty Hunters' Guild (unofficial)", "Separatist clients (deniable)", "Republic black budgets (deniable)"),
        timeline=_tl(("Broker Rise", "Anonymous contract routing"), ("Clone Wars", "Deniable operations"), ("High Value", "Holocron-class targets"), ("Legacy", "Shadow broker archetype")),
    ),
    qb(
        "Gha Nachkt", "Trandoshan Bounty Hunter", "Trandosha",
        "Trandoshan scavenger-hunter who sold captured droids on Ruusan black markets during the Clone Wars.",
        "#65a30d", "Clone Wars", "trandoshan",
        "Gha Nachkt combined scavenging and bounty work, capturing astromech droids and selling them to Separatist buyers when Republic salvage law failed to reach Rim junkyards.",
        "Nachkt hunted Republic droids during Clone Wars salvage operations, treating droid capture as profitable puck work on Ruusan and Mid Rim depots.",
        "Droid capture nets, salvage yard operations, Trandoshan boarding tactics, and black-market droid resale.",
        events=_ev("Ruusan salvage-hunter operations", "Droid capture and resale contracts", "Clone Wars astromech hunts", "Separatist buyer network service"),
        affiliations=_aff("Ruusan salvage markets", "Separatist buyers", "Trandoshan scavenger guilds", "Bounty Hunters' Guild"),
        timeline=_tl(("Trandosha", "Scavenger origins"), ("Ruusan", "Salvage operations"), ("Clone Wars", "Droid captures"), ("Legacy", "Scavenger-hunter icon")),
    ),
    qb(
        "Akku Seii", "Anzati Bounty Hunter", "Anzat",
        "Anzati hunter who taught assassination traditions that blurred bounty hunting and soul-drinking ritual across Old Republic eras.",
        "#991b1b", "Legends · Old Republic lore", "alien",
        "Akku Seii trained Anzati hunters to treat targets as sustenance and contract simultaneously, exporting the tradition to Nar Shaddaa guild markets.",
        "Seii's pupils hunted Jedi and Sith sympathizers during Old Republic collapse, where capture-alive clauses rarely survived Anzati feeding rituals.",
        "Anzati proboscis strike, stealth infiltration, soul-drinking ritual, and hunter-pupil lineage training.",
        events=_ev("Anzati hunter master on Anzat", "Trains Nar Shaddaa pupil assassins", "Old Republic collapse contracts", "Jedi and Sith sympathizer hunts"),
        affiliations=_aff("Anzati hunter tradition", "Nar Shaddaa training circles", "Bounty Hunters' Guild (adjacent)", "Old Republic shadow markets"),
        timeline=_tl(("Anzat", "Master hunter rise"), ("Training", "Pupil assassin line"), ("Old Republic", "Collapse-era contracts"), ("Legacy", "Anzati hunter myth")),
    ),
    qb(
        "Khamus", "Pyke Syndicate Hunter", "Oba Diah",
        "Pyke syndicate enforcer who operated as bounty-adjacent muscle during Clone Wars spice-route enforcement.",
        "#0891b2", "Bad Batch · Clone Wars era", "alien",
        "Khamus enforced Pyke spice debts on Rim worlds, using hunter-style pursuit when smugglers defaulted on syndicate contracts.",
        "Khamus tracked Bad Batch-adjacent deserters and spice convoy raiders along Oba Diah supply lines during late Clone Wars consolidation.",
        "Pyke syndicate intimidation, spice-route pursuit, debt enforcement, and convoy raider elimination.",
        events=_ev("Pyke syndicate enforcer training", "Spice-route debt enforcement", "Clone Wars Rim pursuit operations", "Bad Batch era syndicate muscle"),
        affiliations=_aff("Pyke Syndicate", "Oba Diah spice brokers", "Bounty Hunters' Guild (adjacent)", "Rim smuggler debt networks"),
        timeline=_tl(("Oba Diah", "Syndicate training"), ("Spice Routes", "Debt enforcement"), ("Clone Wars", "Rim pursuits"), ("Legacy", "Pyke enforcer-hunter")),
    ),
    qb(
        "Fenn Rau", "Mandalorian Protector Hunter", "Concord Dawn",
        "Mandalorian Protector who enforced Concord Dawn neutrality through hunter-precision strikes against pirates and Separatist incursions.",
        "#0284c7", "Clone Wars · Rebels", "mando",
        "Fenn Rau commanded Mandalorian Protectors on Concord Dawn, posting hunter-style interceptions against anyone violating system neutrality during the Clone Wars.",
        "Rau later cooperated with Rebels after Imperial compromise, applying Protector hunter doctrine to Phoenix Squadron escort operations.",
        "Protector starfighter interception, Concord Dawn neutrality enforcement, Mandalorian honor codes, and precision strike planning.",
        events=_ev("Commands Mandalorian Protectors on Concord Dawn", "Enforces system neutrality via interceptions", "Imperial compromise and Protector scattering", "Rebels era Phoenix Squadron cooperation"),
        affiliations=_aff("Mandalorian Protectors", "Concord Dawn", "Galactic Republic (contracted)", "Rebel Alliance (later)"),
        timeline=_tl(("Concord Dawn", "Protector command"), ("Clone Wars", "Neutrality enforcement"), ("Imperial Era", "Protector scattering"), ("Rebels", "Phoenix cooperation")),
    ),
    qb(
        "Lyn", "Human Bounty Hunter", "Unknown",
        "Imperial-era hunter who tracked Force-sensitive targets during the Great Jedi Purge's long aftermath.",
        "#64748b", "Rebels · Expanded media", "human",
        "Lyn specialized in Imperial postings for undocumented Force sensitives, treating Purge survivors as high-value pucks when Inquisitors wanted deniability.",
        "Lyn pursued Rebel-adjacent targets on Rim worlds where ISB needed hunter contractors instead of open Inquisitor deployment.",
        "Force-sensitive tracking informants, Imperial deniability contracts, Purge survivor pursuit, and Rim world infiltration.",
        events=_ev("Imperial Force-sensitive hunter specialization", "Great Purge aftermath contracts", "Rebels era Rim pursuits", "Inquisitor-adjacent deniable jobs"),
        affiliations=_aff("Galactic Empire (contracted)", "Imperial Security Bureau", "Bounty Hunters' Guild", "Inquisitorius (adjacent)"),
        timeline=_tl(("Purges", "Specialization begins"), ("Imperial Era", "Force-sensitive pucks"), ("Rebels Era", "Rim pursuits"), ("Legacy", "Purge-hunter archetype")),
    ),
    qb(
        "Skreek", "Trandoshan Bounty Hunter", "Trandosha",
        "Trandoshan hunter who contested Bossk's scorekeeper tallies during Imperial Era lodge disputes.",
        "#65a30d", "Expanded lore", "trandoshan",
        "Skreek challenged Bossk's Cradossk-backed authority in Trandoshan lodges, turning scorekeeper disputes into public hunt duels on Wookiee contract worlds.",
        "Skreek and Bossk competed for the same Kashyyyk slave-route pucks, escalating Trandoshan hunter feud into Imperial broker attention.",
        "Scorekeeper duel tradition, Wookiee hunt rivalry, lodge political combat, and Trandoshan trophy competition.",
        events=_ev("Challenges Bossk lodge authority", "Competes for Kashyyyk route pucks", "Public Trandoshan hunt duels", "Imperial broker attention from feud"),
        affiliations=_aff("Trandoshan scorekeepers", "Bossk rival lodges", "Bounty Hunters' Guild", "Kashyyyk hunt routes"),
        timeline=_tl(("Trandosha", "Rival lodge rise"), ("Feud", "Bossk competition"), ("Kashyyyk Routes", "Puck disputes"), ("Legacy", "Lodge rivalry icon")),
    ),
    qb(
        "Rook Kast", "Mandalorian Bounty Hunter", "Mandalore",
        "Mandalorian super commando who hunted Jedi and Republic targets under Darth Maul's Shadow Collective.",
        "#991b1b", "Clone Wars · Comics", "mando",
        "Rook Kast led Mandalorian hunter squads for Maul's Shadow Collective, posting pucks on Jedi and Republic officials during Mandalore's civil collapse.",
        "Kast coordinated super commando pursuit teams across Sundari and Dathomir when Maul needed hunter precision instead of army occupation.",
        "Super commando jetpack assault, Maul's Shadow Collective authority, Mandalore civil war pursuit, and Jedi target extraction.",
        events=_ev("Shadow Collective hunter commander", "Mandalore civil war pursuits", "Jedi target extraction operations", "Maul-era super commando raids"),
        affiliations=_aff("Shadow Collective", "Mandalorian super commandos", "Darth Maul's hunter squads", "Mandalore civil war factions"),
        timeline=_tl(("Mandalore", "Super commando rise"), ("Shadow Collective", "Maul recruitment"), ("Civil War", "Jedi pursuits"), ("Legacy", "Mandalorian hunter-commander")),
    ),
    qb(
        "Seripas", "Armored Bounty Hunter", "Unknown",
        "Small hunter who wore powered armor to intimidate targets—a partner in Sugi's Clone Wars mercenary crew on Felucia.",
        "#65a30d", "Clone Wars", "helmet",
        "Seripas compensated for small stature with oversized powered armor, fighting alongside Sugi and Embo when Hondo Ohnaka threatened Felucia nysillin farmers.",
        "Seripas held the line against Ohnaka's pirates while Sugi negotiated hunter-mercenary contracts protecting Felucia villages.",
        "Powered armor intimidation, Felucia village defense, Sugi crew coordination, and pirate siege survival.",
        events=_ev("Joins Sugi mercenary crew", "Felucia nysillin farmer protection", "Fights Hondo Ohnaka pirates", "Powered armor hunter intimidation"),
        affiliations=_aff("Sugi's mercenary crew", "Felucia farmer contracts", "Embo partnership circle", "Bounty Hunters' Guild"),
        timeline=_tl(("Armor", "Powered suit adoption"), ("Sugi Crew", "Mercenary join"), ("Felucia", "Farmer protection"), ("Pirates", "Ohnaka siege")),
    ),
    qb(
        "Dane Tizzin", "Human Bounty Hunter", "Naboo",
        "Naboo-born hunter who specialized in pirate-king eliminations along the Mid Rim during the Imperial Era.",
        "#0284c7", "Expanded lore", "human",
        "Dane Tizzin left Naboo's peaceful reputation behind to hunt pirate kings whose fleets threatened Mid Rim shipping when Imperial patrols were absent.",
        "Tizzin dismantled pirate bases through infiltration and capture bounties priced higher than Navy deployments for local governors.",
        "Pirate king infiltration, Mid Rim naval intelligence, capture-alive pirate contracts, and Naboo diplomatic cover stories.",
        events=_ev("Leaves Naboo for hunter career", "Mid Rim pirate-king specialization", "Dismantles multiple pirate bases", "Governor-priced capture contracts"),
        affiliations=_aff("Mid Rim governors (contracted)", "Bounty Hunters' Guild", "Naboo expatriates", "Anti-piracy broker networks"),
        timeline=_tl(("Naboo", "Origins"), ("Mid Rim", "Pirate specialization"), ("Base Raids", "King eliminations"), ("Legacy", "Pirate-hunter specialist")),
    ),
    qb(
        "Kintan Strider", "Nikto Bounty Hunter", "Kintan",
        "Nikto hunter guild enforcer from Kintan who served Hutt masters across Tatooine and Nar Shaddaa.",
        "#65a30d", "Return of the Jedi · Expanded lore", "alien",
        "Kintan Strider Nikto hunters formed a loose guild identity on Kintan, exporting Hutt loyalty and vibro-glaive work to Tatooine palace retinues.",
        "Strider Nikto hunters guarded Jabba's sail barge approaches and accepted pucks on Hutt debtors across the Dune Sea.",
        "Nikto vibro-glaives, Hutt loyalty oaths, desert pursuit endurance, and palace retinue standby.",
        events=_ev("Kintan Nikto hunter guild formation", "Hutt court recruitment", "Tatooine palace and Dune Sea contracts", "Jabba sail barge era service"),
        affiliations=_aff("Kintan Strider guild", "Jabba the Hutt's court", "Hutt Cartel", "Bounty Hunters' Guild"),
        timeline=_tl(("Kintan", "Guild formation"), ("Hutt Space", "Court recruitment"), ("Tatooine", "Palace service"), ("Legacy", "Nikto hunter guild")),
    ),
    qb(
        "Sardu Sallowe", "Ubese Bounty Hunter", "Uba IV",
        "Ubese hunter whose clan armor designs influenced the gear later associated with Boushh and other Ubese contractors.",
        "#991b1b", "Expanded lore", "helmet",
        "Sardu Sallowe pioneered Ubese isolation-armor hunter exports after Uba IV's Imperial quarantine, selling clan designs to offworld guild members.",
        "Sallowe hunted Black Sun lieutenants and Imperial quarantine breakers, establishing Ubese hunter gear as premium Rim protection.",
        "Ubese clan armor crafting, quarantine-smuggling routes, Black Sun contract work, and isolationist clan codes.",
        events=_ev("Uba IV quarantine hunter adaptation", "Ubese armor design exports", "Black Sun contract eliminations", "Influences Boushh-era gear standards"),
        affiliations=_aff("Ubese hunter clans", "Black Sun (targets)", "Bounty Hunters' Guild", "Uba IV smuggling networks"),
        timeline=_tl(("Uba IV", "Quarantine adaptation"), ("Armor", "Design exports"), ("Black Sun", "Contract work"), ("Legacy", "Ubese gear standards")),
    ),
    qb(
        "Villos Oran", "Chiss Bounty Hunter", "Csilla",
        "Chiss precision hunter who exported Ascendancy tracking doctrine to Republic-era guild markets under strict neutrality contracts.",
        "#0891b2", "Expanded lore · Thrawn adjacent", "chiss",
        "Villos Oran left Csilla on deniable Ascendancy contracts, selling Chiss precision pursuit to clients who needed hunter work without diplomatic attribution.",
        "Oran tracked smuggler convoys and Separatist agents along the Unknown Regions border when Republic brokers paid premium for Chiss accuracy.",
        "Chiss precision targeting, Unknown Regions navigation, deniable Ascendancy contracts, and cold-logic pursuit planning.",
        events=_ev("Csilla Ascendancy hunter training", "Deniable Republic border contracts", "Separatist agent pursuits", "Unknown Regions navigation expertise"),
        affiliations=_aff("Chiss Ascendancy (deniable)", "Bounty Hunters' Guild", "Republic border brokers", "Unknown Regions navigators"),
        timeline=_tl(("Csilla", "Ascendancy training"), ("Border", "Deniable contracts"), ("Pursuits", "Agent hunts"), ("Legacy", "Chiss hunter export")),
    ),
    qb(
        "Huntress", "Zabrak Bounty Hunter", "Iridonia",
        "Zabrak hunter who operated independently on Black Sun routes before Ketsu Onyo's Concord Dawn partnership fractured.",
        "#d97706", "Rebels · Expanded lore", "zabrak",
        "Huntress built Iridonia exile credentials on Black Sun enforcement before Ketsu Onyo partnership, then split when Syndicate loyalty conflicted with conscience.",
        "Huntress and Ketsu hunted together on Black Sun debt routes until Ketsu chose Rebels-adjacent morality over Syndicate pucks.",
        "Zabrak horn combat, Black Sun debt enforcement, partnership crew tactics, and Syndicate loyalty fractures.",
        events=_ev("Iridonia exile hunter career", "Black Sun debt route partnerships", "Ketsu Onyo crew operations", "Partnership fracture over morality"),
        affiliations=_aff("Black Sun (former)", "Ketsu Onyo (former partner)", "Iridonia expatriates", "Bounty Hunters' Guild"),
        timeline=_tl(("Iridonia", "Exile origins"), ("Black Sun", "Debt enforcement"), ("Partnership", "Ketsu crew era"), ("Split", "Morality fracture")),
    ),
    qb(
        "Tasu Leech", "Kanjiklub Enforcer", "Unknown",
        "Kanjiklub enforcer whose hunter-adjacent intimidation work overlapped with Han Solo's smuggling debts on Takodana.",
        "#991b1b", "Force Awakens · Expanded lore", "human",
        "Tasu Leech led Kanjiklub enforcers hunting Solo-era debt obligations, blurring syndicate enforcement and guild-style capture work.",
        "Leech confronted Han Solo on Eravana freighter yards when unpaid debts triggered enforcer pursuit styled like open market bounties.",
        "Kanjiklub intimidation squads, debt enforcement as bounty analog, freighter yard ambushes, and syndicate spectacle captures.",
        events=_ev("Rises in Kanjiklub enforcer ranks", "Solo debt enforcement operations", "Eravana freighter yard confrontation", "Syndicate-enforcer bounty analog work"),
        affiliations=_aff("Kanjiklub", "Debt enforcement networks", "Han Solo creditors", "Syndicate enforcer circuits"),
        timeline=_tl(("Kanjiklub", "Enforcer rise"), ("Debts", "Solo obligations"), ("Eravana", "Freighter confrontation"), ("Legacy", "Syndicate enforcer-hunter")),
    ),
    qb(
        "Mavra Zane", "Human Bounty Hunter", "Core Worlds",
        "Core Worlds hunter who operated during the Old Republic's final centuries, bridging Jedi-era law and Sith war mercenary markets.",
        "#0284c7", "Old Republic era · Expanded lore", "human",
        "Mavra Zane tracked Sith cultists and Mandalorian deserters when the Old Republic's judiciary outsourced Rim enforcement to guild charters.",
        "Zane's contracts on Tython-adjacent worlds prefigured later hunter markets that KOTOR-era boards would formalize on Nar Shaddaa.",
        "Core Worlds judicial charters, Sith cultist tracking, Mandalorian deserter capture, and early guild legal frameworks.",
        ancient="Zane's charter contracts appear in Jedi archives as early evidence of Republic hunter outsourcing before the Sith Empire's return.",
        events=_ev("Old Republic judicial hunter charters", "Sith cultist tracking contracts", "Mandalorian deserter captures", "Pre-KOTOR guild market formation"),
        affiliations=_aff("Old Republic judiciary", "Early Bounty Hunters' Guild", "Core Worlds charters", "Tython-adjacent security"),
        timeline=_tl(("Old Republic", "Charter hunter work"), ("Sith Cults", "Tracking contracts"), ("Deserters", "Mandalorian captures"), ("Legacy", "Pre-KOTOR guild evidence")),
    ),
    qb(
        "Anulus Gae", "Sith Pureblood Bounty Hunter", "Dromund Kaas",
        "Sith Empire-era hunter who competed in Great Hunt brackets under Imperial mandate to showcase Sith dominion over guild markets.",
        "#991b1b", "Star Wars: The Old Republic", "alien",
        "Anulus Gae entered the Great Hunt as Sith Empire propaganda—proving Imperial subjects could dominate hunter tournaments Republic media broadcast galaxy-wide.",
        "Gae eliminated Republic-aligned competitors during SWTOR's Hunt season, turning tournament brackets into Sith-Imperial prestige warfare.",
        "Sith Imperial mandate, Great Hunt tournament aggression, Pureblood hunter pride, and Dromund Kaas arena dominance.",
        events=_ev("Sith Empire hunter recruitment", "Great Hunt propaganda entry", "Republic-aligned competitor eliminations", "SWTOR Imperial hunter showcase"),
        affiliations=_aff("Sith Empire", "Great Hunt tournament", "Dromund Kaas hunter lodges", "Bounty Hunters' Guild"),
        timeline=_tl(("Dromund Kaas", "Imperial recruitment"), ("Great Hunt", "Propaganda entry"), ("Arena", "Republic rival eliminations"), ("Legacy", "Sith hunter showcase")),
    ),
]
