#!/usr/bin/env python3
"""Part 6 — final 16 bounty hunter entries."""


def register_rest6(_add, L):
    def d(**kw):
        return kw

    entries = [
        ("Jodo Kast", "Boba Fett Impersonator", "Unknown", "Mandalorian-armored fraud who exploited Fett's reputation until the real hunter ended the charade.", "#0284c7", "Legends · comics", "mando",
         d(origin_detail="Jodo Kast wore Mandalorian armor painted like Boba Fett's green scheme, exploiting the real Fett's reputation for contracts until Boba personally ended the impersonation fraud.",
           ancient_detail="Mandalorian armor impersonation scams appear in guild archives across eras; Kast represents reputation thieves who profit from legendary hunter names without earning kills.",
           modern_detail="Jodo Kast's Legends comics arc served as cautionary tale about stealing Boba Fett's identity—real Fett's response defined trademark violence on hunter impersonators.",
           conflict_detail="Kast accepted contracts using Fett's visual identity, deceived clients across Rim worlds, and confronted the real Boba Fett who dismantled his fraud operation permanently.",
           methods_detail="Fett-visual armor mimicry, borrowed reputation intimidation, standard blaster work without Fett's skill—Kast trades on fear of a name he didn't earn.",
           reputation_detail="Clients initially confused Kast for Fett; real Fett hunted him as personal insult; guild brokers blacklist armor impersonators citing Kast precedent.",
           impact_detail="Jodo Kast's defeat reinforced Boba Fett's monopoly on his own legend—impersonation attempts became guild violation with lethal enforcement.",
           events=["Adopts Boba Fett visual identity fraud", "Accepts contracts using stolen reputation", "Operates across Rim deceiving clients", "Real Boba Fett confronts impersonator", "Fraud operation permanently ended"],
           affiliations=["Boba Fett impersonation (fraud)", "Legends comics continuity", "Bounty Hunters' Guild (blacklisted)", "Mandalorian armor (stolen visual)", "Rim deception markets"],
           timeline=[("Fraud Begin", "Fett armor impersonation"), ("Contracts", "Stolen reputation work"), ("Exposure", "Clients confuse identities"), ("Confrontation", "Real Fett intervenes"), ("End", "Impersonation dismantled")])),
        ("Cradossk", "Trandoshan Hunter Patriarch", "Trandosha", "Legendary Trandoshan hunter and Bossk's father who chaired guild authority during Imperial Era.", "#65a30d", "Empire Strikes Back · comics", "trandoshan",
         d(origin_detail="Cradossk chaired the Bounty Hunters' Guild during Imperial Era as legendary Trandoshan patriarch—Bossk's father whose authority derived from scorekeeper traditions and decades of Wookiee hunt tallies.",
           ancient_detail="Trandoshan guild chairmanship passed through Cradossk bloodline for generations; his scorekeeper records predate Republic founding per Trandosha religious archives.",
           modern_detail="Cradossk's guild leadership during Bossk's rise created dynastic hunter politics—father as bureaucrat, son as field operative on Vader's Executor roster.",
           conflict_detail="Cradossk managed guild disputes between Imperial clients and Hutt syndicates while Bossk handled field contracts—splitting patriarch authority from active hunting.",
           methods_detail="Guild political negotiation, Trandoshan scorekeeper authority, Wookiee hunt contract allocation, and patriarch intimidation—Cradossk administers violence he once performed.",
           reputation_detail="Guild members answered to Cradossk's chair; Bossk inherited his name's weight; Imperial clients negotiated guild rates through his office.",
           impact_detail="Cradossk defined Trandoshan dynastic guild leadership model—patriarch chairman plus heir field hunter—structuring Imperial Era hunter bureaucracy.",
           events=["Ascends to Bounty Hunters' Guild chair", "Manages Imperial Era guild politics", "Bossk inherits field hunter role", "Oversees Wookiee hunt contract allocation", "Trandoshan patriarch dynasty established"],
           affiliations=["Bounty Hunters' Guild (chairman)", "Cradossk-Bossk dynasty", "Trandoshan scorekeeper tradition", "Galactic Empire (guild negotiator)", "Hutt Cartel contract mediation"],
           timeline=[("Trandosha", "Scorekeeper patriarch rise"), ("Guild Chair", "Bounty Hunters' Guild leadership"), ("Imperial Era", "Client negotiation authority"), ("Bossk Heir", "Field hunter succession"), ("Legacy", "Trandoshan guild dynasty")])),
        ("Mako", "Rodian Bounty Hunter", "Rodia", "SWTOR Great Hunt competitor and Braden's protégé on Dromund Kaas.", "#65a30d", "SWTOR", "rodian",
         d(origin_detail="Mako, Rodian hacker-tracker, partnered Braden's SWTOR hunter team on Dromund Kaas as Great Hunt competitor—combining Rodian tracking instincts with elite slicing skills.",
           ancient_detail="Rodia produces tracker-hacker hybrids for Exchange markets; Mako represents SWTOR-era Rodian hunters complementing Mandalorian muscle with intelligence support.",
           modern_detail="Mako's SWTOR Great Hunt partnership with Braden's protégé made her iconic Rodian companion in TOR hunter class storyline on Dromund Kaas and Nar Shaddaa.",
           conflict_detail="Mako competed in Great Hunt trials, sliced Imperial security for hunter ops, and navigated Tarro Blood's sabotage campaign against her team.",
           methods_detail="Slicing, tracking, Rodian intuition, starship nav data theft, and Great Hunt competition strategy—Mako wins through intelligence not brute force.",
           reputation_detail="Braden valued Mako's slicing; Great Hunt officials monitored her tech advantage; Rodian clans celebrate her SWTOR representation.",
           impact_detail="Mako defined SWTOR Rodian hunter companion archetype—hacker-tracker essential to Great Hunt team success against Tarro Blood.",
           events=["Joins Braden's hunter team on Dromund Kaas", "Competes in SWTOR Great Hunt", "Slicing support for hunter operations", "Partners Great Hunt protagonist", "Rodian tracker-hacker icon"],
           affiliations=["SWTOR Great Hunt", "Braden's team (successor)", "Dromund Kaas hunter markets", "Rodian tracker networks", "Tarro Blood rivals"],
           timeline=[("Rodia", "Tracker-hacker training"), ("Dromund Kaas", "Braden team join"), ("Great Hunt", "Competition begins"), ("Slicing Ops", "Intelligence support role"), ("Legacy", "SWTOR Rodian companion")])),
        ("Blizz", "Jawa Bounty Hunter", "Tatooine", "Jawa mercenary companion from SWTOR Great Hunt with sandcrawler firepower.", "#65a30d", "SWTOR", "alien",
         d(origin_detail="Blizz, Jawa mercenary, joined SWTOR Great Hunt competitor's team bringing sandcrawler-mounted heavy weapons and Tatooine scrap-field engineering to Mandalorian competition.",
           ancient_detail="Tatooine Jawa mercenary bands occasionally enter galactic hunter markets; Blizz represents rare Jawa Great Hunt participation with sandcrawler mobile arsenal.",
           modern_detail="Blizz's SWTOR companion role added comic relief and heavy firepower to Great Hunt narrative—Jawa hunter in Mandalorian-dominated competition.",
           conflict_detail="Blizz deployed sandcrawler weapons during Great Hunt trials, scavenged battlefield equipment, and supported player hunter against Tarro Blood sabotage.",
           methods_detail="Sandcrawler heavy weapons, Jawa engineering improvisation, scrap-field salvage combat, and unpredictable mercenary loyalty—Blizz fights loud and messy.",
           reputation_detail="Great Hunt competitors underestimated Blizz initially; player hunters valued his firepower; Tatooine Jawas celebrate his off-world mercenary fame.",
           impact_detail="Blizz proved Jawa mercenaries belong in SWTOR hunter narratives—diversifying Great Hunt species representation beyond Mandalorians and Rodians.",
           events=["Leaves Tatooine for Great Hunt", "Joins SWTOR player hunter team", "Deploys sandcrawler heavy weapons", "Great Hunt trial support operations", "Jawa mercenary SWTOR icon"],
           affiliations=["SWTOR Great Hunt", "Player hunter team", "Tatooine Jawa clans", "Sandcrawler mercenary unit", "Dromund Kaas competition"],
           timeline=[("Tatooine", "Jawa mercenary origins"), ("Great Hunt", "Team recruitment"), ("Trials", "Sandcrawler firepower"), ("Tarro Blood", "Sabotage response"), ("Legacy", "Jawa hunter representation")])),
        ("Gor Koresh", "Abyssin Bounty Hunter", "Byss", "Abyssin hunter who ran underground arena on Tatooine during Book of Boba Fett.", "#991b1b", "Book of Boba Fett", "alien",
         d(origin_detail="Gor Koresh, Abyssin hunter, ran Tatooine underground gladiator arena where he collected bounties on fighters—combining arena management with personal hunt contracts during Book of Boba Fett era.",
           ancient_detail="Abyssin regenerative hunters from Byss traditionally thrive in gladiator economies; Koresh represents post-Sarlacc Tatooine arena hunter culture under new Daimyo politics.",
           modern_detail="Gor Koresh's Book of Boba Fett arena operation showed hunter economies persisting on Tatooine despite Boba Fett's Daimyo restructuring of Mos Espa power.",
           conflict_detail="Koresh managed arena fights, collected fighter bounties, and clashed with Tatooine power shifts as Pyke syndicate war escalated around Mos Espa.",
           methods_detail="Abyssin regeneration in arena combat, underground fight promotion, bounty collection on defeated gladiators, and Tatooine criminal network management.",
           reputation_detail="Arena fighters feared Koresh's regeneration; Tatooine gamblers knew his venue; Book of Boba Fett audiences saw him as Dune Sea underground economy symbol.",
           impact_detail="Gor Koresh illustrated Tatooine's layered hunter economies—arena promotion alongside guild pucks—surviving Daimyo political transitions.",
           events=["Establishes Tatooine underground arena", "Collects bounties on gladiator fighters", "Operates during Book of Boba Fett era", "Navigates Pyke syndicate war chaos", "Abyssin regenerative arena hunter"],
           affiliations=["Tatooine underground arena", "Gladiator bounty markets", "Book of Boba Fett timeline", "Abyssin hunter tradition", "Mos Espa criminal economy"],
           timeline=[("Byss", "Abyssin regenerative origins"), ("Tatooine", "Arena establishment"), ("Book of Boba Fett", "Underground operations"), ("Pyke War", "Syndicate chaos navigation"), ("Legacy", "Arena hunter archetype")])),
        ("Xi'an", "Twilek Bounty Hunter", "Ryloth", "Twilek thief-hunter and Mando's former partner imprisoned aboard Bothan-5.", "#65a30d", "Mandalorian", "twilek",
         d(origin_detail="Xi'an, Twilek thief-hunter from Ryloth, was Din Djarin's former partner on a dangerous job before Ranzar Malk's crew imprisoned her aboard prison ship Bothan-5 during Grogu rescue operation.",
           ancient_detail="Ryloth Twi'lek hunter-thief hybrids populate Rim smuggling routes; Xi'an represents Din Djarin's pre-Nevarro partnership history in guild underworld.",
           modern_detail="Xi'an's Mandalorian episode revealed Din's past crew relationships and complicated Ranzar Malk's betrayal during New Republic prison break sequence.",
           conflict_detail="Xi'an joined Ranzar's crew targeting Grogu on Bothan-5, confronted Din Djarin over past partnership, and navigated prison ship combat during rescue chaos.",
           methods_detail="Twi'lek agility, knife combat, thief infiltration, and former partnership leverage—Xi'an fights close and personal with emotional history as weapon.",
           reputation_detail="Din Djarin trusted Xi'an once before betrayal patterns; Ranzar Malk used her skills until Bothan-5 chaos; Twi'lek networks know her thief-hunter reputation.",
           impact_detail="Xi'an expanded Din Djarin's backstory—showing Mandalorian hunter had partnership history and trust failures before Grogu foundling bond defined his path.",
           events=["Former partnership with Din Djarin", "Joins Ranzar Malk's Bothan-5 crew", "Targets Grogu on prison ship", "Confronts Din over shared past", "Prison break combat sequence"],
           affiliations=["Din Djarin (former partner)", "Ranzar Malk's crew", "Bothan-5 prison ship", "Ryloth Twi'lek networks", "Nevarro hunter underworld"],
           timeline=[("Partnership", "Din Djarin crew history"), ("Ranzar Crew", "Bothan-5 recruitment"), ("Prison Ship", "Grogu target operation"), ("Confrontation", "Past partnership clash"), ("Legacy", "Din's backstory expansion")])),
        ("Q9-0", "Zero Assassin Droid", "Unknown manufacture", "Ranzar Malk's assassin droid who nearly killed Grogu before Din Djarin destroyed him.", "#64748b", "Mandalorian", "droid",
         d(origin_detail="Q9-0, called Zero, served Ranzar Malk's crew as assassin droid specializing in precise elimination—nearly killing Grogu aboard Bothan-5 before Din Djarin destroyed him.",
           ancient_detail="Assassin droid precision units follow IG-88 and IG-11 lineage; Zero represents Imperial-adjacent droid hunters in New Republic era prison break operations.",
           modern_detail="Zero's Mandalorian episode antagonism toward Grogu paralleled IG-11's redemption arc inversion—assassin droid who would not be reprogrammed into protector.",
           conflict_detail="Zero infiltrated New Republic prison ship, targeted infant Grogu for elimination, fought Din Djarin in close combat, and was destroyed protecting Ranzar Malk's contract.",
           methods_detail="Assassin droid precision shooting, infiltration protocols, emotionless target elimination, and tactical analysis—Zero treats Grogu as pure contract objective.",
           reputation_detail="Ranzar Malk trusted Zero's precision; Din Djarin destroyed him to protect Grogu; droid hunters compare Zero unfavorably to IG-11's sacrificial redemption.",
           impact_detail="Q9-0's destruction reinforced Din-Grogu bond—assassin droid failure contrasting IG-11's protective sacrifice on same narrative theme.",
           events=["Serves Ranzar Malk's crew as assassin", "Infiltrates Bothan-5 prison ship", "Targets Grogu for elimination", "Fights Din Djarin in combat", "Destroyed protecting infant Grogu"],
           affiliations=["Ranzar Malk's crew", "Bothan-5 operation", "Assassin droid manufacturing", "Grogu target contract", "Din Djarin (destroyed by)"],
           timeline=[("Activation", "Ranzar Malk recruitment"), ("Bothan-5", "Prison ship infiltration"), ("Grogu Target", "Assassination attempt"), ("Combat", "Din Djarin confrontation"), ("Destruction", "Droid eliminated")])),
        ("Hondo Ohnaka", "Pirate King (Bounty Contractor)", "Sriluur", "Weequay pirate who alternately hired hunters and placed bounties during Clone Wars and Rebels.", "#991b1b", "Clone Wars · Rebels", "weequay",
         d(origin_detail="Hondo Ohnaka built Florrum-based pirate empire alternately hiring bounty hunters and placing pucks on rivals—Weequay kingpin whose contracts shaped Clone Wars and Rebels hunter economies.",
           ancient_detail="Sriluur Weequay pirate-kajidic traditions blend smuggling and bounty placement; Hondo represents pirate contractors who compete with guild for Rim enforcement.",
           modern_detail="Hondo's Rebels era partnership with Ezra Bridger showed pirate-bounty hybrid evolution—same Hondo who fought Sugi on Felucia later aided Rebellion for profit.",
           conflict_detail="Hondo fought Sugi and Embo on Felucia, captured Count Dooku briefly for ransom, lost Florrum base repeatedly, and supplied Rebels with smuggler-hunter intelligence.",
           methods_detail="Pirate fleet assault, ransom negotiation, bounty placement on rivals, charismatic betrayal, and Florrum base operations—Hondo contracts hunters when piracy insufficient.",
           reputation_detail="Guild hunters price Hondo as employer and obstacle; Dooku ransomed from him once; Rebels tolerate him for useful chaos; Weequay pirates study his survival instincts.",
           impact_detail="Hondo Ohnaka linked pirate and bounty economies across Clone Wars and Rebels—proving Rim power brokers both hire hunters and become targets.",
           events=["Builds Florrum pirate empire", "Fights Sugi's crew on Felucia", "Captures Count Dooku for ransom", "Places and hires bounty contracts", "Rebels era Ezra Bridger alliance"],
           affiliations=["Ohnaka pirate gang", "Florrum base operations", "Hutt Cartel (adjacent)", "Rebel Alliance (opportunistic)", "Bounty Hunters' Guild (client and rival)"],
           timeline=[("Florrum", "Pirate empire founding"), ("Felucia", "Fights Sugi and Embo"), ("Dooku Ransom", "Brief Separatist capture"), ("Clone Wars", "Hunter contract cycles"), ("Rebels", "Ezra alliance era")])),
        ("Onca", "Selkath Bounty Hunter", "Manaan", "Selkath hunter paired with Derrown in Moralo Eval's box tournament.", "#65a30d", "Clone Wars", "alien",
         d(origin_detail="Onca, Selkath hunter from Manaan, competed in Moralo Eval's box tournament alongside Derrown—pairing aquatic species hunter traditions in Separatist assassin recruitment trials.",
           ancient_detail="Manaan's Selkath warriors occasionally leave kolto homeworld for mercenary markets; Onca represents amphibious hunters in Core gladiator competitions.",
           modern_detail="Onca's box tournament pairing with Derrown showcased Selkath-Parwan hunter team dynamics in Clone Wars' deadliest assassin screening event.",
           conflict_detail="Onca survived early box trial stages using Selkath combat training before Eval's lethal platform mechanisms eliminated competitors.",
           methods_detail="Selkath aquatic combat adapted to arena, paired operations with Derrown's gas attacks, and Manaan warrior discipline in gladiator environment.",
           reputation_detail="Eval's organizers paired Onca with Derrown deliberately; box competitors noted Selkath resilience; Manaan mercenary diaspora cites tournament representation.",
           impact_detail="Onca validated Selkath hunter participation in Core tournaments—amphibious species competing alongside Duros and Mandalorian legends.",
           events=["Leaves Manaan for bounty markets", "Enters Moralo Eval's box tournament", "Pairs with Derrown in trials", "Selkath combat in arena stages", "Clone Wars assassin pipeline candidate"],
           affiliations=["Moralo Eval's box roster", "Derrown partnership", "Manaan Selkath warriors", "Separatist assassin recruitment", "Bounty Hunters' Guild"],
           timeline=[("Manaan", "Selkath warrior training"), ("Box Entry", "Eval tournament"), ("Partnership", "Derrown team trials"), ("Arena", "Survival stages"), ("Legacy", "Selkath hunter representation")])),
        ("Sinrich", "Rattataki Bounty Hunter", "Rattatak", "Rattataki inventor hunter who deployed holographic decoys in the box challenge.", "#65a30d", "Clone Wars", "zabrak",
         d(origin_detail="Sinrich, Rattataki inventor-hunter from Rattatak, entered Moralo Eval's box deploying holographic decoy technology—tech-specialist among gladiator-hunter competitors.",
           ancient_detail="Rattatak's isolation produced inventor warriors; Sinrich represents tech-augmented hunters predating later droid-hunter integration in guild markets.",
           modern_detail="Sinrich's holographic decoys in Eval's box demonstrated Rattataki technological hunter edge in Clone Wars assassin recruitment tournament.",
           conflict_detail="Sinrich used decoy projections to confuse box competitors during Serenno trials until platform retraction and rival adaptation countered his technology.",
           methods_detail="Holographic decoy deployment, Rattataki inventor engineering, arena confusion tactics, and tech-specialist survival in gladiator environment.",
           reputation_detail="Box competitors initially disoriented by Sinrich's decoys; Eval noted his technical innovation; Rattataki clans celebrate inventor-hunter representation.",
           impact_detail="Sinrich proved tech-specialist hunters belong in gladiator tournaments—holographic warfare as legitimate box competition methodology.",
           events=["Develops holographic decoy hunter tech", "Enters Moralo Eval's box tournament", "Deploys decoys against competitors", "Serenno trial survival attempts", "Rattataki inventor-hunter showcase"],
           affiliations=["Moralo Eval's box roster", "Rattatak inventor tradition", "Separatist tech pipeline", "Bounty Hunters' Guild", "Holographic decoy patents"],
           timeline=[("Rattatak", "Inventor warrior training"), ("Tech Dev", "Holographic decoy creation"), ("Box Entry", "Eval tournament"), ("Serenno", "Decoy deployment trials"), ("Legacy", "Tech-hunter archetype")])),
        ("Twazzi", "Frenk Bounty Hunter", "Unknown", "Frenk acrobat hunter who competed in Eval's box before Separatist service.", "#65a30d", "Clone Wars", "alien",
         d(origin_detail="Twazzi, Frenk acrobat-hunter, brought aerial agility to Moralo Eval's box tournament—using acrobatic mobility to survive retractable platform trials other hunters couldn't.",
           ancient_detail="Frenk acrobat mercenary circuses supplied gladiator hunters for centuries; Twazzi represents performance-athlete hunters in Separatist recruitment pipelines.",
           modern_detail="Twazzi's box acrobatics showcased Frenk physical specialization in Clone Wars hunter gladiator event alongside Cad Bane and Derrown.",
           conflict_detail="Twazzi navigated Eval's platform retraction traps with acrobatic leaps, surviving longer than grounded competitors until tournament logic eliminated all but assassin recruits.",
           methods_detail="Frenk acrobatic mobility, aerial evasion, platform-to-platform leaps, and performance-hunter showmanship converted to lethal trial survival.",
           reputation_detail="Box audiences noted Twazzi's aerial grace; Eval valued agility testing; Frenk diaspora cites acrobat-hunter box representation.",
           impact_detail="Twazzi validated acrobat-species hunters in assassin recruitment tournaments—mobility as survival advantage in Eval's death course design.",
           events=["Frenk acrobat mercenary background", "Enters Moralo Eval's box tournament", "Acrobatic platform survival attempts", "Separatist service post-tournament", "Clone Wars agility hunter icon"],
           affiliations=["Moralo Eval's box roster", "Frenk acrobat tradition", "Separatist assassin pipeline", "Bounty Hunters' Guild", "Gladiator circuit (former)"],
           timeline=[("Frenk Training", "Acrobat mercenary roots"), ("Box Entry", "Eval tournament"), ("Serenno", "Platform acrobatics"), ("Survival", "Agility trial stages"), ("Legacy", "Acrobat-hunter model")])),
        ("Mantu", "Selkath Bounty Hunter", "Manaan", "Selkath warrior hunter in box tournament representing Manaan mercenary traditions.", "#65a30d", "Clone Wars", "alien",
         d(origin_detail="Mantu, Selkath warrior from Manaan, competed in Moralo Eval's box representing his homeworld's mercenary traditions alongside fellow Selkath Onca in assassin recruitment trials.",
           ancient_detail="Manaan's kolto wealth funded Selkath warrior exports to mercenary markets; Mantu continues amphibious hunter tradition Onca also represents.",
           modern_detail="Mantu and Onca's dual Selkath box presence showcased Manaan producing multiple hunter competitors in same Separatist tournament—unusual homeworld representation density.",
           conflict_detail="Mantu applied Selkath warrior training in box arena combat, surviving initial trial phases before Eval's lethal course design eliminated competitors.",
           methods_detail="Selkath warrior combat, Manaan honor discipline, amphibious adaptation in arena, and paired-homeworld pride driving tournament performance.",
           reputation_detail="Eval noted dual Selkath entries; Manaan mercenary brokers celebrated twin representation; box competitors respected Selkath resilience.",
           impact_detail="Mantu reinforced Manaan as hunter-exporting homeworld alongside Onca—dual Selkath box entries rare in tournament history.",
           events=["Selkath warrior training on Manaan", "Enters Moralo Eval's box tournament", "Competes alongside fellow Selkath Onca", "Arena warrior combat trials", "Manaan mercenary tradition showcase"],
           affiliations=["Moralo Eval's box roster", "Manaan Selkath warriors", "Onca (homeworld peer)", "Separatist recruitment", "Bounty Hunters' Guild"],
           timeline=[("Manaan", "Warrior training"), ("Box Entry", "Eval tournament"), ("Arena", "Combat trial stages"), ("Dual Selkath", "Onca parallel entry"), ("Legacy", "Manaan hunter export")])),
        ("Sixtat", "Zabrak Bounty Hunter", "Iridonia", "Zabrak sniper eliminated during Eval's box when platforms retracted.", "#65a30d", "Clone Wars", "zabrak",
         d(origin_detail="Sixtat, Zabrak sniper from Iridonia, entered Moralo Eval's box tournament as precision shooter eliminated when retractable platforms dropped him into arena depths.",
           ancient_detail="Iridonia Zabrak sniper cadres supply mercenary overwatch across eras; Sixtat's box death demonstrates even precision specialists fail Eval's trap engineering.",
           modern_detail="Sixtat's platform-retraction elimination became box tournament cautionary moment—sniper skill insufficient against Moralo Eval's engineered death course.",
           conflict_detail="Sixtat provided sniper overwatch in early box stages until platform mechanism triggered, dropping him to elimination despite Zabrak combat training.",
           methods_detail="Zabrak sniper precision, elevated platform overwatch, long-range elimination of competitors, and Iridonia discipline—undone by trap engineering not rival skill.",
           reputation_detail="Box competitors witnessed Sixtat's platform fall; Eval used his elimination as course demonstration; Iridonia sniper cadres study his failure as trap-awareness lesson.",
           impact_detail="Sixtat's elimination illustrated Eval's box prioritizes trap survival over raw skill—sniper precision worthless against engineered platform betrayal.",
           events=["Iridonia Zabrak sniper training", "Enters Moralo Eval's box tournament", "Sniper overwatch in early trials", "Eliminated by platform retraction trap", "Cautionary box tournament death"],
           affiliations=["Moralo Eval's box roster", "Iridonia Zabrak snipers", "Separatist recruitment (failed)", "Bounty Hunters' Guild", "Eval trap engineering (victim)"],
           timeline=[("Iridonia", "Sniper cadre training"), ("Box Entry", "Eval tournament"), ("Overwatch", "Early trial sniping"), ("Trap Death", "Platform retraction fall"), ("Legacy", "Trap-awareness lesson")])),
        ("Jakoli", "Rodian Bounty Hunter", "Rodia", "Rodian hunter known for never bringing targets alive; box tournament competitor.", "#65a30d", "Clone Wars", "rodian",
         d(origin_detail="Jakoli, Rodian hunter from Rodia, built reputation for never bringing targets alive before entering Moralo Eval's box—lethal Rodian tradition in gladiator assassin screening.",
           ancient_detail="Rodia hunter clans debate kill-vs-capture ethics; Jakoli represents extreme lethal-only Rodian contractors predating Greedo's cantina confrontation fame.",
           modern_detail="Jakoli's no-prisoners policy made him box tournament outlier—Eval valued lethal intent for assassination recruitment pipeline over guild capture standards.",
           conflict_detail="Jakoli competed in Eval's box using lethal Rodian tracking, eliminating competitors permanently rather than disabling—matching Separatist assassin requirements.",
           methods_detail="Rodian lethal tracking, no-capture kill policy, box arena ambushes, and clan honor through permanent elimination of all targets.",
           reputation_detail="Box organizers noted Jakoli's kill-only policy; Rodian clans divided on his extremism; guild capture specialists considered him professionally deviant.",
           impact_detail="Jakoli represented lethal-only hunter subclass Separatists preferred for assassination pipeline—capture-alive guild norms explicitly rejected.",
           events=["Builds no-capture Rodian reputation", "Enters Moralo Eval's box tournament", "Lethal elimination of box competitors", "Separatist assassin pipeline candidate", "Rodian kill-only hunter icon"],
           affiliations=["Moralo Eval's box roster", "Rodia hunter clans", "Separatist assassination pipeline", "Bounty Hunters' Guild (deviant)", "Lethal-only contractor market"],
           timeline=[("Rodia", "Kill-only hunter training"), ("Reputation", "No-capture policy established"), ("Box Entry", "Eval tournament"), ("Lethal Trials", "Permanent eliminations"), ("Legacy", "Assassin pipeline fit")])),
        ("Amanaman", "Snivvian Bounty Hunter", "Cadomai Prime", "Snivvian hunter present in Jabba's palace during Return of the Jedi.", "#991b1b", "Return of the Jedi", "alien",
         d(origin_detail="Amanaman, Snivvian hunter from Cadomai Prime, occupied Jabba's palace court during Return of the Jedi—silent Snivvian presence among Hutt criminal hunter retinue.",
           ancient_detail="Cadomai Prime Snivvian hunters serve Hutt courts across eras; Amanaman represents background palace hunter retinue during saga's Tatooine criminal climax.",
           modern_detail="Amanaman's Jabba palace presence during Solo rescue and sail barge battle places him in saga's most documented Hutt hunter court scene.",
           conflict_detail="Amanaman witnessed palace chaos during Luke's rescue attempt, sail barge departure, and Jabba's death—Snivvian hunter observing Hutt empire collapse.",
           methods_detail="Snivvian silent observation, palace court presence as intimidation, Hutt retinue hunter standby, and Cadomai Prime tracking traditions.",
           reputation_detail="Jabba's court included Amanaman among diverse hunter retinue; palace witnesses remember Snivvian silhouette during sail barge events.",
           impact_detail="Amanaman documents Snivvian hunter integration in Hutt court retinue—background species presence in saga's definitive criminal hunter gathering.",
           events=["Serves in Jabba's palace hunter retinue", "Present during Han Solo rescue attempt", "Witnesses sail barge departure", "Observes Jabba's death and court collapse", "Snivvian palace hunter documentation"],
           affiliations=["Jabba the Hutt's court", "Cadomai Prime Snivvian hunters", "Tatooine criminal retinue", "Hutt Cartel enforcement", "Sail barge court"],
           timeline=[("Cadomai Prime", "Snivvian hunter origins"), ("Jabba Court", "Palace retinue service"), ("Rescue Attempt", "Luke's palace infiltration"), ("Sail Barge", "Departure and battle"), ("Collapse", "Jabba's death aftermath")])),
        ("Kaba Baiz", "Klatooinian Bounty Target Hunter", "Klatooine", "Klatooinian butcher whose bounty drew Din Djarin to Glavis Ring in Mandalorian season 3.", "#65a30d", "Mandalorian", "alien",
         d(origin_detail="Kaba Baiz, Klatooinian butcher on Glavis Ring space station, became bounty target whose puck drew Din Djarin into Mandalorian season 3's opening hunt showcasing post-Boba hunter economy.",
           ancient_detail="Klatooinian Hutt servitude traditions produce station butchers and enforcers; Kaba Baiz represents targets whose bounties launch hunter narrative arcs.",
           modern_detail="Kaba Baiz's Mandalorian season 3 bounty opening reestablished Din Djarin as active guild hunter before Mandalore reclamation plot dominated the season.",
           conflict_detail="Din Djarin hunted Kaba Baiz on Glavis Ring for unpaid debts or syndicate contract, demonstrating Mandalorian season 3 hunter work before Creed plot accelerated.",
           methods_detail="Klatooinian butcher station operations, Glavis Ring underworld connections, and target behavior forcing hunter extraction—Kaba Baiz is pursued not pursuer.",
           reputation_detail="Glavis Ring residents knew Kaba Baiz's butcher shop; Din Djarin collected his puck efficiently; guild brokers used Glavis hunt as season opener marketing.",
           impact_detail="Kaba Baiz bounty launched Mandalorian season 3 with classic puck-work before epic Mandalore arc—anchoring Din in guild reality before Mand'alor destiny.",
           events=["Operates butcher shop on Glavis Ring", "Bounty posted on Kaba Baiz", "Din Djarin hunt on space station", "Mandalorian season 3 opening contract", "Klatooinian target hunter narrative"],
           affiliations=["Glavis Ring station", "Klatooinian butcher trade", "Syndicate debt targets", "Din Djarin (hunter pursuer)", "Nevarro guild network"],
           timeline=[("Klatooine", "Klatooinian origins"), ("Glavis Ring", "Butcher shop operations"), ("Bounty Posted", "Puck issued on Baiz"), ("Season 3 Open", "Din Djarin hunt"), ("Legacy", "Mando season opener target")])),
    ]
    for e in entries:
        _add(*e)
