#!/usr/bin/env python3
"""Part 2 bounty hunter entries."""


def register_rest2(_add, L):
    hunters = [
        ("Zam Wesell", "Clawdite Assassin", "Zolan",
         "Shapeshifting Clawdite hired to kill Padmé Amidala; silenced by Jango's Kamino saberdart.",
         "#0891b2", "Attack of the Clones", "clawdite",
         L(origin_detail="Zam Wesell trained on Zolan as a Clawdite shapeshifter selling assassination to Separatist intermediaries, using form-shift infiltration where blasters would fail.",
           ancient_detail="Clawdite metamorph traditions on Zolan predate the Republic; KOTOR intelligence archives document shapeshifter assassins bypassing Senate security for millennia.",
           modern_detail="Zam's death by Jango's Kamino saberdart in Coruscant alleyways exposed the clone army trail—her assassination attempt triggered the chain revealing Kamino.",
           conflict_detail="Zam bombed Padmé's Naboo cruiser, infiltrated Coruscant as multiple identities, and died when Jango silenced her before Obi-Wan could interrogate her.",
           methods_detail="Clawdite shapeshifting, sniper rifle from speeder lanes, explosive sabotage, and identity infiltration—Zam kills from inside the target's trust perimeter.",
           reputation_detail="Dooku's agents valued Zam's discretion; Jedi investigators never caught her true face until post-mortem; Clawdite guilds cite her Amidala contract as masterwork.",
           impact_detail="Zam Wesell's failed assassination set Obi-Wan on Jango's trail to Kamino—without her contract, the clone conspiracy might have stayed hidden longer.",
           events=["Bombs Padmé Amidala's Naboo cruiser", "Assassinates via speeder-lane sniper attempt", "Infiltrates Coruscant in shapeshifted forms", "Killed by Jango's Kamino saberdart", "Death leads Obi-Wan to Kamino discovery"],
           affiliations=["Count Dooku / CIS (contracted)", "Clawdite assassin networks", "Zolan shapeshifter clans", "Separatist shadow accounts", "Coruscant underworld brokers"],
           timeline=[("Zolan", "Clawdite assassin training"), ("Contract", "Hired to kill Senator Amidala"), ("Naboo Cruiser", "Bombing attempt"), ("Coruscant", "Speeder chase with Anakin"), ("Death", "Silenced by Jango Fett")])),
        ("Fennec Shand", "Master Assassin", "Unknown",
         "Precision sniper who survived Tatooine's Dune Sea and became Boba Fett's Daimyo enforcer.",
         "#0284c7", "Mandalorian · Book of Boba Fett · Bad Batch", "human",
         L(origin_detail="Fennec Shand built reputation as a Core-tier assassin before Toro Calican's betrayal left her wounded in Tatooine's Dune Sea, where Boba Fett's rescue forged an alliance.",
           ancient_detail="Assassin guilds from Coruscant to Muunilinst maintained sniper cadres centuries before Fennec; TOR-era Imperial Intelligence used similar precision contractors.",
           modern_detail="Rebuilt with cybernetic enhancements, Fennec became Boba Fett's Daimyo lieutenant, killing Bib Fortuna's guards and coordinating Mos Espa defense against Pyke syndicate forces.",
           conflict_detail="Fennec hunted Grogu for Imperial remnant clients, survived Dune Sea wounds, executed Toro Calican, and led tactical operations during Boba's Mos Espa power grab.",
           methods_detail="Long-range sniper precision, cybernetic enhancement after Dune Sea trauma, close-quarters bladed combat, and tactical coordination—Fennec combines assassin patience with enforcer loyalty.",
           reputation_detail="Toro Calican called her the finest assassin in the sector; Boba trusted her with Daimyo operations; Pyke capos learned to fear her rooftop overwatch.",
           impact_detail="Fennec's partnership stabilized Boba Fett's Daimyo transition; her survival and enhancement arc exemplifies post-Empire hunter reinvention on Tatooine.",
           events=["Hunted as elite Core assassin", "Wounded and left in Tatooine Dune Sea", "Rescued and allied with Boba Fett", "Kills Toro Calican in revenge", "Serves as Mos Espa Daimyo lieutenant"],
           affiliations=["Boba Fett's court", "Mos Espa Daimyo administration", "Bounty Hunters' Guild (former)", "Cybernetic enhancement clinics", "Tatooine crime syndicates"],
           timeline=[("Core Assassin", "Elite sniper reputation"), ("Dune Sea", "Betrayed by Toro Calican"), ("Rescue", "Boba Fett alliance"), ("Revenge", "Kills Toro Calican"), ("Book of Boba Fett", "Daimyo enforcer")])),
        ("Din Djarin", "Mandalorian Bounty Hunter", "Aq Vallack (foundling)",
         "Foundling hunter who captured Grogu for Nevarro guild before breaking Creed to become Mand'alor.",
         "#0284c7", "Mandalorian · Book of Boba Fett", "mando",
         L(origin_detail="Rescued as a foundling by Death Watch during the Clone Wars, Din Djarin was raised on Concordia under the Way of Mandalore and became a guild hunter on Nevarro under Greef Karga.",
           ancient_detail="Mandalorian foundling traditions stretch to KOTOR-era Neo-Crusaders; Din's Creed-breaking choice to protect Grogu echoes ancient debates over hunter honor versus foundling bonds.",
           modern_detail="Din returned Grogu to Jedi training, reclaimed Mandalore from Imperial remnant occupation, and accepted the Darksaber to become Mand'alor—transcending guild work entirely.",
           conflict_detail="Din captured Grogu for Imperial remnant client, fought IG-11 and Moff Gideon's forces on Nevarro, assembled a Mandalorian covert on Glavis Ring, and retook Mandalore from Gideon's base.",
           methods_detail="Beskar armor, Amban sniper rifle, whistling birds, jetpack assault, and Mudhorn signet—Din combines Mandalorian martial code with guild pragmatism until Creed supersedes contracts.",
           reputation_detail="Greef Karga posted his puck; Bo-Katan initially dismissed him; the Armorer declared him apostate then prophet; Grogu's bond made him legend beyond any single contract total.",
           impact_detail="Din's Grogu protection altered Imperial remnant plans; his Mandalore reclamation restored Mandalorian sovereignty; he proved foundling bonds can override guild and Imperial payment alike.",
           events=["Captures Grogu for Nevarro guild contract", "Protects Grogu and breaks bounty delivery", "Defeats Moff Gideon's Imperial remnant on Nevarro", "Retrieves Darksaber and founds covert on Glavis Ring", "Retakes Mandalore and becomes Mand'alor"],
           affiliations=["Children of the Watch", "Nevarro Bounty Hunters' Guild", "Clan Mudhorn", "Mandalorian covert", "Grogu foundling bond", "Greef Karga (former employer)"],
           timeline=[("Foundling", "Raised by Death Watch"), ("Nevarro", "Guild hunter under Greef Karga"), ("Grogu Contract", "Capture and Creed break"), ("Imperial Remnant", "Fights Gideon's forces"), ("Mandalore", "Becomes Mand'alor")])),
        ("Toro Calican", "Aspirant Bounty Hunter", "Unknown",
         "Ambitious rookie who betrayed Din Djarin hunting Fennec Shand and died to her vengeance.",
         "#65a30d", "Mandalorian", "human",
         L(origin_detail="Toro Calican arrived on Tatooine desperate to make guild name by capturing Fennec Shand, recruiting Din Djarin with flattery before planning to steal credit and fame.",
           ancient_detail="Guild aspirant culture on Tatooine dates to Hutt-era posting boards; KOTOR Nar Shaddaa records show similar rookies betraying partners for debut contracts.",
           modern_detail="Toro's betrayal and death by Fennec Shand became cautionary tale for Nevarro guild cadets—proof that stealing a veteran's hunt ends worse than failing honestly.",
           conflict_detail="Toro partnered with Din Djarin tracking Fennec Shand, handcuffed Djarin to steal the capture, and left Fennec wounded in the Dune Sea before she killed him in retaliation.",
           methods_detail="Blaster work, speeder bike pursuit, handcuff betrayal, and social manipulation—Toro had ambition and equipment but lacked honor or survival instinct.",
           reputation_detail="Fennec dismissed him as a wannabe; Din survived his betrayal; Tatooine guild brokers blacklisted his name posthumously as partnership poison.",
           impact_detail="Toro's betrayal directly caused Fennec Shand's Dune Sea wounds and her subsequent alliance with Boba Fett—his failure reshaped Tatooine power dynamics.",
           events=["Recruits Din Djarin on Tatooine", "Tracks Fennec Shand together", "Betrayals and handcuffs Djarin", "Leaves Fennec wounded in Dune Sea", "Killed by Fennec Shand in revenge"],
           affiliations=["Bounty Hunters' Guild (aspirant)", "Tatooine posting boards", "Fennec Shand hunt (target)", "Din Djarin (betrayed partner)"],
           timeline=[("Tatooine Arrival", "Seeks Fennec Shand puck"), ("Partnership", "Recruits Din Djarin"), ("Betrayal", "Handcuffs Djarin"), ("Dune Sea", "Wounds Fennec"), ("Death", "Killed by Fennec Shand")])),
        ("Migs Mayfeld", "Imperial Sharpshooter Turned Hunter", "Turbolift City",
         "Cynical ex-Imperial marksman who helped Din Djarin infiltrate Morak refinery.",
         "#64748b", "Mandalorian", "human",
         L(origin_detail="Migs Mayfeld served as Imperial sharpshooter before Imperial collapse left him cynical guild work on Nevarro, where survival mattered more than ideology.",
           ancient_detail="Imperial remnant sharpshooters on Morak and similar refinery worlds appear in Andor-era ISB archives; Mayfeld represents veteran gunners sold to guild markets post-Endor.",
           modern_detail="Mayfeld's Morak infiltration with Din Djarin exposed Operation: Cinder connections; his choice to let Din kill ex-Imperial officer showed personal justice overriding contracts.",
           conflict_detail="Mayfeld joined Din's prison break, infiltrated Morak Imperial refinery disguised as troopers, and confronted the officer responsible for Burnin Konday destruction.",
           methods_detail="Imperial marksman training, disguised infiltration, heavy blaster work, and cynical improvisation—Mayfeld knows Imperial protocols better than most active hunters.",
           reputation_detail="Greef Karga vouched for his skills if not his attitude; Din trusted him inside an Imperial base; Mayfeld himself expected betrayal and planned accordingly.",
           impact_detail="Mayfeld's Morak mission provided intelligence on Imperial remnant logistics and demonstrated ex-Imperial specialists remain valuable guild assets post-Endor.",
           events=["Imperial sharpshooter service", "Imprisoned on Nevarro with Din Djarin", "Infiltrates Morak refinery in disguise", "Confronts Burnin Konday officer", "Released after successful mission"],
           affiliations=["Galactic Empire (former)", "Nevarro Bounty Hunters' Guild", "Din Djarin (mission partner)", "Morak Imperial remnant (infiltrated)", "Imperial sharpshooter corps (former)"],
           timeline=[("Imperial Era", "Sharpshooter service"), ("Nevarro Prison", "Meets Din Djarin"), ("Morak Infiltration", "Refinery disguise mission"), ("Confrontation", "Burnin Konday reckoning"), ("Release", "Freedom after mission")])),
        ("Black Krrsantan", "Wookiee Bounty Hunter", "Kashyyyk",
         "Exiled scarred Wookiee gladiator who served Vader and Doctor Aphra with brutal close-quarters violence.",
         "#991b1b", "Comics · Doctor Aphra", "wookiee",
         L(origin_detail="Black Krrsantan was exiled from Kashyyyk with ritual scarring, sold into gladiatorial circuits before Vader recruited him as a Wookiee hunter who could match his own people's strength.",
           ancient_detail="Wookiee exile traditions and gladiator markets on Nar Shaddaa predate Krrsantan; KOTOR Exchange records document scarred Wookiee enforcers hunting their own kin for credits.",
           modern_detail="Krrsantan's partnership with Doctor Aphra on artifact heists made him a marquee comics-era hunter; his gladiator past and Vader contract defined brutal close-quarters reputation.",
           conflict_detail="Krrsantan served Darth Vader hunting Chewbacca, fought Doctor Aphra's enemies across archaeological war zones, and battled in underworld arenas from Nar Shaddaa to Coruscant.",
           methods_detail="Wookiee strength amplified by gladiator training, bowcaster and bare-hand violence, intimidation through scarred appearance—Krrsantan breaks targets rather than capturing alive.",
           reputation_detail="Vader valued him against Rebel Wookiees; Aphra kept him on retainer; Kashyyyk exiles consider him traitor while guild brokers consider him premium muscle.",
           impact_detail="Black Krrsantan proved exiled Wookiees could become the Empire's anti-Wookiee weapon; his Aphra partnership expanded hunter roles into archaeological mercenary work.",
           events=["Exiled and scarred from Kashyyyk", "Gladiator circuit on Nar Shaddaa", "Recruited by Darth Vader for Wookiee hunts", "Partners with Doctor Aphra on heists", "Battles Chewbacca and Rebel allies"],
           affiliations=["Doctor Aphra's crew", "Darth Vader (contracted)", "Nar Shaddaa gladiator circuits", "Kashyyyk exile networks", "Hutt Cartel (contracted)", "Archaeological black market"],
           timeline=[("Kashyyyk", "Exile and scarring"), ("Gladiator Era", "Nar Shaddaa circuits"), ("Vader Contract", "Anti-Wookiee missions"), ("Aphra Partnership", "Artifact heists"), ("War of the Bounty Hunters", "Han Solo carbonite chase")])),
        ("Asajj Ventress", "Bounty Hunter (Post-Sith)", "Dathomir",
         "Former Sith assassin who reinvented as guild hunter after Dooku's betrayals; died saving Quinlan Vos.",
         "#0891b2", "Clone Wars · Dark Disciple", "zabrak",
         L(origin_detail="Raised by Nightsisters and trained as Dooku's Sith assassin, Asajj Ventress survived multiple betrayals and reinvented herself as a Bounty Hunters' Guild contractor on Tatooine and Quarren.",
           ancient_detail="Dathomir Nightsister hunter magic and Sith assassin training predate Ventress; KOTOR Sith acolyte programs on Korriban ran parallel force-user mercenary pipelines.",
           modern_detail="Ventress's Dark Disciple arc hunting with Quinlan Vos ended in her death saving him from Dooku—transforming Sith assassin into redeemed hunter martyr in guild folklore.",
           conflict_detail="Ventress fought Jedi across the Clone Wars, hunted Separatist deserters as guild work, partnered Quinlan Vos against Dooku, and died absorbing Force lightning meant for her partner.",
           methods_detail="Dual curved lightsabers (when armed), Nightsister force techniques, guild negotiation, and assassin infiltration—Ventress combines dark side training with bounty pragmatism.",
           reputation_detail="Jedi feared her across the Clone Wars; guild brokers respected her post-Sith reinvention; Quinlan Vos mourned her as partner beyond any contract.",
           impact_detail="Ventress's transition from Sith assassin to guild hunter proved Force-users could exit dark side service; her sacrifice influenced Vos and Nightsister-Dathomir politics.",
           events=["Serves Count Dooku as Sith assassin", "Survives Dooku's betrayal on Dathomir", "Reinvents as Bounty Hunters' Guild contractor", "Partners Quinlan Vos against Dooku", "Dies saving Vos from Force lightning"],
           affiliations=["Nightsisters of Dathomir", "Bounty Hunters' Guild", "Quinlan Vos partnership", "Count Dooku / CIS (former)", "Tatooine guild postings", "Dark Disciple operation"],
           timeline=[("Dathomir", "Nightsister training"), ("Sith Assassin", "Dooku's apprentice"), ("Betrayal", "Cast aside; joins guild"), ("Dark Disciple", "Partners Quinlan Vos"), ("Sacrifice", "Dies saving Vos from Dooku")])),
        ("Beilert Valance", "Cyborged Bounty Hunter", "Chorin",
         "Imperial-turned-hunter cyborg who hunted Han Solo in War of the Bounty Hunters comics arc.",
         "#64748b", "Comics · War of the Bounty Hunters", "cyborg",
         L(origin_detail="Beilert Valance served as Imperial officer on Chorin until injuries required extensive cybernetic reconstruction; discharged and bitter, he entered bounty markets with military precision and hatred for the Empire that discarded him.",
           ancient_detail="Chorin's mining officer corps supplied Imperial cadres; cyborg reconstruction clinics on Nar Shaddaa documented similar veterans turned hunters after medical discharge.",
           modern_detail="Valance became central to War of the Bounty Hunters after Han Solo's carbonite theft, hunting across Nar Shaddaa, Corellia, and Rebel-adjacent space with cyborg-enhanced endurance.",
           conflict_detail="Valance fought Imperial holdouts, competed for Solo's carbonite puck, clashed with Boba Fett and other marquee hunters, and navigated post-Endor power vacuum guild wars.",
           methods_detail="Military tactical planning, cybernetic strength and resilience, starship combat, and blaster precision—Valance treats hunts like Imperial operations with hunter profit motive.",
           reputation_detail="Guild brokers rank Valance among top Imperial-era cyborg hunters; his War of the Bounty Hunters performance elevated him to marquee comics status alongside Fett and Dengar.",
           impact_detail="Valance exemplifies Imperial veteran reinvention in hunter markets; his Solo pursuit during carbonite theft crisis reshaped post-Endor guild competition dynamics.",
           events=["Imperial officer service on Chorin", "Cyborg reconstruction after combat injuries", "Enters bounty hunting post-discharge", "Competes in War of the Bounty Hunters", "Pursues Han Solo carbonite puck across sectors"],
           affiliations=["Bounty Hunters' Guild", "Galactic Empire (former officer)", "War of the Bounty Hunters competitors", "Chorin veteran networks", "Cyonotic enhancement clinics", "Han Solo pursuit coalition"],
           timeline=[("Chorin", "Imperial officer career"), ("Injury", "Cyborg reconstruction"), ("Guild Entry", "Hunter reinvention"), ("Carbonite Theft", "Solo puck competition"), ("War of the Bounty Hunters", "Marquee crossover arc")])),
        ("Calo Nord", "Mandalorian Bounty Hunter", "Unknown",
         "Legendary Mandalorian hunter from KOTOR who gunned down targets in cantinas without negotiation.",
         "#0284c7", "KOTOR", "mando",
         L(origin_detail="Calo Nord built legendary KOTOR-era reputation on Taris and beyond as a Mandalorian hunter who ended conversations with blaster fire and counted kills before accepting new contracts.",
           ancient_detail="Mandalorian hunter mercenaries dominated Old Republic Rim markets during Jedi Civil War; Calo represents the era when guild boards on Taris competed with Exchange-backed assassination.",
           modern_detail="Calo Nord remains KOTOR's iconic hunter encounter—players remember his cantina warnings and Taris pursuit as defining bounty hunter gameplay in Old Republic era.",
           conflict_detail="Calo hunted Revan's companions on Taris for Sith bounty, ambushed in Lower City, and exemplified Mandalorian hunter lethality during Jedi Civil War chaos.",
           methods_detail="Dual blasters, Mandalorian armor, no-negotiation policy, and cantina kill counts—Calo Nord warns targets once then fires without further dialogue.",
           reputation_detail="Taris underworld feared his kill-count ritual; Sith paid premium rates; KOTOR-era guild brokers ranked him among top Mandalorian contractors of the Jedi Civil War.",
           impact_detail="Calo Nord defined KOTOR bounty hunter identity for a generation of players; his Taris arc proved hunters could be pivotal antagonists in Old Republic narratives.",
           events=["Builds reputation on Taris bounty boards", "Warns cantina patrons about kill count", "Hunts Revan's party for Sith contract", "Ambush in Taris Lower City", "Defining KOTOR hunter encounter"],
           affiliations=["Bounty Hunters' Guild", "Sith Empire (contracted)", "Mandalorian mercenary tradition", "Taris underworld", "Exchange (adjacent)", "Old Republic hunter markets"],
           timeline=[("Old Republic", "Rise on Taris"), ("Jedi Civil War", "Sith-backed contracts"), ("Taris", "Hunts Revan's companions"), ("Cantina", "Kill-count warnings"), ("Legacy", "KOTOR icon status")])),
        ("Mira", "Bounty Hunter & Scout", "Unknown",
         "Force-sensitive hunter from KOTOR II who redeemed Hanharr and fought Sith Triumvirate on Malachor V.",
         "#94a3b8", "KOTOR II", "human",
         L(origin_detail="Mira was raised on Nar Shaddaa's refugee stacks learning survival scouting before the Exchange posted bounties making her target and hunter simultaneously in KOTOR II's most complex companion arc.",
           ancient_detail="Nar Shaddaa Exchange hunter markets during Jedi Civil War aftermath produced Force-sensitive scouts; Mira represents found-family hunter ethics against Exchange brutality.",
           modern_detail="Mira's redemption of Hanharr and Malachor V assault alongside Meetra Surik made her KOTOR II's moral center—proof hunters can choose light over Exchange blood money.",
           conflict_detail="Mira hunted and was hunted by Hanharr on Nar Shaddaa, joined Surik's crew against Sith Triumvirate, and fought on Malachor V's gravity-wounded surface.",
           methods_detail="Scout tracking, non-lethal preference when possible, explosive traps, and Force sensitivity enhancing intuition—Mira hunts to protect rather than for cruelty.",
           reputation_detail="Exchange brokers frustrated by her ethics; Surik trusted her as crew anchor; Hanharr's redemption attempt defines her among Wookiee-hunter relationships galaxy-wide.",
           impact_detail="Mira's Hanharr redemption arc and Triumvirate role proved Force-sensitive hunters could align with Jedi exile causes without joining the Order.",
           events=["Raised on Nar Shaddaa refugee stacks", "Targeted by Exchange and Hanharr hunts", "Joins Meetra Surik's crew", "Attempts Hanharr redemption", "Fights Sith Triumvirate on Malachor V"],
           affiliations=["Meetra Surik's crew", "Nar Shaddaa Exchange (opposed)", "Hanharr (redemption target)", "KOTOR II hunter scouts", "Malachor V assault force", "Independent Rim brokers"],
           timeline=[("Nar Shaddaa", "Refugee scout upbringing"), ("Exchange", "Target and hunter dual role"), ("Surik Crew", "Joins against Triumvirate"), ("Hanharr", "Redemption attempt"), ("Malachor V", "Triumvirate final battle")])),
    ]
    for spec in hunters:
        _add(*spec)

    from build_bh_hunters_rest3 import register_rest3
    register_rest3(_add, L)
