#!/usr/bin/env python3
"""Part 5 — final 26 bounty hunter entries."""


def register_rest5(_add, L):
    def d(**kw):
        return kw

    final = [
        ("Greef Karga", "Bounty Hunters' Guild Agent", "Nevarro", "Nevarro guild magistrate who posted Din Djarin's Grogu contract before turning ally against Imperial remnant.", "#65a30d", "Mandalorian · Book of Boba Fett", "human",
         d(origin_detail="Greef Karga managed Nevarro's Bounty Hunters' Guild hall as magistrate—posting contracts, collecting fees, and balancing Imperial remnant pressure against hunter independence until Din Djarin broke the Grogu puck.",
           ancient_detail="Nevarro guild halls followed Ord Mantell posting board traditions; Greef represents mid-tier guild bureaucrats who control puck access without hunting themselves.",
           modern_detail="Greef allied with Din Djarin against Moff Gideon's Imperial remnant, became Mos Espa business partner in Book of Boba Fett, and survived guild-to-politics transition.",
           conflict_detail="Greef posted Grogu's Imperial remnant contract, pursued Din for breach, negotiated truce against Gideon, and defended Nevarro from Imperial occupation forces.",
           methods_detail="Guild authority, contract negotiation, armed backup from guild hunters, and political pragmatism—Greef manages hunters rather than leading assaults.",
           reputation_detail="Nevarro hunters answered to Greef; Din Djarin initially obeyed his puck; Imperial remnant tried corrupting him before he chose local survival over Client loyalty.",
           impact_detail="Greef Karga's Grogu contract launched Mandalorian series events; his guild-to-ally arc defined Nevarro's post-Imperial governance model.",
           events=["Manages Nevarro guild hall as magistrate", "Posts Grogu contract for Imperial Client", "Pursues Din Djarin for contract breach", "Allies against Moff Gideon's remnant", "Book of Boba Fett Mos Espa business"],
           affiliations=["Nevarro Bounty Hunters' Guild", "Din Djarin (former employer/ally)", "Moff Gideon's Imperial remnant (former Client)", "Mos Espa commerce", "Guild magistrate authority"],
           timeline=[("Nevarro", "Guild magistrate appointment"), ("Grogu Contract", "Posts Imperial remnant puck"), ("Breach", "Din Djarin defies delivery"), ("Alliance", "Fights Gideon together"), ("Book of Boba Fett", "Mos Espa partner")])),
        ("Rako Hardeen", "Bounty Hunter Identity (Obi-Wan Kenobi)", "Concordia (cover)", "Cover identity Obi-Wan used to infiltrate Moralo Eval's box tournament and foil kidnapping plot.", "#94a3b8", "Clone Wars", "human",
         d(origin_detail="Rako Hardeen was supposedly a deadly bounty hunter whose identity Obi-Wan Kenobi assumed via facial disguise to infiltrate Moralo Eval's box tournament and expose Count Dooku's kidnapping plot.",
           ancient_detail="Undercover Jedi hunter infiltration has precedent in Old Republic intelligence; Hardeen—real or fabricated—served as Clone Wars cover legend for Kenobi's Serenno operation.",
           modern_detail="Obi-Wan's Rako Hardeen disguise fooled Cad Bane and Eval's box competitors, enabling Jedi to thwart Separatist assassin recruitment pipeline.",
           conflict_detail="Kenobi-as-Hardeen survived Eval's box trials on Serenno, earned Cad Bane's grudging respect, and prevented Moralo Eval from delivering kidnapped Chancellor Palpatine to Dooku.",
           methods_detail="Facial disguise, undercover improvisation, Jedi combat hidden behind hunter persona, and box tournament survival—Hardeen identity is performance not profession.",
           reputation_detail="Box competitors feared Hardeen's supposed kill count; Cad Bane tested him repeatedly; only audiences knowing Clone Wars context understand the identity was Obi-Wan Kenobi.",
           impact_detail="Rako Hardeen infiltration foiled Separatist kidnapping plot and demonstrated Jedi could penetrate hunter tournaments—adding intelligence dimension to guild events.",
           events=["Obi-Wan assumes Hardeen identity", "Infiltrates Moralo Eval's box tournament", "Survives Serenno box trials with Cad Bane", "Exposes Count Dooku kidnapping plot", "Prevents Palpatine abduction delivery"],
           affiliations=["Jedi Order (Obi-Wan Kenobi cover)", "Moralo Eval's box roster", "Cad Bane (unwitting competitor)", "Count Dooku plot (opposed)", "Serenno tournament"],
           timeline=[("Cover Creation", "Obi-Wan becomes Hardeen"), ("Box Entry", "Eval tournament infiltration"), ("Serenno", "Survival with Cad Bane"), ("Plot Exposed", "Kidnapping foiled"), ("Legacy", "Jedi undercover hunter legend")])),
        ("Moralo Eval", "Phindian Hunter Mastermind", "Phindar", "Phindian criminal who designed Count Dooku's box gladiator trial to recruit hunter assassins.", "#0891b2", "Clone Wars", "alien",
         d(origin_detail="Moralo Eval, Phindian criminal mastermind, designed the Box gladiator-hunter trial on Serenno for Count Dooku to recruit assassins capable of kidnapping Supreme Chancellor Palpatine.",
           ancient_detail="Phindar's criminal engineer class historically built Separatist trial courses; Eval represents designer-masterminds who weaponize hunter competition for political assassination.",
           modern_detail="Eval's box tournament gathered Cad Bane, Obi-Wan-as-Hardeen, Derrown, Onca, and others in Clone Wars' definitive hunter gladiator event.",
           conflict_detail="Eval ran box trials killing competitors via retractable platforms and environmental traps, tested Cad Bane's crew, and planned Palpatine delivery until Obi-Wan foiled the plot.",
           methods_detail="Trap engineering, psychological testing, platform retraction mechanics, and assassin recruitment screening—Eval designs death courses not personal combat.",
           reputation_detail="Count Dooku funded Eval's box; surviving hunters earned premium assassination contracts; Republic Intelligence studied his trial design after plot exposure.",
           impact_detail="Moralo Eval's box tournament became Clone Wars' defining hunter gladiator event—recruiting assassins through lethal competition rather than guild postings.",
           events=["Designs Box for Count Dooku", "Runs Serenno gladiator-hunter trials", "Recruits Cad Bane and competitors", "Plans Palpatine kidnapping delivery", "Plot foiled by Obi-Wan Kenobi infiltration"],
           affiliations=["Count Dooku / CIS", "Phindian criminal engineers", "Box tournament roster", "Separatist assassin recruitment", "Serenno operations"],
           timeline=[("Phindar", "Criminal mastermind rise"), ("Dooku Contract", "Box design commission"), ("Serenno", "Tournament execution"), ("Recruitment", "Cad Bane selected"), ("Failure", "Kenobi foils kidnapping plot")])),
        ("Chata Hylo", "Pantoran Bounty Hunter", "Pantora", "Pantoran hunter active in High Republic and later eras in extended publishing.", "#65a30d", "Comics · High Republic", "human",
         d(origin_detail="Chata Hylo, Pantoran bounty hunter, operated across High Republic era frontiers where Nihil chaos created unprecedented puck demand for hunters willing to enter hyperspace anomaly zones.",
           ancient_detail="Pantora's diplomatic moon culture produced independent contractors when Republic governance failed Rim sectors; Hylo represents High Republic hunter generation predating Clone Wars guild formalization.",
           modern_detail="Chata Hylo's extended publishing presence connects High Republic hunter markets to later era guild continuity—rare cross-era Pantoran hunter documentation.",
           conflict_detail="Hylo hunted Nihil raiders, protected Rim convoys during High Republic crisis, and navigated frontier zones where Republic judicial authority barely reached.",
           methods_detail="Pantoran cold-tolerance tactics, starship pursuit through anomaly zones, Rim convoy escort flipping to hunt mode, and frontier improvisation.",
           reputation_detail="High Republic era brokers valued Hylo's anomaly-zone experience; Pantoran government noted her independent operations outside diplomatic corps.",
           impact_detail="Chata Hylo links High Republic hunter economy to later guild eras—documenting puck markets during Nihil crisis predating Imperial formalization.",
           events=["Active during High Republic Nihil crisis", "Hunts raiders in hyperspace anomaly zones", "Protects Rim convoy routes", "Pantoran independent contractor role", "Extended publishing cross-era presence"],
           affiliations=["High Republic hunter markets", "Pantora independent contractors", "Nihil crisis responders", "Rim convoy clients", "Bounty Hunters' Guild (proto-era)"],
           timeline=[("High Republic", "Frontier hunter career begins"), ("Nihil Crisis", "Anomaly zone contracts"), ("Pantora", "Independent contractor status"), ("Convoy War", "Escort and hunt dual role"), ("Legacy", "Cross-era publishing link")])),
        ("Synara San", "Warbird Pirate Hunter", "Unknown", "Undercover pirate hunter allied with Kazuda Xiono on Colossus platform.", "#e11d48", "Resistance animated series", "human",
         d(origin_detail="Synara San infiltrated Colossus platform as Warbird pirate spy before allying with Kazuda Xiono—occupying hunter-adjacent undercover space between piracy and Resistance intelligence.",
           ancient_detail="Castilon's Colossus platform hosted smuggler and hunter traffic during New Republic era; Synara represents undercover operatives blurring pirate and hunter identities.",
           modern_detail="Synara's Resistance series arc from Warbird spy to Kaz's ally demonstrated post-Imperial platform politics where hunters and pirates share information economies.",
           conflict_detail="Synara spied for Warbird pirates on Colossus, protected Kaz during First Order occupation, and fought in platform defense when hunter-pirate alliances shifted.",
           methods_detail="Undercover social infiltration, pirate combat skills, platform intelligence, and Kazuda Xiono alliance combat—Synara adapts between spy and fighter roles.",
           reputation_detail="Warbirds trusted her cover; Kaz valued her conversion to ally; Colossus residents remember her as spy who chose platform over pirate masters.",
           impact_detail="Synara San linked Resistance intelligence to platform hunter-pirate economies—showing post-Endor undercover operatives occupy same social space as guild contractors.",
           events=["Infiltrates Colossus as Warbird spy", "Befriends Kazuda Xiono undercover", "Reveals pirate allegiance under pressure", "Allies with Kaz against First Order", "Defends Colossus platform"],
           affiliations=["Warbird pirates (former)", "Kazuda Xiono / Resistance", "Colossus platform residents", "First Order (opposed)", "Undercover intelligence networks"],
           timeline=[("Warbird Cover", "Spy infiltration begins"), ("Colossus", "Kaz friendship develops"), ("Reveal", "Pirate allegiance exposed"), ("Alliance", "Joins platform defense"), ("First Order", "Occupation resistance")])),
        ("Ketsu Onyo", "Black Sun Bounty Hunter", "Shukut", "Former Black Sun enforcer turned Rebel-allied hunter partnered with Sabine Wren on Lothal.", "#991b1b", "Rebels", "twilek",
         d(origin_detail="Ketsu Onyo trained with Sabine Wren at Mandalorian Imperial Academy before becoming Black Sun enforcer; she later reconciled with Sabine and aided Rebel cell operations on Lothal.",
           ancient_detail="Shukut Twi'lek hunter traditions and Black Sun enforcer pipelines predate Ketsu; Mandalorian Academy dropout hunters represent Imperial training turned syndicate service.",
           modern_detail="Ketsu's Rebels arc from Sabine's estranged partner to Rebel ally showcased Twi'lek hunter redemption alongside Mandalorian revolutionary politics on Lothal.",
           conflict_detail="Ketsu hunted Sabine for Black Sun before reconciliation, ambushed Ghost crew shipments, then helped Sabine steal fuel for Lothal rebellion and fought Imperial blockade.",
           methods_detail="Twi'lek agility, Black Sun tactics, starship interdiction with Shadow Caster, and Mandalorian Academy-trained combat—Ketsu combines syndicate brutality with formal training.",
           reputation_detail="Black Sun valued Ketsu's Sabine connection; Rebels celebrated her reconciliation; Lothal cells trusted her after fuel heist alliance.",
           impact_detail="Ketsu Onyo's Sabine reconciliation arc proved Black Sun enforcers could defect to Rebellion—linking syndicate hunter markets to revolutionary cause.",
           events=["Trains with Sabine at Mandalorian Academy", "Joins Black Sun as enforcer", "Hunts Sabine and Ghost crew", "Reconciles and aids Lothal rebellion", "Shadow Caster fuel heist alliance"],
           affiliations=["Black Sun (former)", "Sabine Wren partnership", "Lothal Rebel cell", "Shadow Caster crew", "Mandalorian Academy (dropout)"],
           timeline=[("Academy", "Sabine friendship and fallout"), ("Black Sun", "Enforcer service"), ("Hunt", "Pursues Sabine for syndicate"), ("Reconciliation", "Rebel alliance restored"), ("Lothal", "Fuel heist for rebellion")])),
        ("Sabine Wren", "Mandalorian Bounty Past", "Krownest", "Mandalorian artist-warrior who briefly took guild contracts before joining Phoenix Squadron.", "#e11d48", "Rebels · Clone Wars", "mando",
         d(origin_detail="Sabine Wren, Mandalorian artist-warrior from Clan Wren, briefly operated in bounty-adjacent mercenary space before joining Phoenix Squadron as Ghost crew weapons expert and Rebel propagandist.",
           ancient_detail="Clan Wren's Krownest traditions combine art and combat; Sabine represents Mandalorian warriors who reject guild long-term but retain hunter tactical skills in Rebel service.",
           modern_detail="Sabine's Rebels arc from Imperial Academy dropout to Mandalore liberator connects brief hunter-adjacent past to full revolutionary Mandalorian leadership against Empire.",
           conflict_detail="Sabine fought Imperials on Lothal, reclaimed Darksaber significance, reunited with Ketsu Onyo, and led Mandalore liberation from Imperial occupation post-Endor.",
           methods_detail="Graffiti propaganda, explosives expertise, Mandalorian jetpack combat, and Darksaber training—Sabine weaponizes art and hunter skills for Rebellion.",
           reputation_detail="Ghost crew trusted her completely; Ketsu Onyo reconciled with her; Mandalore recognized her as liberator; Imperial governors feared her propaganda bombs.",
           impact_detail="Sabine Wren proved Mandalorian hunter skills transfer to Rebel operations—brief guild-adjacent past shaped full revolutionary arc and Mandalore's future.",
           events=["Imperial Academy training with Ketsu", "Joins Ghost crew / Phoenix Squadron", "Brief bounty-adjacent mercenary work", "Reclaims Darksaber cultural role", "Leads Mandalore liberation post-Endor"],
           affiliations=["Clan Wren", "Ghost crew / Phoenix Squadron", "Ketsu Onyo (partner)", "Lothal Rebel cell", "Mandalorian resistance", "Rebel Alliance"],
           timeline=[("Krownest", "Clan Wren upbringing"), ("Academy", "Imperial training; dropout"), ("Ghost Crew", "Rebel weapons expert"), ("Lothal", "Platform liberation fight"), ("Mandalore", "Post-Endor liberation leader")])),
        ("Cato Parasitti", "Clawdite Bounty Hunter", "Zolan", "Clawdite infiltrator who impersonated Jedi librarian Jocasta Nu during holocron heist.", "#0891b2", "Clone Wars", "alien",
         d(origin_detail="Cato Parasitti, Clawdite shapeshifter, infiltrated Jedi Temple disguised as librarian Jocasta Nu during Cad Bane's holocron heist—specializing in identity theft over combat.",
           ancient_detail="Zolan Clawdite infiltration specialists served Separatist intelligence for decades; Cato represents shapeshifter hunters who win through disguise before blaster fire.",
           modern_detail="Cato's Jedi Temple impersonation enabled Cad Bane's holocron theft—one of Clone Wars' boldest hunter-intelligence operations against Jedi Order.",
           conflict_detail="Cato maintained Jocasta Nu disguise inside Jedi Temple, assisted Bane's vault breach, and demonstrated Clawdite infiltration could penetrate Order's most sacred archives.",
           methods_detail="Clawdite shapeshifting, voice mimicry, behavioral study of impersonation targets, and intelligence support for Cad Bane's combat team.",
           reputation_detail="Cad Bane trusted Cato's infiltration skills; Jedi discovered impersonation post-heist; Clawdite guilds cite Temple job as masterwork infiltration.",
           impact_detail="Cato Parasitti's Temple infiltration forced Jedi to upgrade identity verification—proving shapeshifter hunters are intelligence threats not just assassins.",
           events=["Hired by Cad Bane for Temple heist", "Impersonates Jedi librarian Jocasta Nu", "Assists holocron vault breach", "Maintains cover during Bane operation", "Clawdite infiltration masterwork"],
           affiliations=["Cad Bane gang", "Clawdite infiltrator networks", "Count Dooku / CIS (contracted)", "Jedi Temple (infiltrated)", "Separatist intelligence"],
           timeline=[("Zolan", "Clawdite infiltration training"), ("Bane Contract", "Temple heist recruitment"), ("Impersonation", "Jocasta Nu disguise"), ("Vault", "Holocron theft support"), ("Legacy", "Jedi security upgrade catalyst")])),
        ("Derrown", "Parwan Bounty Hunter", "Parwan", "Parwan sniper alchemist who competed in Moralo Eval's box on Serenno.", "#65a30d", "Clone Wars", "alien",
         d(origin_detail="Derrown, a Parwan sniper-alchemist, competed in Moralo Eval's box tournament using toxic gas chemistry and long-range precision—representing Parwan's unique hunter-scientist tradition.",
           ancient_detail="Parwan's ammonia-atmosphere alchemists produced toxin specialists for Rim mercenary markets; Derrown brings chemical warfare to hunter gladiator competitions.",
           modern_detail="Derrown's box performance alongside Cad Bane and Onca showcased Parwan hunter-alchemists in Clone Wars' deadliest tournament environment.",
           conflict_detail="Derrown survived multiple box trial stages using gas attacks and sniper overwatch until Eval's retractable platforms eliminated weaker competitors.",
           methods_detail="Toxic gas synthesis, long-range sniper shots, atmospheric chemistry exploiting competitor weaknesses, and Parwan biological toxin resistance.",
           reputation_detail="Box competitors feared Derrown's gas clouds; Eval ranked him among top technical specialists; Parwan clans celebrate his tournament representation.",
           impact_detail="Derrown validated Parwan alchemist-hunter hybrid class in guild gladiator events—chemical warfare as legitimate hunter methodology.",
           events=["Enters Moralo Eval's box tournament", "Deploys toxic gas against competitors", "Sniper overwatch on Serenno trials", "Survives multiple box stages", "Parwan alchemist-hunter showcase"],
           affiliations=["Moralo Eval's box roster", "Parwan alchemist tradition", "Cad Bane tournament peers", "Separatist assassin pipeline", "Bounty Hunters' Guild"],
           timeline=[("Parwan", "Alchemist-sniper training"), ("Box Entry", "Eval tournament recruitment"), ("Serenno", "Gas and sniper trials"), ("Survival", "Multiple stage advancement"), ("Legacy", "Parwan hunter archetype")])),
        ("IG-11", "Nurse Droid Turned Hunter", "Unknown manufacture", "Assassin droid reprogrammed to protect Grogu after Nevarro guild contract went sideways.", "#65a30d", "Mandalorian", "droid",
         d(origin_detail="IG-11 was an assassin droid activated for Greef Karga's Grogu contract on Nevarro; after Din Djarin destroyed and Kuiil reprogrammed him, IG-11 became Grogu's nurse-droid protector until sacrificing himself against Imperial forces.",
           ancient_detail="Assassin droid reprogramming traditions on Nevarro follow Nar Shaddaa modification culture; IG-11's nurse protocol inversion mirrors 4-LOM's hunter rewiring generations earlier.",
           modern_detail="IG-11's Mandalorian arc from hunter to protector to sacrificial hero defined droid character depth and launched Grogu protection narrative alongside Din Djarin.",
           conflict_detail="IG-11 fought Din Djarin as assassin, served Kuiil's reprogramming on Nevarro, nursed Grogu, and self-destructed holding off Imperial remnant troopers for crew escape.",
           methods_detail="Assassin droid precision (pre-reprogram), nurse protocol caregiving (post-reprogram), self-destruct sacrificial combat—IG-11's methods transformed entirely mid-arc.",
           reputation_detail="Greef Karga deployed IG-11 as reliable assassin; Kuiil trusted his reprogramming; Din honored IG-11's sacrifice; Nevarro remembers him as Grogu's protector droid.",
           impact_detail="IG-11's sacrifice enabled Din Djarin and Grogu to escape Nevarro—catalyzing Mandalorian series central relationship and droid hunter reprogramming theme.",
           events=["Activated for Grogu assassin contract", "Fights Din Djarin on Nevarro", "Reprogrammed by Kuiil as nurse droid", "Protects Grogu from Imperial forces", "Self-destructs enabling crew escape"],
           affiliations=["Nevarro Bounty Hunters' Guild (contracted)", "Kuiil reprogramming", "Din Djarin (former target/ally)", "Grogu protection detail", "Imperial remnant (opposed)"],
           timeline=[("Activation", "Grogu assassin contract"), ("Nevarro Fight", "Battles Din Djarin"), ("Reprogramming", "Kuiil nurse protocol"), ("Protection", "Grogu nurse droid"), ("Sacrifice", "Self-destruct for escape")])),
    ]
    for e in final:
        _add(*e)

    from build_bh_hunters_rest6 import register_rest6
    register_rest6(_add, L)
