#!/usr/bin/env python3
"""Part 3 bounty hunter entries — remaining 46 hunters."""


def register_rest3(_add, L):
    specs = [
        ("Hanharr", "Wookiee Bounty Hunter", "Kashyyyk", "Bloodthirsty Wookiee hunter enslaved by Exchange who hunted Mira across Nar Shaddaa.", "#991b1b", "KOTOR II", "wookiee",
         dict(origin_detail="Hanharr was a bloodthirsty Wookiee enslaved by Nar Shaddaa Exchange bosses who weaponized his honor code against fellow Wookiee captives, making him Mira's relentless pursuer.",
              ancient_detail="Exchange Wookiee enslavement on Nar Shaddaa predates Hanharr; KOTOR-era records document honor-broken Wookiees used as hunter-killers against escaped refugees.",
              modern_detail="Hanharr's KOTOR II arc with Mira offered redemption or death—his fate defines whether Exchange corruption can be broken or only survived.",
              conflict_detail="Hanharr hunted Mira across Nar Shaddaa vertical city, served Exchange enforcement, and joined or opposed Surik's crew depending on player choices on Malachor V.",
              methods_detail="Wookiee brute strength, bowcaster violence, honor-code manipulation by Exchange handlers, and relentless pursuit—Hanharr prefers killing targets over capture.",
              reputation_detail="Exchange valued his terror; Mira feared and pitied him; Nar Shaddaa refugees whisper his name as Exchange enforcement symbol.",
              impact_detail="Hanharr's Mira pursuit exemplifies Exchange hunter cruelty; his redemption possibility made KOTOR II's hunter ethics uniquely complex.",
              events=["Enslaved by Nar Shaddaa Exchange", "Hunts Mira across vertical city", "Serves Exchange enforcement contracts", "Confrontation with Meetra Surik's crew", "Redemption or death on Malachor path"],
              affiliations=["Nar Shaddaa Exchange", "Mira (hunt target)", "Meetra Surik's crew (conditional)", "Kashyyyk exile status", "Exchange enforcement"],
              timeline=[("Kashyyyk", "Honor before enslavement"), ("Exchange", "Enslaved as hunter"), ("Nar Shaddaa", "Mira pursuit"), ("Surik Crew", "Conditional alliance"), ("Malachor V", "Final confrontation")])),
        ("Durge", "Gen'Dai Bounty Hunter", "Unknown (Gen'Dai)", "Ancient Gen'Dai warrior who fought Jedi across centuries including Clone Wars massacres.", "#0891b2", "Clone Wars · comics", "alien",
         dict(origin_detail="Durge is an ancient Gen'Dai mercenary whose regenerative biology let him fight Jedi across centuries, selling his immortality to Separatists as living siege weapon during Clone Wars.",
              ancient_detail="Gen'Dai longevity predates the Republic; Durge fought Mandalorians in ancient wars and was sealed in prison until Separatists freed him for Jedi-killing contracts.",
              modern_detail="Durge's Clone Wars massacres against clone troopers and Jedi made him among the war's most terrifying non-Force combatants before his apparent destruction.",
              conflict_detail="Durge slaughtered clone units, fought Obi-Wan Kenobi and Ventress, and served Count Dooku as Gen'Dai enforcer until explosive defeats could not permanently kill his regenerating form.",
              methods_detail="Regenerative Gen'Dai biology, heavy armor, flamethrowers, spears, and vehicular assault—Durge absorbs damage that would kill organic hunters and keeps fighting.",
              reputation_detail="Clone troopers feared Durge's name in briefing; Jedi noted his ancient Mandalorian war stories; Separatists paid premium for his Jedi-killing reputation.",
              impact_detail="Durge proved ancient Gen'Dai mercenaries could match Jedi in open battle; his Clone Wars rampage forced Republic tactical doctrine updates for hunter-class threats.",
              events=["Freed from ancient prison by Separatists", "Massacres clone trooper units", "Fights Obi-Wan Kenobi repeatedly", "Serves Count Dooku as enforcer", "Apparent destruction in Clone Wars"],
              affiliations=["Count Dooku / CIS (contracted)", "Gen'Dai mercenary tradition", "Separatist military", "Ancient Mandalorian war legacy", "Jedi-killing specialist market"],
              timeline=[("Ancient Era", "Fights Mandalorians; imprisoned"), ("Release", "Separatists free Durge"), ("Clone Wars", "Jedi and clone massacres"), ("Dooku Service", "Separatist enforcer"), ("Destruction", "Regenerative defeat")])),
        ("Montross", "Mandalorian Bounty Hunter", "Mandalore", "Rival Mandalorian hunter to Jango Fett in Bounty Hunter game; broken by guild politics.", "#0284c7", "Bounty Hunter game · legends", "mando",
         dict(origin_detail="Montross was Jango Fett's Mandalorian rival who lost a duel for leadership and turned guild hunter, competing for the same contracts that defined Jango's rise on Mandalore.",
              ancient_detail="Mandalorian hunter rivalry traditions mirror KOTOR Neo-Crusader internal contests; Montross represents guild politics where defeat means exile into bounty markets.",
              modern_detail="Montross's Bounty Hunter game role as Jango antagonist made him iconic gaming-era Mandalorian hunter rival alongside live-action Fett canon.",
              conflict_detail="Montross competed with Jango for Mandalorian authority, hunted across game narrative worlds, and embodied broken honor pursuing credits over Creed.",
              methods_detail="Heavy Mandalorian armor, brutal close combat, rocket launchers, and psychological warfare against Jango—Montross fights like a warlord not a tracker.",
              reputation_detail="Mandalorian clans remember Montross as cautionary rival; gaming-era guild archives rank him second to Jango in pre-Clone Wars hunter tier lists.",
              impact_detail="Montross defined Mandalorian hunter rivalry in Bounty Hunter game narrative; his Jango opposition explored honor failure in Mandalorian mercenary culture.",
              events=["Rival duel with Jango Fett on Mandalore", "Exiled into bounty hunting", "Competes for guild premium contracts", "Antagonist in Bounty Hunter game arc", "Embodies broken Mandalorian honor"],
              affiliations=["Mandalorian clans (exiled)", "Bounty Hunters' Guild", "Jango Fett rivalry", "Mandalore hunter markets", "Legends gaming continuity"],
              timeline=[("Mandalore", "Rivalry with Jango"), ("Duel Loss", "Exile to hunting"), ("Guild Era", "Premium contract competition"), ("Game Arc", "Bounty Hunter antagonist"), ("Legacy", "Mandalorian rival icon")])),
        ("Robonino", "Patrolian Saboteur Hunter", "Patrolia", "Aquatic saboteur who worked with Cad Bane on Senate hostage extraction.", "#0891b2", "Clone Wars", "alien",
         dict(origin_detail="Robonino, a Patrolian aquatic saboteur, specialized in disabling power grids and security systems—skills Cad Bane leveraged for the Galactic Senate hostage crisis.",
              ancient_detail="Patrolia's aquatic engineers supplied sabotage specialists to Rim corporations; Clone Wars Separatist rolls recruited them for infrastructure attacks.",
              modern_detail="Robonino's Senate power-grid sabotage alongside Cad Bane remains a case study in hunter-engineer hybrid roles within guild team operations.",
              conflict_detail="Robonino disabled Coruscant Senate building power during Cad Bane's hostage operation, enabling hunter gang control of Galactic Senate chamber.",
              methods_detail="Electrical sabotage, aquatic mobility in flooded zones, security system bypass, and team coordination with Cad Bane's gunslingers.",
              reputation_detail="Cad Bane trusted Robonino for Senate job; Republic engineers studied his sabotage patterns; Patrolian diaspora cites him in technical hunter recruitment.",
              impact_detail="Robonino's Senate sabotage proved engineer-hunters could disable planetary government infrastructure—a Republic security wake-up call.",
              events=["Recruited by Cad Bane for Senate operation", "Sabotages Senate building power grid", "Enables hostage crisis in chamber", "Evades Coruscant security response", "Patrolian saboteur reputation established"],
              affiliations=["Cad Bane gang", "Count Dooku / CIS (contracted)", "Patrolian engineer diaspora", "Separatist sabotage rolls", "Coruscant infrastructure targets"],
              timeline=[("Patrolia", "Aquatic saboteur training"), ("Cad Bane Gang", "Joins elite crew"), ("Senate Crisis", "Power grid sabotage"), ("Hostage Op", "Chamber control enabled"), ("Legacy", "Engineer-hunter archetype")])),
        ("C-21 Highsinger", "Assassin Droid Bounty Hunter", "Unknown manufacture", "Droid mercenary in Sugi's crew with heavy weapons specialization on Felucia.", "#65a30d", "Clone Wars", "droid",
         dict(origin_detail="C-21 Highsinger was an assassin droid mercenary Sugi recruited for heavy weapons support—providing firepower Embo's silence and Rumi's sniper overwatch couldn't deliver on Felucia.",
              ancient_detail="Assassin droid mercenary markets on Nar Shaddaa supplied Clone Wars crew hunters; Highsinger represents droid squad integration predating IG-11's Mandalorian arc.",
              modern_detail="Highsinger's Felucia deployment with Sugi's crew demonstrated droid heavy-weapons specialists in farmer-defense contracts against Hondo Ohnaka's pirates.",
              conflict_detail="Highsinger fought Hondo's pirate assault on Felucian nerf herders, providing suppressive fire while Sugi coordinated ground defense and Embo flanked attackers.",
              methods_detail="Heavy repeating blasters, droid durability, squad fire support, and mercenary programming—Highsinger delivers volume of fire over precision.",
              reputation_detail="Sugi relied on Highsinger for pirate battles; guild brokers note droid heavy-gunners as cost-effective crew additions for Rim defense contracts.",
              impact_detail="C-21 Highsinger validated droid heavy-weapons roles in hunter mercenary crews—a template for later Mandalorian-era assassin droid contracts.",
              events=["Recruited into Sugi's mercenary crew", "Deploys on Felucian farmer defense", "Provides heavy fire against Hondo's pirates", "Supports Embo and Rumi Paramita", "Droid mercenary crew model"],
              affiliations=["Sugi's mercenary crew", "Bounty Hunters' Guild", "Felucian defense contract", "Embo partnership (crew)", "Assassin droid manufacturing"],
              timeline=[("Recruitment", "Joins Sugi's crew"), ("Felucia", "Farmer defense deployment"), ("Pirate Battle", "Heavy weapons support"), ("Crew Ops", "Mercenary fire team"), ("Legacy", "Droid crew gunner model")])),
        ("Latts Razzi", "Theelin Bounty Hunter", "Unknown", "Theelin hunter in young Boba Fett's Clone Wars crew alongside Bossk and Aurra Sing.", "#65a30d", "Clone Wars", "alien",
         dict(origin_detail="Latts Razzi, a Theelin hunter, joined young Boba Fett's Clone Wars crew bringing starship piloting and underworld connections alongside Bossk's strength and Aurra Sing's sniper work.",
              ancient_detail="Theelin diaspora on Nar Shaddaa produced pilot-hunter hybrids; Latts represents crew specialists who handle transport while lead hunters pursue targets.",
              modern_detail="Latts survived Aurra Sing's crew purges longer than Castas, demonstrating Theelin adaptability in volatile young Boba operations.",
              conflict_detail="Latts flew Boba's crew missions during revenge operations against Jedi, navigated Separatist-adjacent space, and survived internal crew violence when Aurra eliminated weak links.",
              methods_detail="Starship piloting, crew logistics, blaster backup, and underworld negotiation—Latts keeps the crew moving while Bossk and Aurra handle violence.",
              reputation_detail="Young Boba depended on Latts for transport; Bossk respected her pilot skills; guild cadets study Boba's crew as cautionary team dynamics lesson.",
              impact_detail="Latts Razzi's crew role showed hunter operations require pilots and logistics specialists—not every guild member needs to be front-line killer.",
              events=["Joins young Boba Fett's crew", "Pilots missions against Jedi targets", "Survives Aurra Sing's crew purges", "Works alongside Bossk and Castas", "Theelin crew specialist model"],
              affiliations=["Young Boba Fett crew", "Bossk partnership", "Aurra Sing crew (former)", "Bounty Hunters' Guild", "Theelin pilot networks"],
              timeline=[("Crew Join", "Young Boba's team"), ("Pilot Ops", "Revenge mission transport"), ("Internal Conflict", "Aurra's purges"), ("Survival", "Outlasts Castas"), ("Legacy", "Crew pilot archetype")])),
        ("Castas", "Klatooinian Bounty Hunter", "Klatooine", "Klatooinian crew member of young Boba who died when Aurra Sing eliminated weak links.", "#65a30d", "Clone Wars", "alien",
         dict(origin_detail="Castas, a Klatooinian hunter, joined young Boba Fett's crew but lacked Aurra Sing's discipline—his complaints about risk led Aurra to eliminate him as crew weak link.",
              ancient_detail="Klatooinian servitude traditions to Hutt masters historically produced hunter-enforcers; Castas broke pattern by joining independent crew under Boba.",
              modern_detail="Castas's death by Aurra Sing became defining example of Boba crew's volatile internal politics and the cost of complaining about elite hunter leadership.",
              conflict_detail="Castas participated in young Boba's Clone Wars operations until his dissent prompted Aurra Sing to kill him—demonstrating crew survival required silence and competence.",
              methods_detail="Standard blaster work, crew support roles, and Klatooinian physical durability—Castas had adequate skills but poor judgment about crew politics.",
              reputation_detail="Aurra considered him expendable; Boba learned crew management from his death; Klatooinian hunters cite Castas as politics-over-skill cautionary tale.",
              impact_detail="Castas's elimination showed young Boba's crew operated by predator rules—not guild bureaucracy—and shaped Boba's later preference for solo or elite partnerships.",
              events=["Joins young Boba Fett's crew", "Participates in Clone Wars hunt ops", "Complains about mission risk to Aurra Sing", "Killed by Aurra as weak link", "Cautionary crew politics lesson"],
              affiliations=["Young Boba Fett crew", "Aurra Sing (killer)", "Bossk partnership (crew)", "Klatooine hunter diaspora", "Bounty Hunters' Guild"],
              timeline=[("Crew Join", "Young Boba's team"), ("Operations", "Clone Wars hunt missions"), ("Dissent", "Complains about risk"), ("Death", "Aurra Sing eliminates him"), ("Legacy", "Crew politics warning")])),
        ("Rumi Paramita", "Pa'lowick Bounty Hunter", "Lowick", "Pa'lowick sniper in Sugi's mercenary crew killed defending Felucian farmers.", "#65a30d", "Clone Wars", "alien",
         dict(origin_detail="Rumi Paramita, a Pa'lowick sniper from Lowick, joined Sugi's mercenary crew providing long-range overwatch for Felucian nerf-herder defense contracts against pirate threats.",
              ancient_detail="Pa'lowick musical and hunting traditions from Lowick produce sniper-specialists; Rumi represents Rim species joining multi-species mercenary crews for farmer-defense work.",
              modern_detail="Rumi's death defending Felucian farmers against Hondo Ohnaka's pirates made her Clone Wars sacrifice emblematic of hunter crews protecting Rim civilians.",
              conflict_detail="Rumi held sniper positions during Hondo's Felucia assault until overwhelming pirate numbers killed her—buying time for Embo and Sugi to organize counterattack.",
              methods_detail="Pa'lowick sniper rifle expertise, elevated overwatch positions, and crew coordination with Embo's close combat—Rumi covers approaches while allies engage.",
              reputation_detail="Felucian farmers mourned Rumi by name; Sugi's crew honored her sacrifice; Pa'lowick clans remember her farmer-defense death as honor.",
              impact_detail="Rumi Paramita's Felucia death proved hunter crews could die defending Rim civilians—not just hunting for Hutt credits—shaping Sugi crew legacy.",
              events=["Joins Sugi's mercenary crew as sniper", "Deploys on Felucian farmer defense", "Provides overwatch against Hondo's pirates", "Killed during Felucia assault", "Honored as farmer-defense martyr"],
              affiliations=["Sugi's mercenary crew", "Embo partnership (crew)", "Felucian farmer clients", "Pa'lowick sniper tradition", "Bounty Hunters' Guild"],
              timeline=[("Lowick", "Pa'lowick sniper training"), ("Crew Join", "Sugi's mercenaries"), ("Felucia", "Farmer defense contract"), ("Battle", "Overwatch against pirates"), ("Death", "Falls defending farmers")])),
        ("Jas Emari", "Zabrak Bounty Hunter", "Iridonia", "New Republic-era Zabrak hunter from Aftermath novels who hunted Imperials and joined Han's crew.", "#e11d48", "Aftermath novels", "zabrak",
         dict(origin_detail="Jas Emari, a Zabrak hunter from Iridonia, built New Republic-era reputation hunting Imperial holdouts before joining Han Solo's Aftermath crew for Battle of Jakku operations.",
              ancient_detail="Iridonia Zabrak hunters served Old Republic mercenary markets; Jas represents post-Endor generation turning guild skills toward Imperial remnant elimination.",
              modern_detail="Jas Emari's Aftermath trilogy role hunting Imperials with Han Solo connected bounty hunting to New Republic military operations during Jakku campaign.",
              conflict_detail="Jas hunted Imperial warlords across Outer Rim, joined Han's team against Rae Sloane's forces, and fought in New Republic transition battles post-Endor.",
              methods_detail="Zabrak combat training, starship pursuit of Imperial fugitives, crew coordination with New Republic allies, and Iridonia tactical discipline.",
              reputation_detail="New Republic recruiters valued Jas's Imperial-hunting record; Han Solo trusted her in Aftermath operations; Iridonia clans celebrated her anti-Imperial contracts.",
              impact_detail="Jas Emari linked bounty hunting to New Republic founding narrative—hunters as military auxiliaries against Imperial remnant rather than purely criminal contractors.",
              events=["Builds Imperial-hunting reputation post-Endor", "Joins Han Solo's Aftermath crew", "Hunts Imperial warlords on Outer Rim", "Participates in Battle of Jakku operations", "New Republic-era Zabrak hunter icon"],
              affiliations=["Han Solo's Aftermath crew", "New Republic (allied)", "Iridonia Zabrak networks", "Bounty Hunters' Guild", "Imperial remnant targets"],
              timeline=[("Post-Endor", "Imperial-hunting contracts"), ("Aftermath", "Joins Han's crew"), ("Outer Rim", "Warlord pursuit"), ("Jakku", "Battle operations"), ("Legacy", "New Republic hunter auxiliaries")])),
        ("Nakano Lash", "Nautolan Bounty Hunter", "Glee Anselm", "Nautolan hunter whose betrayal triggered War of the Bounty Hunters comic crossover.", "#65a30d", "Comics · War of the Bounty Hunters", "nautolan",
         dict(origin_detail="Nakano Lash, a Nautolan hunter from Glee Anselm, built guild reputation before her betrayal of Han Solo's carbonite handoff triggered the War of the Bounty Hunters crossover crisis.",
              ancient_detail="Nautolan Force-sensitive hunter traditions from Glee Anselm occasionally produce guild contractors; Lash represents amphibious species in Core hunter markets.",
              modern_detail="Nakano Lash's carbonite betrayal made her central figure in Marvel's War of the Bounty Hunters—reshaping post-Endor hunter competition for Solo's frozen body.",
              conflict_detail="Lash manipulated carbonite transfer logistics, betrayed partners in Solo puck chase, and forced Boba Fett, Valance, and dozens of hunters into open competition.",
              methods_detail="Nautolan tactical intuition, underwater infiltration skills, carbonite logistics expertise, and betrayal as strategic weapon—Lash plays long games.",
              reputation_detail="Guild brokers blacklisted her post-betrayal; War of the Bounty Hunters hunters hunted her in return; Nautolan diaspora divided on her legacy.",
              impact_detail="Nakano Lash's betrayal catalyzed War of the Bounty Hunters—the largest post-Endor hunter crossover event in comics continuity.",
              events=["Builds Nautolan hunter reputation", "Involved in Han Solo carbonite logistics", "Betrayal triggers hunter war", "Pursued by Boba Fett and Valance", "Central War of the Bounty Hunters figure"],
              affiliations=["Bounty Hunters' Guild", "War of the Bounty Hunters coalition", "Glee Anselm Nautolan networks", "Han Solo carbonite chain", "Betrayal target of peer hunters"],
              timeline=[("Glee Anselm", "Nautolan hunter rise"), ("Carbonite", "Solo logistics involvement"), ("Betrayal", "Triggers hunter war"), ("Crossover", "War of the Bounty Hunters"), ("Legacy", "Post-Endor guild crisis")])),
    ]
    for s in specs:
        _add(*s)

    from build_bh_hunters_rest4 import register_rest4
    register_rest4(_add, L)
