#!/usr/bin/env python3
"""Part 4 — final 36 bounty hunter entries."""


def register_rest4(_add, L):
    def d(**kw):
        return kw

    entries = [
        ("T'onga", "Mimbanese Bounty Hunter", "Mimban", "Mimbanese hunter seeking brother T'ongor; stars in Bounty Hunters Marvel series.", "#65a30d", "Comics · War of the Bounty Hunters", "human",
         d(origin_detail="T'onga left Mimban's fog warfare culture hunting bounties across the galaxy while searching for her brother T'ongor, whose disappearance drove her into Marvel's Bounty Hunters series lead role.",
           ancient_detail="Mimban's swamp combat traditions produced mercenary scouts for Old Republic frontier wars; T'onga represents Mimbanese hunters in post-Endor comics continuity.",
           modern_detail="T'onga's Marvel Bounty Hunters series made her marquee post-Endor hunter alongside Nakano Lash and Valance in War of the Bounty Hunters aftermath.",
           conflict_detail="T'onga pursued brother-related conspiracies, competed in post-Endor guild markets, and navigated Imperial remnant threats while building independent hunter crew.",
           methods_detail="Mimbanese swamp-combat training, starship pursuit, crew leadership, and persistence tracking—T'onga hunts for family not just credits.",
           reputation_detail="Marvel series positioned T'onga as lead hunter protagonist; Mimbanese diaspora celebrates her representation in Core hunter publishing.",
           impact_detail="T'onga expanded Mimbanese hunter visibility and anchored Marvel's Bounty Hunters ongoing series in post-Endor guild politics.",
           events=["Leaves Mimban for galactic hunting", "Searches for brother T'ongor", "Leads Marvel Bounty Hunters series", "Navigates War of the Bounty Hunters aftermath", "Builds independent hunter crew"],
           affiliations=["Marvel Bounty Hunters crew", "Bounty Hunters' Guild", "Mimbanese diaspora", "T'ongor search network", "Post-Endor hunter markets"],
           timeline=[("Mimban", "Swamp warrior origins"), ("Brother Search", "T'ongor disappearance"), ("Guild Career", "Galactic hunting rise"), ("Marvel Series", "Lead protagonist role"), ("Post-War", "Independent crew leader")])),
        ("Doctor Aphra", "Archaeologist Thief (Hunter Adjacent)", "Unknown", "Rogue archaeologist who hires hunters and operates with Black Krrsantan on artifact heists.", "#991b1b", "Comics · Doctor Aphra", "human",
         d(origin_detail="Chelli Lona Aphra, rogue archaeologist, operates adjacent to bounty hunting—employing Black Krrsantan and running heists that require hunter muscle, Imperial evasion, and tomb raiding in equal measure.",
           ancient_detail="Old Republic archaeologist-thief guilds on Nar Shaddaa blurred lines between hunter and looter; Aphra revives that tradition with doctoral credentials and zero ethics.",
           modern_detail="Doctor Aphra's comics series made her central to post-Endor artifact black markets where hunters like Krrsantan provide violence Aphra's intellect cannot.",
           conflict_detail="Aphra stole Sith artifacts, evaded Darth Vader's personal pursuit, partnered Krrsantan against Triple-Zero and BT-1, and navigated Imperial and Rebel hunter-adjacent chaos.",
           methods_detail="Archaeological expertise, social manipulation, droid specialists, and Krrsantan's brute force—Aphra hires hunters rather than holding puck herself.",
           reputation_detail="Imperial Intelligence flagged Aphra as priority; Krrsantan stayed for credits and chaos; hunters guild brokers treat her jobs as high-risk high-reward.",
           impact_detail="Doctor Aphra expanded hunter-adjacent work into archaeological mercenary space—proving puck economy extends to artifact extraction and tomb raiding.",
           events=["Steals Sith artifacts from Vader's reach", "Partners Black Krrsantan on heists", "Evades Darth Vader personal pursuit", "Leads Doctor Aphra comics series", "Operates artifact black markets"],
           affiliations=["Black Krrsantan crew", "Archaeological black market", "Triple-Zero and BT-1 (former)", "Imperial Intelligence (fugitive)", "Sith artifact networks"],
           timeline=[("Academic Fall", "Ethics abandonment"), ("Vader Era", "Artifact theft spree"), ("Krrsantan", "Hunter partnership"), ("Comics Lead", "Doctor Aphra series"), ("Black Market", "Artifact mercenary queen")])),
        ("Ochi of Bestoon", "Sith Assassin Hunter", "Bestoon", "Bestoon assassin who hunted Sith wayfinders for Palpatine on Exegol mission.", "#64748b", "Rise of Skywalker · comics", "alien",
         d(origin_detail="Ochi of Bestoon served Palpatine's Sith Eternal as assassin-hunter tasked with locating Sith wayfinders and eliminating anyone guarding Exegol's secrets—including Rey's parents.",
           ancient_detail="Bestoon assassin clans supplied Sith cult operations for generations; Ochi represents Final Order-era hunter-assassins serving dark side cults beyond Imperial bureaucracy.",
           modern_detail="Ochi's pursuit of Rey's parents on Jakku and his poisoned blade death on Pasaana made him key Rise of Skywalker hunter antagonist in comics and film.",
           conflict_detail="Ochi hunted Sith wayfinder clues across Jakku and Pasaana, killed Rey's guardian Ochi-targeted victims, and died in acid pool during wayfinder pursuit.",
           methods_detail="Bestoon assassin blades, Sith cult intelligence networks, poison weapons, and fanatical loyalty—Ochi hunts for cult doctrine not guild credits.",
           reputation_detail="Sith Eternal trusted Ochi with wayfinder mission; Lando Calrissian encountered his trail on Pasaana; Jedi historians classify him as dark-side hunter operative.",
           impact_detail="Ochi's wayfinder hunt connected Palpatine's return plot to hunter-assassin tradecraft—bridging bounty culture and Sith Eternal cult operations.",
           events=["Recruited by Palpatine's Sith Eternal", "Hunts Sith wayfinder artifacts", "Pursues Rey's parents on Jakku", "Operates on Pasaana", "Dies in acid pool during mission"],
           affiliations=["Sith Eternal cult", "Palpatine's Final Order", "Bestoon assassin clans", "Exegol cult operations", "Wayfinder search network"],
           timeline=[("Bestoon", "Assassin clan training"), ("Sith Eternal", "Palpatine recruitment"), ("Wayfinder Hunt", "Artifact pursuit begins"), ("Jakku", "Rey's parents targeted"), ("Pasaana", "Death in acid pool")])),
        ("Bazine Netal", "Spy & Bounty Adjacent Operative", "Chaasadai", "Mercenary spy at Maz Kanata's castle who reported to First Order on Solo's movements.", "#64748b", "Force Awakens · comics", "human",
         d(origin_detail="Bazine Netal operated as mercenary spy at Maz Kanata's castle on Takodana, selling intelligence to First Order about Han Solo's Resistance movements during Force Awakens era.",
           ancient_detail="Chaasadai mercenary spy networks supplied Old Republic intelligence markets; Bazine represents post-Imperial era hunter-spy hybrids working First Order contracts.",
           modern_detail="Bazine's Takodana castle presence during Force Awakens made her key informant in Han Solo pursuit—hunter-adjacent intelligence rather than direct puck work.",
           conflict_detail="Bazine monitored Maz's castle clientele, reported Solo's arrival to First Order, and operated in shadow intelligence economy parallel to bounty boards.",
           methods_detail="Social infiltration at neutral castle hubs, encrypted First Order reporting, disguise, and information brokerage—Bazine sells locations not captures.",
           reputation_detail="Maz Kanata's staff watched Bazine suspiciously; First Order valued her Takodana access; Resistance later flagged her as First Order intelligence asset.",
           impact_detail="Bazine Netal demonstrated post-Endor hunter economy includes intelligence mercenaries at neutral hubs—complementing traditional capture-kill contracts.",
           events=["Establishes cover at Maz's castle", "Monitors smuggler and Resistance traffic", "Reports Han Solo arrival to First Order", "Force Awakens intelligence role", "Mercenary spy at Takodana"],
           affiliations=["First Order intelligence", "Maz Kanata's castle (cover)", "Chaasadai mercenary networks", "Information broker markets", "Han Solo surveillance"],
           timeline=[("Chaasadai", "Mercenary spy training"), ("Takodana", "Castle infiltration cover"), ("Force Awakens", "Solo intelligence report"), ("First Order", "Contracted asset"), ("Legacy", "Spy-hunter hybrid model")])),
        ("Mercurial Swift", "Bounty Hunter", "Coruscant", "Core world hunter competing in War of the Bounty Hunters after Han Solo carbonite theft.", "#65a30d", "Comics · War of the Bounty Hunters", "human",
         d(origin_detail="Mercurial Swift built Coruscant Core-world hunter reputation for speed and agility before joining the chaotic competition for Han Solo's stolen carbonite block in War of the Bounty Hunters.",
           ancient_detail="Coruscant guild posting boards historically favored Core-trained hunters with political connections; Swift represents urban hunter elite in post-Endor comics crossover.",
           modern_detail="Swift competed alongside Boba Fett, Valance, and Nakano Lash during carbonite theft crisis—Core agility against Rim brutality in marquee comics event.",
           conflict_detail="Swift pursued Solo carbonite puck across Nar Shaddaa and Core worlds, clashed with rival hunters, and navigated post-Endor guild lawlessness.",
           methods_detail="Acrobatic pursuit, speed-focused starship chases, Core-world guild connections, and rapid close-quarters takedowns—Swift lives up to his name.",
           reputation_detail="Coruscant brokers ranked Swift among top Core hunters; War of the Bounty Hunters elevated his profile against marquee Rim legends.",
           impact_detail="Mercurial Swift represented Core-world hunter interests in War of the Bounty Hunters—balancing Rim icons like Fett with urban elite competition.",
           events=["Builds Coruscant hunter reputation", "Enters War of the Bounty Hunters", "Pursues Han Solo carbonite puck", "Competes against Boba Fett and Valance", "Core-world agility showcase"],
           affiliations=["Bounty Hunters' Guild", "Coruscant posting boards", "War of the Bounty Hunters competitors", "Core-world hunter elite", "Han Solo carbonite chase"],
           timeline=[("Coruscant", "Core hunter rise"), ("Guild Elite", "Speed and agility fame"), ("Carbonite Theft", "Solo puck competition"), ("Crossover", "War of the Bounty Hunters"), ("Legacy", "Core hunter representation")])),
        ("Skadge", "Barabel Bounty Hunter", "Barab I", "Barabel enforcer from KOTOR II Exchange who brute-forced targets on Nar Shaddaa.", "#991b1b", "KOTOR II", "alien",
         d(origin_detail="Skadge, a Barabel enforcer, served Nar Shaddaa Exchange brutalizing targets and hunters alike—Meetra Surik's crew encountered him as force-of-nature obstacle in KOTOR II's underworld.",
           ancient_detail="Barabel mercenary enforcers from Barab I supplied Exchange muscle for centuries; Skadge represents reptilian brute hunters predating Trandoshan guild dominance.",
           modern_detail="Skadge's KOTOR II role as Exchange enforcer made him memorable brute hunter in Old Republic gaming era alongside Calo Nord and Hanharr.",
           conflict_detail="Skadge enforced Exchange debts on Nar Shaddaa, fought Surik's companions in tight vertical city combat, and embodied Exchange preference for terror over negotiation.",
           methods_detail="Barabel raw strength, intimidation, close-quarters mauling, and Exchange backing—Skadge breaks bodies rather than tracking across systems.",
           reputation_detail="Exchange clients valued Skadge's terror factor; Nar Shaddaa refugees feared him; KOTOR II players remember his brute-force boss encounters.",
           impact_detail="Skadge exemplified Exchange brute-enforcer hunter class in KOTOR II—complementing Mira's ethical scout opposition on same moon.",
           events=["Exchange enforcer on Nar Shaddaa", "Brutalizes debt targets and rivals", "Confronts Meetra Surik's crew", "KOTOR II underworld encounters", "Barabel brute hunter icon"],
           affiliations=["Nar Shaddaa Exchange", "Barabel enforcer networks", "KOTOR II underworld", "Exchange debt collection", "Meetra Surik (opposed)"],
           timeline=[("Barab I", "Barabel enforcer origins"), ("Exchange", "Nar Shaddaa muscle"), ("Enforcement", "Debt brutalization"), ("Surik Crew", "KOTOR II confrontation"), ("Legacy", "Exchange brute archetype")])),
        ("Gault Rennow", "Bounty Hunter", "Unknown", "Hunter from KOTOR II smuggling moon Nar Shaddaa with ties to Exchange and refugee networks.", "#94a3b8", "KOTOR II", "human",
         d(origin_detail="Gault Rennow operated on Nar Shaddaa during KOTOR II as hunter-smuggler hybrid navigating Exchange politics, refugee networks, and Meetra Surik's crew orbit.",
           ancient_detail="Nar Shaddaa hunter-smuggler hybrids predated Gault; KOTOR Exchange markets blurred puck work and contraband transport on vertical city levels.",
           modern_detail="Gault Rennow's KOTOR II presence added neutral hunter option in Surik's companion ecosystem—pragmatic contractor avoiding Exchange extremes.",
           conflict_detail="Gault navigated Nar Shaddaa Exchange territory, took selective contracts avoiding Skadge's brutality, and operated in Jedi Civil War aftermath chaos.",
           methods_detail="Smuggler routes, selective contract acceptance, blaster pragmatism, and refugee network contacts—Gault hunts when paid but avoids cult-like Exchange loyalty.",
           reputation_detail="Nar Shaddaa brokers knew Gault as reliable middle-tier hunter; Surik crew considered him optional ally; Exchange tolerated his independence.",
           impact_detail="Gault Rennow represented neutral hunter middle ground in KOTOR II's Exchange-dominated Nar Shaddaa—between Mira's ethics and Skadge's brutality.",
           events=["Operates on Nar Shaddaa during KOTOR II", "Navigates Exchange hunter politics", "Selective contract work", "Surik crew orbit interactions", "Hunter-smuggler hybrid model"],
           affiliations=["Nar Shaddaa hunter markets", "Exchange (independent contractor)", "KOTOR II smuggling routes", "Refugee network contacts", "Meetra Surik (optional ally)"],
           timeline=[("Nar Shaddaa", "Hunter-smuggler setup"), ("Exchange Era", "Independent contracts"), ("KOTOR II", "Surik timeline operations"), ("Neutrality", "Avoids Exchange extremes"), ("Legacy", "Middle-tier hunter model")])),
        ("Tarro Blood", "Mandalorian Bounty Hunter", "Mandalore", "Notorious Mandalorian rival from SWTOR Great Hunt competition.", "#0284c7", "SWTOR", "mando",
         d(origin_detail="Tarro Blood earned notoriety in SWTOR's Great Hunt by cheating, sabotaging rivals, and exploiting Mandalorian competition rules—becoming primary antagonist to bounty hunter player character.",
           ancient_detail="SWTOR Great Hunt revived Mandalorian bounty competition traditions from KOTOR-era mercenary trials; Tarro Blood represents corrupted honor in sacred hunter games.",
           modern_detail="Tarro Blood's SWTOR Great Hunt arc made him iconic gaming antagonist—Mandalorian hunter who wins through sabotage rather than skill.",
           conflict_detail="Tarro sabotaged Great Hunt competitors on Dromund Kaas, Nar Shaddaa, and Hutta before facing player hunter in Mandalorian arena showdown.",
           methods_detail="Sabotage, hired thugs, political manipulation of Hunt rules, and Mandalorian armor—Tarro Blood fights dirty in supposedly honorable competition.",
           reputation_detail="Great Hunt officials disqualified Tarro repeatedly; Mandalorian elders despised him; SWTOR players remember him as cheat antagonist.",
           impact_detail="Tarro Blood defined SWTOR Great Hunt narrative tension—honorable Mandalorian hunting tradition versus corrupted competitor exploiting system.",
           events=["Enters SWTOR Great Hunt competition", "Sabotages rival hunters repeatedly", "Exploits Mandalorian Hunt rules", "Antagonizes player hunter protagonist", "Arena showdown in Great Hunt finale"],
           affiliations=["SWTOR Great Hunt", "Mandalorian competition (disqualified)", "Dromund Kaas hunter markets", "Sabotage networks", "Mandalore hunter tradition (corrupted)"],
           timeline=[("Great Hunt Entry", "SWTOR competition begins"), ("Sabotage", "Rival hunter attacks"), ("Disqualification", "Rule exploitation exposed"), ("Arena", "Final confrontation"), ("Legacy", "SWTOR cheat antagonist")])),
        ("Braden", "Mandalorian Bounty Hunter Mentor", "Mandalore", "Veteran hunter who trained SWTOR protagonists in Great Hunt prelude on Dromund Kaas.", "#0284c7", "SWTOR", "mando",
         d(origin_detail="Braden, veteran Mandalorian hunter, mentored SWTOR player character during Great Hunt prelude on Dromund Kaas before his murder launched the competition's central revenge arc.",
           ancient_detail="Mandalorian hunter mentorship traditions require veterans to train Great Hunt entrants; Braden represents honorable predecessor to Tarro Blood's corruption.",
           modern_detail="Braden's death in SWTOR opening hours motivated player hunter's Great Hunt victory—mentor martyrdom driving SWTOR bounty hunter class narrative.",
           conflict_detail="Braden trained player on Dromund Kaas, held off attackers during ambush, and died protecting protégé—triggering Great Hunt revenge storyline.",
           methods_detail="Veteran Mandalorian tactics, mentorship pedagogy, blaster defense, and strategic planning—Braden teaches before fighting.",
           reputation_detail="Mandalorian Hunt officials respected Braden; his protégé avenged him; SWTOR community remembers him as tragic mentor figure.",
           impact_detail="Braden's death catalyzed SWTOR Great Hunt narrative—establishing emotional stakes for player bounty hunter class origin story.",
           events=["Mentors SWTOR player on Dromund Kaas", "Trains Great Hunt prelude skills", "Ambushed during training mission", "Dies protecting protégé", "Death motivates Great Hunt revenge arc"],
           affiliations=["SWTOR Great Hunt", "Mandalorian mentor tradition", "Dromund Kaas hunter training", "Player hunter protégé", "Mandalore hunter culture"],
           timeline=[("Veteran Era", "Established hunter reputation"), ("Mentorship", "Trains SWTOR protagonist"), ("Ambush", "Dromund Kaas attack"), ("Death", "Martyrdom protecting protégé"), ("Legacy", "Great Hunt motivation")])),
        ("Shae Vizla", "Mandalorian Bounty Hunter", "Mandalore", "Mandalorian warrior who assaulted Jedi Temple during Sacking of Coruscant in SWTOR.", "#0284c7", "SWTOR", "mando",
         d(origin_detail="Shae Vizla, Mandalorian warrior-hunter, led assault on Jedi Temple during SWTOR's Sacking of Coruscant—blurring line between bounty hunter and Mandalorian military operative.",
           ancient_detail="Mandalorian warriors participated in Sacking of Coruscant as vanguard; Shae Vizla represents TOR-era hunter-soldiers serving Sith Empire against Jedi Order.",
           modern_detail="Shae Vizla became SWTOR cinematic icon and playable-adjacent character—Mandalorian hunter whose Temple assault defined game's opening timeline.",
           conflict_detail="Shae Vizla breached Jedi Temple during Coruscant invasion, fought Jedi defenders in close combat, and exemplified Mandalorian-Sith alliance against Republic.",
           methods_detail="Beskar armor, jetpack assault, flamethrower clearing, and Temple infiltration—Shae Vizla fights as shock trooper not tracker.",
           reputation_detail="Sith Empire celebrated her Temple assault; Jedi survivors remember her beskar silhouette; SWTOR players recognize her from opening cinematic.",
           impact_detail="Shae Vizla's Jedi Temple assault anchored SWTOR timeline—proving Mandalorian hunters serve as elite vanguard in Sith-Republic total war.",
           events=["Joins Sith Empire Mandalorian vanguard", "Assaults Jedi Temple during Sacking of Coruscant", "Fights Jedi Temple defenders", "SWTOR cinematic opening icon", "Mandalorian hunter-soldier legend"],
           affiliations=["Mandalorian warrior clans", "Sith Empire (allied)", "SWTOR Coruscant invasion force", "Jedi Temple assault team", "Mandalore military tradition"],
           timeline=[("Mandalore", "Warrior-hunter training"), ("Sith Alliance", "Empire contract service"), ("Sacking", "Coruscant invasion"), ("Temple Assault", "Jedi Temple breach"), ("Legacy", "SWTOR cinematic icon")])),
    ]
    for e in entries:
        _add(*e)

    from build_bh_hunters_rest5 import register_rest5
    register_rest5(_add, L)
