#!/usr/bin/env python3
"""Curated Related Archives links for each Galactic History chronicle era."""

from __future__ import annotations

# (label, display value, route)
CHRONICLE_ERA_LINKS: dict[str, list[tuple[str, str, str]]] = {
    "dawn-of-the-jedi": [
        ("Planet", "Tython", "planet/tython"),
        ("Planet", "Korriban", "korriban"),
        ("Planet", "Ossus", "planet/ossus"),
        ("Planet", "Rakata Prime", "planet/rakata-prime"),
        ("Sith", "Ajunta Pall", "sith/ajunta-pall"),
        ("Species", "Rakata", "species/rakata"),
        ("Species", "Human", "species/human"),
        ("Species", "Massassi", "species/massassi"),
        ("Conflict", "Hundred-Year Darkness", "wars-conflicts/hundred-year-darkness"),
        ("Settlement", "Jedha City", "settlements/jedha-city"),
        ("Directory", "Jedi Order", "all-jedi"),
        ("Directory", "Sith Order", "all-sith"),
        ("Directory", "Planet Directory", "all-planets"),
        ("Directory", "Species Directory", "all-species"),
        ("Directory", "Character Directory", "all-characters"),
        ("Directory", "Ship Directory", "all-ships"),
        ("Directory", "Droid Directory", "all-droids"),
        ("Directory", "Settlements Directory", "all-cities-settlements"),
        ("Directory", "Bounty Hunter Directory", "all-bounty-hunters"),
        ("Force", "Jedi Code", "the-force/jedi-code"),
        ("Force", "Sith Code", "the-force/sith-code"),
    ],
    "old-sith-empire": [
        ("Planet", "Dromund Kaas", "planet/dromund-kaas"),
        ("Planet", "Korriban", "korriban"),
        ("Planet", "Ziost", "planet/ziost"),
        ("Planet", "Moraband", "planet/moraband"),
        ("Planet", "Nathema", "planet/nathema"),
        ("Planet", "Yavin 4", "planet/yavin-4"),
        ("Planet", "Ossus", "planet/ossus"),
        ("Sith", "Darth Vitiate", "sith/darth-vitiate"),
        ("Sith", "Naga Sadow", "sith/naga-sadow"),
        ("Sith", "Ludo Kressh", "sith/ludo-kressh"),
        ("Sith", "Marka Ragnos", "sith/marka-ragnos"),
        ("Sith", "Exar Kun", "sith/exar-kun"),
        ("Sith", "Freedon Nadd", "sith/freedon-nadd"),
        ("Conflict", "Great Sith War", "wars-conflicts/great-sith-war"),
        ("Conflict", "Stark Hyperspace War", "wars-conflicts/stark-hyperspace-war"),
        ("Military unit", "Sith Empire", "military-units/sith-empire"),
        ("Species", "Sith (Pureblood)", "species/sith-pureblood"),
        ("Settlement", "Kaas City", "settlements/kaas-city"),
        ("Ship", "Sith Interceptor", "ships/sith-interceptor"),
        ("Directory", "Jedi Order", "all-jedi"),
        ("Directory", "Sith Order", "all-sith"),
        ("Directory", "Planet Directory", "all-planets"),
        ("Directory", "Character Directory", "all-characters"),
        ("Directory", "Ship Directory", "all-ships"),
        ("Directory", "Species Directory", "all-species"),
        ("Directory", "Settlements Directory", "all-cities-settlements"),
        ("Directory", "Bounty Hunter Directory", "all-bounty-hunters"),
        ("Directory", "Droid Directory", "all-droids"),
    ],
    "old-republic": [
        ("Planet", "Coruscant", "coruscant"),
        ("Planet", "Ruusan", "planet/ruusan"),
        ("Planet", "Dxun", "planet/dxun"),
        ("Planet", "Malachor V", "planet/malachor-v"),
        ("Planet", "Telos", "planet/telos"),
        ("Planet", "Taris", "planet/taris"),
        ("Planet", "Dromund Kaas", "planet/dromund-kaas"),
        ("Jedi", "Yoda", "jedi/yoda"),
        ("Jedi", "Bastila Shan", "jedi/bastila-shan"),
        ("Jedi", "Jolee Bindo", "jedi/jolee-bindo"),
        ("Jedi", "Meetra Surik", "jedi/meetra-surik"),
        ("Jedi", "Satele Shan", "jedi/satele-shan"),
        ("Jedi", "Revan", "jedi/revan"),
        ("Character", "Carth Onasi", "characters/carth-onasi"),
        ("Sith", "Darth Revan", "sith/darth-revan"),
        ("Sith", "Darth Malak", "sith/darth-malak"),
        ("Sith", "Sith Emperor", "sith/darth-vitiate"),
        ("Sith", "Darth Malgus", "sith/darth-malgus"),
        ("Sith", "Darth Nihilus", "sith/darth-nihilus"),
        ("Sith", "Darth Sion", "sith/darth-sion"),
        ("Sith", "Darth Traya", "sith/darth-traya"),
        ("Sith", "Darth Bane", "sith/darth-bane"),
        ("Conflict", "Mandalorian Wars", "wars-conflicts/mandalorian-wars"),
        ("Conflict", "New Sith Wars", "wars-conflicts/new-sith-wars"),
        ("Conflict", "Great Galactic War", "wars-conflicts/great-galactic-war"),
        ("Faction", "Galactic Republic", "factions/republic"),
        ("Military unit", "Old Republic", "military-units/old-republic"),
        ("Military unit", "Sith Empire", "military-units/sith-empire"),
        ("Character", "HK-47", "characters/hk-47"),
        ("Species", "Human", "species/human"),
        ("Species", "Mandalorian", "species/mandalorian"),
        ("Bounty Hunter", "Cad Bane", "bounty-hunters/cad-bane"),
        ("Settlement", "Mos Eisley", "settlements/mos-eisley"),
        ("Ship", "Hammerhead Corvette", "ships/hammerhead-corvette"),
        ("Directory", "Jedi Directory", "all-jedi"),
        ("Directory", "Sith Directory", "all-sith"),
        ("Directory", "Planet Directory", "all-planets"),
    ],
    "high-republic": [
        ("Planet", "Coruscant", "coruscant"),
        ("Planet", "Naboo", "naboo"),
        ("Planet", "Dathomir", "planet/dathomir"),
        ("Planet", "Carida", "carida"),
        ("Jedi", "Yoda", "jedi/yoda"),
        ("Jedi", "Yaddle", "jedi/yaddle"),
        ("Jedi", "Mace Windu", "jedi/mace-windu"),
        ("Jedi", "Depa Billaba", "jedi/depa-billaba"),
        ("Species", "Togruta", "species/togruta"),
        ("Species", "Mirialan", "species/mirialan"),
        ("Species", "Chiss", "species/chiss"),
        ("Faction", "Galactic Republic", "factions/republic"),
        ("Settlement", "Theed", "settlements/theed"),
        ("Ship", "Consular-class Cruiser", "ships/consular-class"),
        ("Ship", "Venator-class", "ships/venator-class"),
        ("Droid", "BD-1", "droids/bd-1"),
        ("Character", "Mon Mothma", "characters/mon-mothma"),
        ("Directory", "Jedi Directory", "all-jedi"),
        ("Directory", "Planet Directory", "all-planets"),
        ("Directory", "Ship Directory", "all-ships"),
        ("Directory", "Species Directory", "all-species"),
        ("Directory", "Character Directory", "all-characters"),
        ("Directory", "Droid Directory", "all-droids"),
        ("Directory", "Settlements Directory", "all-cities-settlements"),
    ],
    "fall-of-the-republic": [
        ("Planet", "Coruscant", "coruscant"),
        ("Planet", "Geonosis", "planet/geonosis"),
        ("Planet", "Utapau", "planet/utapau"),
        ("Planet", "Mustafar", "mustafar"),
        ("Planet", "Kashyyyk", "planet/kashyyyk"),
        ("Jedi", "Obi-Wan Kenobi", "jedi/obi-wan-kenobi"),
        ("Jedi", "Anakin Skywalker", "jedi/anakin-skywalker"),
        ("Jedi", "Yoda", "jedi/yoda"),
        ("Jedi", "Mace Windu", "jedi/mace-windu"),
        ("Jedi", "Ahsoka Tano", "jedi/ahsoka-tano"),
        ("Sith", "Darth Sidious", "sith/darth-sidious"),
        ("Sith", "Darth Tyranus", "sith/darth-tyranus"),
        ("Sith", "Darth Maul", "sith/darth-maul"),
        ("Conflict", "Clone Wars", "wars-conflicts/clone-wars"),
        ("Faction", "Galactic Republic", "factions/republic"),
        ("Faction", "Confederacy of Independent Systems", "factions/confederacy"),
        ("Military unit", "Galactic Republic", "military-units/galactic-republic"),
        ("Military unit", "Confederacy of Independent Systems", "military-units/confederacy-of-independent-systems"),
        ("Character", "General Grievous", "characters/general-grievous"),
        ("Ship", "Venator-class Star Destroyer", "ships/venator-class"),
        ("Ship", "X-wing", "ships/x-wing"),
        ("Droid", "R2-D2", "droids/r2-d2"),
        ("Droid", "C-3PO", "droids/c-3po"),
        ("Bounty Hunter", "Jango Fett", "bounty-hunters/jango-fett"),
    ],
    "reign-of-the-empire": [
        ("Planet", "Coruscant", "coruscant"),
        ("Planet", "Lothal", "planet/lothal"),
        ("Planet", "Malachor", "planet/malachor"),
        ("Planet", "Ilum", "planet/ilum"),
        ("Planet", "Jedha", "planet/jedha"),
        ("Sith", "Darth Vader", "sith/darth-vader"),
        ("Sith", "Darth Sidious", "sith/darth-sidious"),
        ("Sith", "Grand Inquisitor", "sith/grand-inquisitor"),
        ("Sith", "Second Sister", "sith/second-sister"),
        ("Jedi", "Kanan Jarrus", "jedi/kanan-jarrus"),
        ("Jedi", "Ezra Bridger", "jedi/ezra-bridger"),
        ("Faction", "Galactic Empire", "factions/empire"),
        ("Military unit", "Galactic Empire", "military-units/galactic-empire"),
        ("Character", "Grand Moff Tarkin", "characters/grand-moff-tarkin"),
        ("Ship", "Imperial I-class Star Destroyer", "ships/imperial-i-class"),
        ("Ship", "TIE Fighter", "ships/tie-fighter"),
        ("Ship", "Executor-class", "ships/executor-class"),
        ("Droid", "K-2SO", "droids/k-2so"),
        ("Species", "Lasat", "species/lasat"),
        ("Settlement", "Cloud City", "settlements/cloud-city"),
        ("Bounty Hunter", "Boba Fett", "bounty-hunters/boba-fett"),
        ("Directory", "Sith Directory", "all-sith"),
        ("Directory", "Jedi Directory", "all-jedi"),
        ("Directory", "Ship Directory", "all-ships"),
    ],
    "age-of-rebellion": [
        ("Planet", "Yavin 4", "planet/yavin-4"),
        ("Planet", "Hoth", "hoth"),
        ("Planet", "Endor", "planet/endor"),
        ("Planet", "Bespin", "bespin"),
        ("Planet", "Scarif", "planet/scarif"),
        ("Planet", "Dagobah", "planet/dagobah"),
        ("Jedi", "Luke Skywalker", "jedi/luke-skywalker"),
        ("Jedi", "Obi-Wan Kenobi", "jedi/obi-wan-kenobi"),
        ("Jedi", "Yoda", "jedi/yoda"),
        ("Character", "Leia Organa", "characters/leia-organa"),
        ("Character", "Han Solo", "characters/han-solo"),
        ("Character", "Chewbacca", "characters/chewbacca"),
        ("Sith", "Darth Vader", "sith/darth-vader"),
        ("Conflict", "Galactic Civil War", "wars-conflicts/galactic-civil-war"),
        ("Faction", "Rebel Alliance", "factions/rebel-alliance"),
        ("Military unit", "Rebel Alliance", "military-units/rebel-alliance"),
        ("Ship", "Millennium Falcon", "ships/millennium-falcon"),
        ("Ship", "X-wing", "ships/x-wing"),
        ("Ship", "Executor-class", "ships/executor-class"),
        ("Droid", "R2-D2", "droids/r2-d2"),
        ("Droid", "C-3PO", "droids/c-3po"),
        ("Species", "Wookiee", "species/wookiee"),
        ("Settlement", "Cloud City", "settlements/cloud-city"),
        ("Bounty Hunter", "Boba Fett", "bounty-hunters/boba-fett"),
    ],
    "new-republic": [
        ("Planet", "Jakku", "planet/jakku"),
        ("Planet", "Coruscant", "coruscant"),
        ("Planet", "Hosnian Prime", "planet/hosnian-prime"),
        ("Planet", "Takodana", "planet/takodana"),
        ("Planet", "Ahch-To", "planet/ahch-to"),
        ("Jedi", "Luke Skywalker", "jedi/luke-skywalker"),
        ("Character", "Leia Organa", "characters/leia-organa"),
        ("Character", "Mon Mothma", "characters/mon-mothma"),
        ("Character", "Han Solo", "characters/han-solo"),
        ("Faction", "New Republic", "factions/new-republic"),
        ("Military unit", "New Republic", "military-units/new-republic"),
        ("Military unit", "Resistance", "military-units/resistance"),
        ("Ship", "MC80 Star Cruiser", "ships/mc80-cruiser"),
        ("Ship", "X-wing", "ships/x-wing"),
        ("Species", "Mon Calamari", "species/mon-calamari"),
        ("Species", "Human", "species/human"),
        ("Droid", "BB-8", "droids/bb-8"),
        ("Settlement", "Mos Eisley", "settlements/mos-eisley"),
        ("Bounty Hunter", "Din Djarin", "bounty-hunters/din-djarin"),
        ("Jedi", "Grogu", "jedi/grogu"),
        ("Directory", "Character Directory", "all-characters"),
        ("Directory", "Planet Directory", "all-planets"),
        ("Directory", "Ship Directory", "all-ships"),
        ("Directory", "Jedi Directory", "all-jedi"),
    ],
    "rise-of-the-first-order": [
        ("Planet", "Starkiller Base", "planet/starkiller-base"),
        ("Planet", "Crait", "planet/crait"),
        ("Planet", "Exegol", "planet/exegol"),
        ("Planet", "D'Qar", "planet/d-qar"),
        ("Planet", "Hosnian Prime", "planet/hosnian-prime"),
        ("Character", "Rey", "characters/rey"),
        ("Character", "Finn", "characters/finn"),
        ("Character", "Poe Dameron", "characters/poe-dameron"),
        ("Sith", "Darth Sidious", "sith/darth-sidious"),
        ("Conflict", "Cold War (First Order)", "wars-conflicts/cold-war"),
        ("Faction", "First Order", "factions/first-order"),
        ("Military unit", "First Order", "military-units/first-order"),
        ("Military unit", "Resistance", "military-units/resistance"),
        ("Ship", "Resurgent-class Star Destroyer", "ships/resurgent-class"),
        ("Ship", "TIE Fighter", "ships/tie-fighter"),
        ("Droid", "BB-8", "droids/bb-8"),
        ("Species", "Human", "species/human"),
        ("Settlement", "Takodana Castle", "settlements/takodana-castle"),
        ("Bounty Hunter", "Boba Fett", "bounty-hunters/boba-fett"),
        ("Directory", "Character Directory", "all-characters"),
        ("Directory", "Ship Directory", "all-ships"),
        ("Directory", "Planet Directory", "all-planets"),
        ("Directory", "Droid Directory", "all-droids"),
        ("Directory", "Bounty Hunter Directory", "all-bounty-hunters"),
    ],
    "new-jedi-order": [
        ("Planet", "Ahch-To", "planet/ahch-to"),
        ("Planet", "Exegol", "planet/exegol"),
        ("Planet", "Tatooine", "tatooine"),
        ("Planet", "Coruscant", "coruscant"),
        ("Jedi", "Luke Skywalker", "jedi/luke-skywalker"),
        ("Character", "Rey", "characters/rey"),
        ("Jedi", "Grogu", "jedi/grogu"),
        ("Jedi", "Kanan Jarrus", "jedi/kanan-jarrus"),
        ("Sith", "Darth Vader", "sith/darth-vader"),
        ("Sith", "Darth Sidious", "sith/darth-sidious"),
        ("Force", "Jedi Code", "the-force/jedi-code"),
        ("Force", "Sith Code", "the-force/sith-code"),
        ("Character", "Leia Organa", "characters/leia-organa"),
        ("Ship", "Millennium Falcon", "ships/millennium-falcon"),
        ("Ship", "X-wing", "ships/x-wing"),
        ("Droid", "BB-8", "droids/bb-8"),
        ("Species", "Human", "species/human"),
        ("Settlement", "Mos Eisley", "settlements/mos-eisley"),
        ("Bounty Hunter", "Din Djarin", "bounty-hunters/din-djarin"),
        ("Directory", "Jedi Directory", "all-jedi"),
        ("Directory", "Sith Directory", "all-sith"),
        ("Directory", "Character Directory", "all-characters"),
        ("Directory", "Planet Directory", "all-planets"),
        ("Directory", "Ship Directory", "all-ships"),
    ],
}
