#!/usr/bin/env python3
"""Canonical homeworld planet slugs for directory entries (category/slug -> planet slug)."""

from __future__ import annotations

JEDI: dict[str, str] = {
    "aayla-secura": "ryloth",
    "adi-gallia": "chalacta",
    "agen-kolar": "iridonia",
    "ahsoka-tano": "shili",
    "anakin-skywalker": "tatooine",
    "barriss-offee": "mirial",
    "bastila-shan": "talravin",
    "bolla-ropal": "dorin",
    "cin-drallig": "coruscant",
    "coleman-kcaj": "coruscant",
    "coleman-trebor": "coruscant",
    "depa-billaba": "haruun-kal",
    "eeth-koth": "iridonia",
    "even-piell": "lannik",
    "ezra-bridger": "lothal",
    "gungi": "kashyyyk",
    "jolee-bindo": "kashyyyk",
    "jocasta-nu": "coruscant",
    "kanan-jarrus": "coruscant",
    "katooni": "dathomir",
    "kelleran-beq": "coruscant",
    "ki-adi-mundi": "cerea",
    "kit-fisto": "glee-anselm",
    "luminara-unduli": "mirial",
    "luke-skywalker": "tatooine",
    "meetra-surik": "dantooine",
    "mace-windu": "haruun-kal",
    "nahdar-vebb": "glee-anselm",
    "obi-wan-kenobi": "stewjon",
    "oppo-rancisis": "thisspias",
    "petro": "coruscant",
    "plo-koon": "dorin",
    "quinlan-vos": "kiffu",
    "qui-gon-jinn": "coruscant",
    "revan": "dromund-kaas",
    "saesee-tiin": "ithor",
    "satele-shan": "tython",
    "shaak-ti": "shili",
    "sifo-dyas": "minashee",
    "stass-allie": "tholoth",
    "tera-sinube": "coruscant",
    "tiplee": "coruscant",
    "tiplar": "coruscant",
    "yaddle": "coruscant",
    "yoda": "dagobah",
}

SITH: dict[str, str] = {
    "darth-sidious": "naboo",
    "darth-maul": "dathomir",
    "darth-tyranus": "serenno",
    "darth-vader": "tatooine",
    "darth-plagueis": "mygeeto",
    "savage-opress": "dathomir",
    "asajj-ventress": "dathomir",
    "grand-inquisitor": "utapau",
    "second-sister": "coruscant",
    "fifth-brother": "coruscant",
    "seventh-sister": "coruscant",
    "eighth-brother": "coruscant",
    "ninth-sister": "coruscant",
    "sixth-brother": "coruscant",
    "barriss-offee": "mirial",
    "pong-krell": "kiffu",
    "darth-revan": "dromund-kaas",
    "darth-malak": "dromund-kaas",
    "darth-bandon": "dromund-kaas",
    "darth-traya": "malachor-v",
    "darth-sion": "malachor-v",
    "darth-nihilus": "katarr",
    "marka-ragnos": "korriban",
    "naga-sadow": "korriban",
    "ludo-kressh": "korriban",
    "tulak-hord": "korriban",
    "exar-kun": "yavin-4",
    "ulic-qel-droma": "alderaan",
    "darth-vitiate": "dromund-kaas",
    "darth-malgus": "dromund-kaas",
    "darth-bane": "moraband",
    "darth-zannah": "ambria",
    "ajunta-pall": "korriban",
    "freedon-nadd": "korriban",
}

CHARACTERS: dict[str, str] = {
    "luke-skywalker": "tatooine",
    "leia-organa": "alderaan",
    "han-solo": "corellia",
    "chewbacca": "kashyyyk",
    "anakin-skywalker": "tatooine",
    "padme-amidala": "naboo",
    "obi-wan-kenobi": "stewjon",
    "darth-vader": "tatooine",
    "yoda": "dagobah",
    "palpatine": "naboo",
    "rey": "jakku",
    "finn": "unknown",
    "mace-windu": "haruun-kal",
    "ahsoka-tano": "shili",
    "boba-fett": "kamino",
    "jango-fett": "concord-dawn",
    "din-djarin": "aconitine",
    "sabine-wren": "krownest",
    "hux": "arkanis",
    "mon-mothma": "chandrila",
    "landon-calrissian": "socorro",
    "lando-calrissian": "socorro",
    "jar-jar-binks": "naboo",
    "shmi-skywalker": "tatooine",
    "bail-organa": "alderaan",
    "breha-organa": "alderaan",
    "cassian-andor": "fest",
    "jyn-erso": "vallt",
    "thrawn": "csilla",
    "general-grievous": "kalee",
    "count-dooku": "serenno",
    "moff-gideon": "coruscant",
    "bo-katan-kryze": "mandalore",
    "satine-kryze": "kalevala",
    "saw-gerrera": "onderon",
    "bodhi-rook": "jedha",
    "chirrut-imwe": "jedha",
    "baze-malbus": "jedha",
    "amilyn-holdo": "gatalenta",
    "poe-dameron": "yavin-4",
    "zam-wesell": "zolan",
    "watto": "tatooine",
    "sebulba": "malastare",
    "nute-gunray": "cato-neimoidia",
    "wedge-antilles": "corellia",
    "biggs-darklighter": "tatooine",
    "boushh": "ubrikkia",
    "snoke": "unknown",
    "kylo-ren": "chandrila",
    "maz-kanata": "takodana",
    "jabba-the-hutt": "nal-hutta",
    "wat tambine": "tambine",
    "satele-shan": "tython",
    "bastila-shan": "talravin",
    "revan": "dromund-kaas",
    "malak": "dromund-kaas",
    "meetra-surik": "dantooine",
    "carth-onasi": "telos",
    "mission-vao": "taris",
    "zaalbar": "kashyyyk",
    "t3-m4": "tatooine",
    "hk-47": "revan",
    "yoda-species": "unknown",
}

SHIP_KEYWORDS: list[tuple[str, str]] = [
    ("corellian", "corellia"),
    ("kuat", "kuat"),
    ("mon cal", "mon-cala"),
    ("mon-cala", "mon-cala"),
    ("naboo", "naboo"),
    ("mandalore", "mandalore"),
    ("geonos", "geonosis"),
    ("trade federation", "neimoidia"),
    ("separatist", "geonosis"),
    ("republic", "coruscant"),
    ("imperial", "coruscant"),
    ("first order", "starkiller-base"),
    ("resistance", "d-qar"),
    ("hutt", "nal-hutta"),
    ("sith", "korriban"),
    ("jedi", "coruscant"),
    ("yavin", "yavin-4"),
    ("endor", "endor"),
    ("hoth", "hoth"),
    ("tatooine", "tatooine"),
    ("coruscant", "coruscant"),
    ("kashyyyk", "kashyyyk"),
    ("mustafar", "mustafar"),
    ("kamino", "kamino"),
    ("bespin", "bespin"),
    ("dathomir", "dathomir"),
    ("ryloth", "ryloth"),
    ("alderaan", "alderaan"),
    ("scarif", "scarif"),
    ("jakku", "jakku"),
    ("exegol", "exegol"),
    ("crait", "crait"),
    ("lothal", "lothal"),
    ("dantooine", "dantooine"),
    ("malachor", "malachor-v"),
    ("korriban", "korriban"),
    ("tython", "tython"),
]

DROID_KEYWORDS: list[tuple[str, str]] = [
    ("geonos", "geonosis"),
    ("kashyyyk", "kashyyyk"),
    ("tatooine", "tatooine"),
    ("coruscant", "coruscant"),
    ("naboo", "naboo"),
    ("kamino", "kamino"),
    ("mustafar", "mustafar"),
    ("bespin", "bespin"),
    ("holowan", "holowan"),
    ("cybot", "tatooine"),
    ("industrial automaton", "nal-hutta"),
    ("baktoid", "geonosis"),
    ("colicoid", "colla-iv"),
    ("separatist", "geonosis"),
    ("imperial", "coruscant"),
    ("republic", "coruscant"),
]

DROID_MANUFACTURERS: dict[str, str] = {
    "Industrial Automaton": "nal-hutta",
    "Cybot Galactica": "tatooine",
    "Holowan Laboratories": "holowan",
    "Holowan Labs": "holowan",
    "Baktoid Combat Automata": "geonosis",
    "Baktoid Armor Workshop": "geonosis",
    "Colicoid Creation Nest": "colla-iv",
    "Arakyd Industries": "coruscant",
    "Publictechnic": "coruscant",
    "AccuTronics": "coruscant",
    "Serv-O-Droid": "coruscant",
    "Verpine": "roche-asteroids",
}

CATEGORY_OVERRIDES: dict[str, dict[str, str]] = {
    "jedi": JEDI,
    "sith": SITH,
    "characters": CHARACTERS,
}
