#!/usr/bin/env python3
"""Cinematic hero-banner prompts for Planet Directory entries."""

from __future__ import annotations

from parse_csharp_data import load_planets

STYLE_SUFFIX = (
    "Cinematic Star Wars digital illustration hero banner, 1536x1024, 16:9. "
    "Hyper-detailed sci-fi matte painting, dramatic rim lighting, rich atmospheric depth, "
    "premium encyclopedia header art quality. No text, no logos, no watermarks."
)

PLANET_OVERRIDES: dict[str, str] = {
    "tatooine": "Twin suns over endless golden sand dunes with moisture vaporators and distant domed homesteads",
    "naboo": "Verdant Naboo rolling hills with Theed golden domes and waterfalls beside a turquoise lake",
    "coruscant": "Layered ecumenopolis skyline from upper atmosphere with traffic lanes and Senate district glow",
    "hoth": "Frozen white tundra with ice caves and distant AT-AT walker silhouettes under aurora sky",
    "mustafar": "Volcanic lava rivers and obsidian cliffs with molten falls and ash-choked red sky",
    "dagobah": "Misty swamp forest with twisted roots, hanging moss, and murky green bog water",
    "bespin": "Cloud City floating platforms in orange tibanna cloud sea with sunset horizon",
    "alderaan": "Peaceful snow-capped mountains and verdant valleys under soft blue skies before destruction",
    "endor": "Giant wroshyr trees with forest moon canopy and Ewok village rope bridges at golden hour",
    "yavin-4": "Massassi temple stone pyramids emerging from dense jungle with rebel base launch activity",
    "kamino": "Stilt cities above storm-wracked ocean with cloning facility spires and landing platforms",
    "geonosis": "Red rock droid factory spires and arena colosseum on arid desert planet horizon",
    "utapau": "Sinkhole city tiers inside vast sandstone cavern with windmill platforms and mist",
    "felucia": "Bioluminescent fungal jungle with pink and purple giant mushrooms and misty wetlands",
    "mandalore": "White domed cities on war-scarred red planet surface with beskar foundry smoke",
    "dathomir": "Red misty nightsister swamps with stone fortress and twisted dead trees",
    "korriban": "Valley of Dark Lords with ancient Sith tombs carved into orange desert cliffs",
    "moraband": "Sith homeworld barren red wastes with monolith tombs and lightning-charged sky",
    "exegol": "Dark storm planet with Sith cult citadel spires and forked lightning over black rock",
    "jakku": "Scavenger camps among crashed Star Destroyer wrecks half-buried in desert sand",
    "scarif": "Tropical palm coastline with Imperial Citadel tower and turquoise shielded bay",
    "jedha": "Desert moon holy city with kyber crystal spires and Imperial occupation shadows",
    "crait": "White salt flats with red mineral dust trails and abandoned rebel base entrance",
    "ahch-to": "Storm-lashed ocean islands with ancient stone Jedi temple steps and crashing waves",
    "lothal": "Grass plains with Imperial factory smokestacks and Ghost starship silhouette at sunset",
    "dantooine": "Rolling grassland rebel base with sensor arrays under peaceful blue sky",
    "kashyyyk": "Wroshyr tree canopy layers with rope bridges and mist over deep jungle rivers",
    "mon-cala": "Underwater Mon Calamari coral city with bioluminescent domes and bubble fields",
    "rishi": "Rishi moon tropical island with clone listening post on foggy volcanic peak",
    "christophsis": "Crystal hex-wall battlefield city with blue kyber-like mineral formations",
    "saleucami": "Mosaic grassland with clone trooper medic camp and lavender twilight sky",
    "mortis": "Surreal Force nexus world with floating monoliths and purple-green aurora sky",
    "bracca": "Scrapyard planet of stacked starship hulls with crane silhouettes in orange haze",
    "cantonica": "Canto Bight casino resort strip on desert coast with neon and luxury speeders",
    "pasaana": "Rolling orange desert festival dunes with giant worm tracks and spice caravan",
    "kijimi": "Snow-covered alpine town with narrow alleys and warm window glow under aurora",
    "sullust": "Volcanic industrial world with lava vents and factory complexes glowing at night",
    "mygeeto": "Crystalline ice-covered banking colony with laser-scarred bridge platforms",
    "serenno": "Cliffside aristocratic estate on misty green world with elegant manor spires",
    "ossus": "Jedi library world with ancient trees and ruined temple archives in golden light",
    "dxun": "Jungle moon orbiting red Onderon with mandalorian camp and beast-rider cliffs",
    "ziost": "Frozen Sith world with ice-covered city ruins and pale aurora over glaciers",
    "manaan": "Ocean world Kolto harvesting station with underwater glass domes and reefs",
    "taris": "Multi-level urban sprawl under perpetual rain with neon lower levels and rakghoul haze",
    "telos": "Restoration project world with Ithorian herdship over recovering green valleys",
    "malachor": "Dark side corrupted world with petrified Sith battlefield and crimson storm clouds",
    "malachor-v": "Petrifed Sith battlefield with obsidian surface and Trayus academy ruins under red sky",
    "ryloth": "Twi'lek homeworld showing day side desert and night side underground resistance caverns",
    "rodia": "Jungle swamps with humid green canopy and hunter clan village platforms",
    "concordia": "Mandalore moon with beskar mines and white dome settlements in red dust",
    "carida": "Imperial academy world with military training grounds and orbital shipyards visible",
    "abednedo": "Abednedo is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "aldhani": "Alpine rebel heist ridges with Imperial payroll convoy in misty valley",
    "aleena": "Aleena is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "alpheridies": "Alpheridies is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "althir": "An Outer Rim world contested during the Mandalorian Wars between Neo-Crusaders and Republic.",
    "ando": "Ando is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "anzat": "Anzat is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "atzerri": "A trade world of sprawling markets and black-market technology stalls.",
    "bakura": "An Outer Rim world invaded by the Ssi-ruuk during the Imperial era.",
    "balmorra": "Industrial factory world with war forges, smoke stacks and siege trenches",
    "balosar": "Balosar is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "barab-i": "Barab I is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "bastion": "Bastion is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "batuu": "Black Spire Outpost market with petrified trees and distant Wild Space horizon",
    "bestoon": "Bestoon is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "bilbringi": "Shipyard orbital platforms with Bothan defense fleet in background",
    "bothawui": "Rocky intelligence hub with spy satellite dishes and Bothan city terraces",
    "byss": "Byss is a deep core world documented across the nine saga films, live-action and animated series, Knights of the Old…",
    "cadomai": "Cadomai is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "cadomai-prime": "Cadomai Prime is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "castell": "A urban colony world of the Colicoid species and droid manufacturing.",
    "cathar": "Savanna world with Mandalorian bombardment scars and Cathar settlement mesas",
    "cerea": "Cerea is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "chaasadai": "Chaasadai is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "chalacta": "Chalacta is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "champala": "Champala is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "chandrila": "Green Core world rolling hills with coastal Senate districts and peaceful silver-roofed cities",
    "chorin": "Chorin is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "clakdor-vii": "Clak'dor VII is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "colla-iv": "Colla IV is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "cona": "Cona is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "concord-dawn": "Mandalorian colony mesas with Protector outposts and orange dawn sky",
    "corbos": "A mining colony world where lost Jedi children were discovered in ancient ruins.",
    "corellia": "Urban shipyard skyline with orbital drydocks and Corellian freighters launching at sunset",
    "csilla": "Frozen Chiss hive cities in blue ice caverns with aurora sky",
    "devaron": "Devaron is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "dorin": "Dorin is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "duro": "Duro is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "dxun": "Jungle moon with mandalorian camp fires and beast-rider cliffs at twilight",
    "eadu": "Storm-lashed kyber research citadel on black cliff with lightning storms",
    "elom": "Elom is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "eshan": "Eshan is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "falleen": "Falleen is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "fondor": "Massive orbital supercarrier docks above industrial cloud layers",
    "gamorr": "Gamorr is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "gand": "Gand is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "garel": "Rocky moon city with Rebel supply docks and multi-moon night sky",
    "gentes": "Gentes is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "glee-anselm": "Glee Anselm is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "honoghr": "A devastated homeworld of the Noghri, poisoned by Imperial chemical warfare.",
    "hosnian-prime": "Core world cityscape with Senate dome towers under blue skies before superweapon destruction",
    "iktotch": "Iktotch is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "iridonia": "Iridonia is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "ithor": "Ithor is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "kafrene": "A mining colony in the Ring of Kafrene where Bodhi Rook met Galen Erso's messenger.",
    "kalee": "Kalee is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "kalevala": "Ocean moon with Kryze royal estates and Mandalorian shipyard domes",
    "kamino-clone-origin": "Kamino (clone origin) is a outer rim territories world documented across the nine saga films, live-action and animated…",
    "kaon": "Sith weapons factory world with red-lit assembly lines and orbital bombardment scars",
    "kemplex-nine": "A Deep Core astronomical anomaly destroyed when ancient Sith superweapons detonated during the Great Sith War.",
    "kessel": "Spice mine trenches and glimmering maelstrom sky over harsh desert canyons",
    "kiffex": "Kiffex is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "kintan": "Kintan is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "kinyen": "Kinyen is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "klatooine": "Klatooine is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "krownest": "A snowy Mandalorian world of Clan Wren fortresses and beskar mines.",
    "kuat": "Orbital shipyard rings around blue-green world with Star Destroyer construction",
    "kubindi": "Kubindi is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "lahmu": "Remote ocean-edged farm ridges with Erso family homestead at sunset",
    "lannik": "Lannik is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "lehon": "Rakata temple ruins over tropical ocean with ancient star maps carved in stone",
    "lhuguenok": "L'huguen'ok is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "lianna": "Lianna is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "lira-san": "Lira San is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "lorrd": "Lorrd is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "lowick": "Lowick is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "makeb": "Resort mesas on colossal repulsorlift pylons above golden cloud sea",
    "malastare": "Podracing plains with fuel refineries and Dug excavation sites",
    "maridun": "A grassland world where Lurmen colonies faced Separatist superweapon tests.",
    "mimban": "Muddy misty swamp battlefield with Imperial trenches and native ruins",
    "mirial": "Mirial is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "moraband": "Sith homeworld barren red wastes with monolith tombs and lightning-charged sky",
    "muunilinst": "Muun banking spires and vault towers above urban canyon streets",
    "mygeeto-colony": "Mygeeto colony is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "nal-hutta": "Swamp homeworld with polluted green fog, Hutt palace spires and orbiting smuggler moon",
    "narkina-5": "An Imperial factory moon of assembly lines where Cassian Andor was imprisoned.",
    "neimoidia": "Fog bridge cities of Trade Federation with golden spires above green mist",
    "oba-diah": "Volcanic Pyke spice mines with lava rivers and syndicate landing pads",
    "odessen": "Sanctuary valley with Alliance base domes and distant mountain ring",
    "ojom": "Ojom is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "olega": "Olega is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "ord-mantell": "Scrapyard port with orbital salvage rings and bounty hunter cantina district",
    "orto": "Orto is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "orto-plutonia": "Orto Plutonia is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "ossus": "Jedi library world with ancient trees and ruined temple archives in golden light",
    "pantora": "Pantora is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "parwan": "Parwan is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "patrolia": "Patrolia is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "peragus": "Asteroid mining station with fuel refinery tunnels and ion cannon turrets",
    "phatrong": "Phatrong is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "phindar": "Phindar is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "plazir-17": "Domed pleasure world with neon resort strips and luxury speeder lanes",
    "primus-goluud": "A red supergiant system used as a Sith staging point during the Great Hyperspace War.",
    "qika": "A contested world in the New Sith Wars where Brotherhood forces clashed with Republic armies.",
    "quarzite": "Quarzite is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "quermia": "Quermia is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "rattatak": "Rattatak is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "rhen-var": "An ice moon with Jedi sanctuaries and ancient Force monuments.",
    "roche": "Roche is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "rodia": "Humid jungle swamps with hunter clan village platforms and green canopy",
    "ruusan": "Barren valley battlefields with thought-bomb crater and scattered Jedi ruins",
    "saleucami": "Mosaic grassland with clone medic camp and lavender twilight sky",
    "scarif": "Tropical palm coastline with Imperial Citadel tower and turquoise shielded bay",
    "selonia": "Selonia is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "sembla": "Sembla is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "shili": "Shili is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "shukut": "Shukut is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "siniteen": "Siniteen is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "skako": "Skako is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "skustell": "Skustell is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "sorgan": "A remote forest world where Mandalorian warriors protected a vulnerable village.",
    "sriluur": "Sriluur is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "starkiller-base": "Frozen Ilum converted to superweapon trench with dark side energy collectors",
    "stygeon-prime": "A mountainous world housing the Spire, a Separatist prison for Jedi captives.",
    "sullust": "Volcanic industrial world with lava vents and factory complexes glowing at night",
    "thisspias": "Thisspias is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "tholoth": "Tholoth is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "tibrin": "Tibrin is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "toola": "Toola is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "toydaria": "Toydaria is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "trandosha": "Trandosha is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "troiken": "An ice world where the Stark Commercial Combine made its last stand against Republic forces.",
    "uba-iv": "Uba IV is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "uvena-prime": "Uvena Prime is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "vinsoth": "Vinsoth is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "wayland": "Wild jungle with Mount Tantiss storehouse spire emerging from canopy",
    "wobani": "Imperial prison labor camps in dusty canyons under guard towers",
    "wroona": "Wroona is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "yablari": "Yablari is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "yagdhul": "Yag'Dhul is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "yar-togna": "Yar Togna is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "zeltros": "Zeltros is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "zolan": "Zolan is a outer rim territories world documented across the nine saga films, live-action and animated series, Knights…",
    "zygerria": "Zygerria is a outer rim territories world documented across the nine saga films, live-action and animated series,…",
    "ambria": "A desolate wasteland poisoned by Sith alchemy, later home to Master Thon's Jedi enclave.",
    "thule": "A secret Sith stronghold world used by the Brotherhood of Darkness and later Imperial cultists.",
    "krayiss-ii": "A dark side nexus world of Sith temples haunted by trapped spirits and ancient holocrons.",
    "khar-delba": "An icy Sith world and fortress moon of Naga Sadow's empire during the Great Hyperspace War.",
    "khar-shian": "The rocky moon fortress companion to Khar Delba, anchoring Sadow's ancient invasion fleets.",
    "rhelg": "One of the five sacred Sith worlds of the Sith Empire, ruled by the Sith Lord Kalimash Persada.",
    "ch-hodos": "A volcanic Sith world among the five sacred domains of the Old Sith Empire.",
    "jaguada": "A red desert Sith world with temple complexes tied to the Great Hyperspace War era.",
    "tund": "A gas-shrouded world of pureblood Sith sorcerers and strange Force traditions.",
    "vjun": "A acid-rain world where Count Dooku built Bast Castle amid ruins of Force-worshipping nobility.",
    "atthiss": "A jungle tomb world of the ancient Sith species, overrun by corrupted beasts and dark side relics.",
    "voss": "A mist-shrouded world of prophetic Voss Mystics contested by Jedi, Sith, and the Eternal Empire.",
    "belsavis": "An ice world hiding a vast Republic prison vault containing ancient Sith superweapons and warlords.",
    "quesh": "A toxic jungle world rich in 'adrenal' chemicals, fought over by Republic and Empire in the Old Republic era.",
    "empress-teta": "A Deep Core industrial world and capital of the Tetan monarchy, central to the Great Sith War.",
    "prakith": "A fortress world of the Imperial Inquisitorius and ancient Sith catacombs beneath its citadels.",
    "koros-major": "The carbonite-rich founding world of the Empress Teta system and early Unification Wars.",
    "kesh": "An isolated continent world where the Lost Tribe of Sith survived for millennia after a crash landing.",
    "almas": "A desert world in the Cularin system housing a Jedi academy built over an ancient Sith fortress.",
    "cularin": "A binary-star system world of dense jungles and Force anomalies tied to Sith experimentation.",
    "foerost": "An ancient shipyard world seized by the Sith during the Great Sith War for dreadnought construction.",
    "koros": "A Deep Core system anchor world linked to Empress Teta's unification campaigns and Sith incursions.",
    "myrkr": "A forest world of ysalamir Force-null zones, used as a base by smugglers and later Imperial factions.",
    "nirauan": "A remote jungle world with a Chiss hand of Thrawn's hidden fortress and ysalamir groves.",
    "hypori": "A factory moon of droid foundries where General Grievous was first revealed to the Jedi.",
    "sleheyron": "A Hutt-linked trade world referenced in KOTOR as a rival hub to Nar Shaddaa's shadow economy.",
    "rekkiad": "An ice world where Sith Emperor Vitiate's mask was hidden among tribal Mandalorian graves.",
    "yavin-8": "An ocean moon of Yavin Prime with Massassi ruins and Jedi Exile training sites.",
    "yavin-13": "A remote moon in the Yavin system tied to Sithspawn experiments and exile colonies.",
    "had-abbadon": "A legendary Deep Core throne world concept tied to dark side imperial ambitions in early drafts.",
    "khomm": "A Deep Core cloning world of uniform Arkanian Offshoot communities and genetic laboratories.",
    "columus": "A low-gravity Core world of floating cities and Columi observers during galactic conflicts.",
    "centares": "A Mid Rim battleground world where art and war collided under Imperial occupation.",
    "kuar": "A Sith world used for dark side training and Brotherhood of Darkness trials.",
    "sanbra": "A scholarly world and holonet hub near the Outer Rim trade lanes.",
    "ubrikkia": "A Mid Rim industrial world known for Ubrikkian Industries repulsorcraft and shipyards.",
    "volik": "A Unknown Regions world linked to Sith Empire exile routes and hidden fleet movements.",
    "arbra": "A jungle world with extensive cave networks used as a Rebel base in Legends continuity.",
    "daluuj": "An ocean world of island chains and wrecked starships from ancient Sith skirmishes.",
    "iego": "The World of a Thousand Moons, a remote world trapped by a Separatist laser web during the Clone Wars.",
    "susevfi": "A volcanic retreat world of SoroSuub executives and later Jedi refuge sites.",
    "tund-minor": "A companion world to Tund associated with Sith sorcerer enclaves and dark side sects.",
    "ziost-ii": "A chart label for secondary Ziost orbit facilities during Old Sith Empire logistics records.",
    "stygium-caldera": "An asteroid caldera rich in stygium crystals used for cloaking devices and Sith artifacts.",
    "nicht-ka": "A barren Sith world with tomb cities from the era before the Great Hyperspace War.",
    "xoxaan-tomb": "A forgotten Sith mausoleum world tied to one of the first Sith Lords after the Hundred-Year Darkness.",
    "bogo-rai": "A Unknown Regions world referenced in Sith Empire exile charts and Chiss border surveys.",
    "sorzus-ne": "A Sith world associated with Sorzus Syn's alchemical texts and early Sith pureblood colonies.",
    "korriban-moon": "An ash-dark moon orbiting Korriban with orbital tombs and Sith academy staging platforms.",
    "yavin-prime": "The gas giant anchoring the Yavin system, orbited by Yavin 4 and other Massassi-touched moons.",
    "tatoo-i": "The primary star of the Tatoo system, whose intense heat shaped Tatooine's desert ecology.",
    "tatoo-ii": "The twin sun of Tatooine's binary system, defining the iconic double-sunset horizon.",
    "subterrel": "A mining world of underground cities and podracing circuits on hostile surface terrain.",
    "praesitlyn": "A communications hub world fought over during Clone Wars campaigns for its HoloNet relay nodes.",
    "druckenwell": "A Mid Rim factory world supplying components to galactic shipwrights across multiple eras.",
    "hapes": "The crown world of the Hapes Consortium, isolated by transitory mists and royal matriarchy.",
    "dathomir-sister-moon": "A companion moon in the Dathomir system tied to Nightsister orbital rituals.",
    "gorog": "A dark side world of the Gorog assassin cult within the Killik hive mind expansions.",
    "yoggoy": "A Killik nest world on the fringes of the Unknown Regions hive collective.",
    "ghomrassen": "Ghomrassen, a rocky Tatooine region moon and mining settlement in Legends surveys.",
    "adumar": "A Wild Space world obsessed with starfighter dueling culture, courted by New Republic and Empire.",
    "borleias": "A Colonies world with a vital planetary shield generator, contested in the New Republic era.",
    "ebaq-9": "An asteroid fortress in the Deep Core used by the New Republic against Yuuzhan Vong incursions.",
    "mortis": "A ethereal Force nexus realm manifesting as a planetoid with the Father, Son, and Daughter.",
    "abafar": "A desert world with a sunken municipal landfill and Clone Wars fuel depot.",
    "raxus-secundus": "The official capital world of the Confederacy of Independent Systems during the Clone Wars.",
    "leesis": "Leesis, a moon in the Christoph system used for forward clone staging areas.",
    "anaxes": "A Core fortress world of the Republic Navy, reduced to an asteroid field during the Clone Wars.",
    "ringo-vinda": "A Mid Rim orbital station world blockaded during the Clone Wars biochip crisis.",
    "scipio": "The headquarters world of the InterGalactic Banking Clan on a crystalline alpine plateau.",
    "lwhekk": "The Ssi-ruuvi homeworld of humid jungles and entechment weapon factories.",
    "bakura-prime": "The primary inhabited world of the Bakura system invaded during the Ssi-ruuvi incursion.",
    "dantooine-moon": "A sparsely settled moon used for Rebel listening posts near Dantooine.",
    "taris-undercity": "The rakghoul-infested foundation levels of Taris before and after planetary bombardment.",
    "ahahta": "Ahto City on Manaan, the floating kolto harvesting capital of the Selkath.",
    "sernpidal": "An Outer Rim world destroyed when its moon was pulled into the planet by Yuuzhan Vong dovin basals.",
    "hapes-cluster": "The navigational heart of the Hapes Consortium's ninety-three-world isolationist realm.",
    "kamino-prime": "The storm planet Kamino, homeworld of clone template production for the Grand Army.",
    "rishi-moon": "The tropical Rishi moon housing a Republic listening post above the Rishi Maze approach.",
    "begeren": "A Sith industrial world of tomb-cities and ore refineries that supplied the Old Sith Empire's war forges.",
    "bosthirda": "A remote Sith Space world of fortress monasteries used during the Golden Age of the Sith.",
    "dromund-fels": "A moon in the Dromund system orbiting Dromund Kaas, used for Sith training trials and dark side rituals.",
    "dromund-ixin": "A storm-wracked moon of the Dromund Kaas system housing Sith academies and exile colonies.",
    "dromund-kalakar": "Kalakar Six — a volcanic moon in the Dromund system where Sith alchemists forged weapons and relics.",
    "dromund-tyne": "A mist-shrouded moon of Dromund Kaas used as a retreat for Sith sorcerers and assassin initiates.",
    "jaguada-moon": "The ash-gray moon of Jaguada, site of Sith beacon towers and invasion fleet staging yards.",
    "kalsunor": "A barren Sith world of obsidian plains where ancient Dark Lords buried war trophies and holocrons.",
    "korriz": "A Korriban sister world of red deserts and satellite tomb complexes tied to the Valley of the Dark Lords.",
    "nfolgai": "A forgotten Sith tomb world of crumbling pyramids and sealed mausoleums from the Old Sith Wars.",
    "arkania": "An icy Colonies world famed for genetic laboratories and Arkanian Offshoot communities with Sith-era ties.",
    "korriban-outpost": "An orbital logistics station serving Korriban's academy complexes and tomb excavations.",
    "agamar": "Misty grassland battlefields with wrecked Separatist droid carriers and clone trooper outposts",
    "denova": "Lush jungle mountains with rocky cliffs, wild beasts, and mercenary fortress settlements",
    "bardotta": "Sacred temple spires on a fog-shrouded Colonies world of mystic Bahk-tov Council halls",
    "denon": "Urban Inner Rim metropolis with layered city districts and busy orbital traffic lanes",
    "kiros": "White marble Togruta artisan colonies with domed galleries on a temperate green world",
    "lotho-minor": "Toxic industrial scrap planet with acid rain, junk processing towers, and slag wasteland",
    "ringo-vinda": "Mid Rim orbital ring station world with massive circular habitat structures in space",
}


def _trim_description(desc: str, max_len: int = 180) -> str:
    text = desc.strip()
    if "Essential Atlas" in text or "StarWars.com galaxy map" in text:
        return ""
    if len(text) > max_len:
        text = text[:max_len].rsplit(" ", 1)[0] + "…"
    return text


def planet_prompt(entry: dict[str, str]) -> str:
    slug = entry["slug"]
    if slug in PLANET_OVERRIDES:
        scene = PLANET_OVERRIDES[slug]
    else:
        name = entry.get("name", "alien world")
        region = entry.get("region", "the galaxy")
        desc = _trim_description(entry.get("description", ""))
        if desc:
            scene = (
                f"Cinematic planetary landscape of {name} in the {region}, {desc}. "
                f"Dramatic surface vista with distinctive terrain, atmosphere, and sci-fi scale"
            )
        else:
            scene = (
                f"Cinematic planetary landscape of {name}, a distinctive {region} world with "
                f"dramatic alien terrain, rich atmosphere, and epic Star Wars sci-fi scale"
            )
    return f"{scene}. {STYLE_SUFFIX}"


def all_planet_prompts() -> dict[str, str]:
    return {e["slug"]: planet_prompt(e) for e in load_planets()}


if __name__ == "__main__":
    prompts = all_planet_prompts()
    print(f"Generated {len(prompts)} planet hero prompts")
