#!/usr/bin/env python3
"""Curated Related Archives links for directory entries that need explicit associations."""

from __future__ import annotations

# (category, slug) -> list of (label, value, route)
RELATED_ARCHIVE_OVERRIDES: dict[tuple[str, str], list[tuple[str, str, str]]] = {
    ("jedi", "bastila-shan"): [
        ("Jedi", "Revan", "jedi/revan"),
        ("Sith", "Darth Revan", "sith/darth-revan"),
        ("Sith", "Darth Malak", "sith/darth-malak"),
        ("Planet", "Taris", "planet/taris"),
        ("Planet", "Dantooine", "dantooine"),
        ("Planet", "Rakata Prime", "planet/rakata-prime"),
        ("Force power", "Battle Meditation", "force-powers/battle-meditation"),
        ("Force power", "Mind Trick", "force-powers/mind-trick"),
        ("Conflict", "Mandalorian Wars", "wars-conflicts/mandalorian-wars"),
        ("Ship", "Ebon Hawk", "ships/ebon-hawk"),
        ("Ship", "Endar Spire", "ships/endar-spire"),
        ("Faction", "Republic", "factions/republic"),
        ("Chronicle", "Old Republic", "chronicles/galactic-history/old-republic"),
    ],
    ("jedi", "jolee-bindo"): [
        ("Jedi", "Revan", "jedi/revan"),
        ("Planet", "Kashyyyk", "planet/kashyyyk"),
        ("Planet", "Dantooine", "dantooine"),
        ("Force power", "Mind Trick", "force-powers/mind-trick"),
        ("Ship", "Ebon Hawk", "ships/ebon-hawk"),
        ("Faction", "Republic", "factions/republic"),
        ("Chronicle", "Old Republic", "chronicles/galactic-history/old-republic"),
    ],
    ("jedi", "meetra-surik"): [
        ("Sith", "Darth Traya", "sith/darth-traya"),
        ("Sith", "Darth Nihilus", "sith/darth-nihilus"),
        ("Sith", "Darth Sion", "sith/darth-sion"),
        ("Jedi", "Revan", "jedi/revan"),
        ("Planet", "Malachor V", "planet/malachor-v"),
        ("Planet", "Dantooine", "dantooine"),
        ("Planet", "Telos", "planet/telos"),
        ("Planet", "Dxun", "planet/dxun"),
        ("Force power", "Force Heal", "force-powers/force-heal"),
        ("Force power", "Force Sense", "force-powers/force-sense"),
        ("Conflict", "Mandalorian Wars", "wars-conflicts/mandalorian-wars"),
        ("Ship", "Ebon Hawk", "ships/ebon-hawk"),
        ("Faction", "Republic", "factions/republic"),
        ("Chronicle", "Old Republic", "chronicles/galactic-history/old-republic"),
    ],
    ("jedi", "satele-shan"): [
        ("Jedi", "Revan", "jedi/revan"),
        ("Planet", "Coruscant", "coruscant"),
        ("Planet", "Tython", "planet/tython"),
        ("Force power", "Battle Meditation", "force-powers/battle-meditation"),
        ("Force power", "Force Push", "force-powers/force-push"),
        ("Conflict", "Great Galactic War", "wars-conflicts/great-galactic-war"),
        ("Faction", "Republic", "factions/republic"),
        ("Chronicle", "Old Republic", "chronicles/galactic-history/old-republic"),
    ],
    ("jedi", "revan"): [
        ("Sith", "Darth Revan", "sith/darth-revan"),
        ("Sith", "Darth Malak", "sith/darth-malak"),
        ("Jedi", "Bastila Shan", "jedi/bastila-shan"),
        ("Jedi", "Meetra Surik", "jedi/meetra-surik"),
        ("Planet", "Malachor V", "planet/malachor-v"),
        ("Planet", "Dantooine", "dantooine"),
        ("Planet", "Taris", "planet/taris"),
        ("Planet", "Rakata Prime", "planet/rakata-prime"),
        ("Force power", "Mind Trick", "force-powers/mind-trick"),
        ("Force power", "Battle Meditation", "force-powers/battle-meditation"),
        ("Conflict", "Mandalorian Wars", "wars-conflicts/mandalorian-wars"),
        ("Ship", "Ebon Hawk", "ships/ebon-hawk"),
        ("Faction", "Republic", "factions/republic"),
        ("Faction", "Sith Empire", "factions/sith-empire"),
        ("Chronicle", "Old Republic", "chronicles/galactic-history/old-republic"),
    ],
    ("sith", "darth-revan"): [
        ("Jedi", "Revan", "jedi/revan"),
        ("Jedi", "Bastila Shan", "jedi/bastila-shan"),
        ("Sith", "Darth Malak", "sith/darth-malak"),
        ("Planet", "Malachor V", "planet/malachor-v"),
        ("Planet", "Dantooine", "dantooine"),
        ("Planet", "Rakata Prime", "planet/rakata-prime"),
        ("Planet", "Dromund Kaas", "planet/dromund-kaas"),
        ("Force power", "Force Lightning", "force-powers/force-lightning"),
        ("Force power", "Mind Trick", "force-powers/mind-trick"),
        ("Conflict", "Mandalorian Wars", "wars-conflicts/mandalorian-wars"),
        ("Ship", "Ebon Hawk", "ships/ebon-hawk"),
        ("Chronicle", "Old Republic", "chronicles/galactic-history/old-republic"),
    ],
    ("sith", "darth-malak"): [
        ("Jedi", "Revan", "jedi/revan"),
        ("Sith", "Darth Revan", "sith/darth-revan"),
        ("Jedi", "Bastila Shan", "jedi/bastila-shan"),
        ("Planet", "Taris", "planet/taris"),
        ("Planet", "Rakata Prime", "planet/rakata-prime"),
        ("Force power", "Force Lightning", "force-powers/force-lightning"),
        ("Ship", "Ebon Hawk", "ships/ebon-hawk"),
        ("Faction", "Sith Empire", "factions/sith-empire"),
        ("Chronicle", "Old Republic", "chronicles/galactic-history/old-republic"),
    ],
    ("sith", "darth-traya"): [
        ("Jedi", "Meetra Surik", "jedi/meetra-surik"),
        ("Sith", "Darth Nihilus", "sith/darth-nihilus"),
        ("Sith", "Darth Sion", "sith/darth-sion"),
        ("Planet", "Malachor V", "planet/malachor-v"),
        ("Planet", "Telos", "planet/telos"),
        ("Planet", "Dantooine", "dantooine"),
        ("Force power", "Force Drain", "force-powers/force-drain"),
        ("Chronicle", "Old Republic", "chronicles/galactic-history/old-republic"),
    ],
    ("sith", "darth-nihilus"): [
        ("Jedi", "Meetra Surik", "jedi/meetra-surik"),
        ("Sith", "Darth Traya", "sith/darth-traya"),
        ("Sith", "Darth Sion", "sith/darth-sion"),
        ("Planet", "Telos", "planet/telos"),
        ("Planet", "Malachor V", "planet/malachor-v"),
        ("Force power", "Force Drain", "force-powers/force-drain"),
        ("Chronicle", "Old Republic", "chronicles/galactic-history/old-republic"),
    ],
    ("sith", "darth-sion"): [
        ("Jedi", "Meetra Surik", "jedi/meetra-surik"),
        ("Sith", "Darth Traya", "sith/darth-traya"),
        ("Sith", "Darth Nihilus", "sith/darth-nihilus"),
        ("Planet", "Malachor V", "planet/malachor-v"),
        ("Force power", "Force Rage", "force-powers/force-rage"),
        ("Chronicle", "Old Republic", "chronicles/galactic-history/old-republic"),
    ],
    ("characters", "bastila-shan"): [
        ("Jedi", "Bastila Shan", "jedi/bastila-shan"),
        ("Chronicle", "Old Republic", "chronicles/galactic-history/old-republic"),
    ],
    ("characters", "jolee-bindo"): [
        ("Jedi", "Jolee Bindo", "jedi/jolee-bindo"),
        ("Chronicle", "Old Republic", "chronicles/galactic-history/old-republic"),
    ],
    ("characters", "meetra-surik"): [
        ("Jedi", "Meetra Surik", "jedi/meetra-surik"),
        ("Chronicle", "Old Republic", "chronicles/galactic-history/old-republic"),
    ],
    ("characters", "satele-shan"): [
        ("Jedi", "Satele Shan", "jedi/satele-shan"),
        ("Chronicle", "Old Republic", "chronicles/galactic-history/old-republic"),
    ],
}
